#!/bin/bash
exec rclone sync -v                                             \
       ./result/share/html/johnwiegley                          \
       fastmail:/johnw.newartisans.com/files/johnwiegley
