:PROPERTIES:
:ID:       4CCDD1F0-ABD2-403C-8E22-D2C82E1B3C2A
:SLUG:     why-i-see-beauty
:END:
#+filetags: :journal:
#+title: Why I see beauty

I realize now why I find beautiful things beautiful: because I miss God.
I miss the perfection about Him which my soul knew, before it lost its
way in this strange world of illusion. I have come to long for Him. I
copy down beautiful things that I read, and listen to music countless
times; I eat what I consider fine food, and bask in the sunlight of an
ocean paradise. All, not because there is anything constructive that I
truly hope to carry on, but because my soul misses Him, and longs for
anything which partakes of the beauty of His attributes. What is finer
is better, and anything better is closer to goodness. That is all I
want: to fill my soul with... Something which is like the joy of
returning home. Now if only a pure ray could transfix my being, and
alter my character forever in a manner that would be pleasing to Him --
this would be bliss.
