:PROPERTIES:
:ID:       04E3F469-3E4D-41B6-A375-A0006DB842CC
:SLUG:     the-stages-of-chess-mastery
:END:
---
title: The stages of chess mastery
tags: journal
---

* The reactionary player
:PROPERTIES:
:CUSTOM_ID: the-reactionary-player
:END:
A reactionary player has no plans of his own, and in the absence of
threats will make whatever move comes to mind. When pressure builds, he
typically tries to avoid attack, or makes single-move counter-attacks in
response. This grade of player is highly susceptible to combinations and
tactical setups, because he doesn't look far enough ahead to avoid them.

* The emotional player
:PROPERTIES:
:CUSTOM_ID: the-emotional-player
:END:
When a reactionist starts forming his own ideas, and pursues them even
in the presence of purposeful moves from his opponent, he will often
meet with success if he psychologically outlasts his opponent.

* The scientific player
:PROPERTIES:
:CUSTOM_ID: the-scientific-player
:END:
The scientist is also the calculating player. He achieves tactical
mastery through evaluation and analysis of the position. There is even a
fair bit of strategic knowledge used here, though without the sort of
ethereal cohesion the artist is able to develop.

* The artistic player
:PROPERTIES:
:CUSTOM_ID: the-artistic-player
:END:
The artist looks not to fulfill certain theories or guidelines, but
instead seeks out an indescribable "something" which counts as most
beautiful in his eyes. At this level, coordination of the pieces becomes
more natural, rather than labored, and calculation is more efficient,
since relevant lines are examined -- rather than everything that might
be possible. But overall, the artist lets his nose lead him in
interesting direction, engaging the intuition far more than rational
judgment.

* The masterful player
:PROPERTIES:
:CUSTOM_ID: the-masterful-player
:END:
The master understand chess in itself, and his own sense of right and
wrong has become somehow harmonized with the game. He can tell a bad
line from a good line almost from sight, without nearly the mental toll
incurred by the other players. He is acutely sensitive, and able to dive
very deeply into long calculation when it seems appropriate. This type
of player almost never loses "the plot", since the plot is more the game
itself to him, rather than a collection of pieces that must obey certain
rules. You might call this level the Zen of playing chess, since there
is a certain unity of mind between the player and the game he plays. In
fact, is there really so much distinction between the player and the
game?
