:PROPERTIES:
:ID:       9C28AC01-386C-4CB1-8BAD-313F0509A2AC
:SLUG:     emotional-memory
:END:
#+filetags: :journal:
#+title: Emotional memory

What if memory is really an emotional process? For example, when I
thought to recall the word "atavism", it didn't take very long for the
memory to come that it is going back to the forefathers, or a
directional intention back to origins. But, the reason for my
remembering that doesn't seem to be due to any analytical process, or
any actual selection of the memory; but very very far in the background
I have the dim sense of the emotion from when I learned the word. So
hearing that word triggers the emotion, and then feeling the emotion
it's almost like a momentary reliving of it. And in that reliving I have
a sense that fits that impression, and the form of that sense is the
definition. Almost as if it were an ideograph imprinted upon my
emotional memory. I have the emotional stimulation, and then the most
adept description of that stimulation is the sense of going back to the
forefathers.

In that sense our memory and our entire lexicon of knowledge, would
represent sort of holistically our emotional imprinting through life,
and be reflective of our personality -- or at least the character of the
experiences we've had. But is there some way that advantage can be taken
of that if it's true, in order to improve memory, or to take advantage
of the mind's system of recall? Because I don't ever remember studying,
or trying to remember what atavism is -- although I may have looked it
up more than once or twice -- but what about all the other words that I
know, that I only looked at momentarily? Could recall be at related to a
sensitivity to emotional context?

In parallel with the mind being emotively driven with respect to memory,
I would believe, that the same reason why a person does not like going
to certain place, or going to a certain house because it feels odd to
them, or doesn't sit right with the flavor of spirit that they have:
that this is the same thing which causes them to avoid certain lines of
thought. That patterns or categories of thoughts can have a "homey"
feeling, just like one's own home or home-town, while another town
across the way can just feel weird, even though it's never been
investigated. But that foreignness keeps the mind from wanting to get
near to it.
