:PROPERTIES:
:ID:       86F2B1FF-5B6E-49BD-BC0A-7721B8212A07
:SLUG:     the-need-for-morals
:END:
---
title: The need for morals
tags: journal
---

After wondering why I have been emphasizing morality so much lately
(both in writing and in my thoughts), a realization occurred to me:

As I've been thinking about it, quality is not achievable without
morals: Morals are the very laws by which quality becomes manifest.

In the case of hospitals, cleanliness is moral: There can be clean
hospitals with little quality, but there cannot be dirty hospitals that
excel in quality. In architecture, morality concerns proportion and
balance, and the utility of spaces. In programming, morality is what is
functional and appropriate; to call something "bad code" is to accuse it
of lacking morality in the domain of programming.

So morality is simply a quality of form, whereas what I call Quality is
a quality of essence. One is the health of the body, while the other is
the radiance of the spirit.

Once I made this connection, I discovered why I dwell on morality so
much: Because after my awakening to Quality this summer, my psyche had
shifted over to giving full preference to unconscious thinking (which
relates to Quality, the indefinable). This caused a whiplash such that
my conscious thinking became out of balance, and I began devaluing form
and procedure excessively. It is not that one or the other is
exclusively the best, but that they must work in harmony to achieve full
perfection.

Thus all of these thoughts on morality stem from an inward search for
balance between two parts of my consciousness: The part that is
ineffable, indescribable, and has little contact with this world; and
the part that is all about description and refinement, and how my
actions relate to the world around me.

I desire to love both, in the end. And do that, in philosophic terms,
I've needed to plumb their connection, until I can see them as parts of
one whole. This realization is a big step in that direction.

* Quote from Taoism
:PROPERTIES:
:CUSTOM_ID: quote-from-taoism
:END:
Just finished reading /Travels/, by Michael Crichton -- a rather
autobiography -- and found at the end a quotation that amazed me:

#+BEGIN_EXAMPLE
The surest test if a man be sane
Is if he accepts life whole, as it is,
Without needing by measure or touch to understand
The measureless untouchable source
Of its images...
#+END_EXAMPLE

Since this brief quote nearly encapsulates most of what I have been
trying to say in essay over the past several months. For a moment I just
had to close my eyes and let it sink in; and then revel in the joy that
other souls have trod this road before me. I am not alone.
