:PROPERTIES:
:ID:       C989AE63-FD9C-4032-9B26-05D556F2A7A7
:SLUG:     an-analogy-of-the-self
:END:
#+filetags: :journal:
#+title: An analogy of the self

An analogy of the self, described as a racing car:

Imagine, as a young person, you are given a beautiful, high-performance
racing car. This is your self.

The racing car sits in the garage at first, because we haven't learned
to drive it. It sits there for a few years, during youth, until around
age ten when we first give it a whirl.

Because it is such a beautiful car, we are inclined to take care of it.
If it were an old junker, however, or if we didn't realize its value, we
might let just it sit there and collect dust.

In other words: Our self-respect is directly related to the measure of
our efforts toward self-perfection. Give a teenager in love with cars a
Ferrari, and he will be out there polishing it every day, tuning the
engine -- into the late night if necessary. He will put all of his joy
into making that car everything it can be. Because he respects what he
has.

If you give the same Ferrari to someone who could care less, or if you
give the same car but somehow run-down or needing repair to someone who
doesn't appreciate its potential, they won't do much; maybe not even
turn it on. They might get embarrassed about it, resentful, even hate
its taking up curb space. They may start to wish it would just go away.
Maybe they'll even try to sell it, or demolish it themselves. This
happens because they don't respect what it is.

To go back to the teenager: There are two kinds who can appreciate such
a car: The kind who want to be race drivers, and the kind who like fancy
cars. Both will value the Ferrari and take superlative care of it. The
latter, however, will be afraid to drive it. He won't want to damage its
perfection in any way. He is attached to its condition and doesn't want
to sacrifice it -- even to unleash the potential of that awesome engine.
It would be mean cleaning, possible nicks and dents, etc. He doesn't
want to put it to the test.

The race driver, on the other hand, may like and admire the Ferrari's
figure and material qualities just as much, but he loves the sensation
of racing so much more that he is willing to do whatever work is
required to repair any damages or weaknesses. He loves what the car can
/do/ more than he loves what it /is/.

So the race driver takes his car out for a pleasant drive. The sun, the
hills, the wind in his face. He admires how beautifully the car drives,
and is quite happy with it.

Then he finds an open stretch -- something the car was /made/ for -- and
he can just feel it: the rightness of the car meeting a test of its
ability. He opens up on the gas and pushes her to top speed, screaming
down the road.

If the car is the self, then being selfless is when the car is fully
underway -- when you're so involved in driving it that you stop thinking
about the car. At low speeds the driver is still very aware of his car;
at high speeds he has no time to think about anything but where he's
going. He appreciates the car even still, but now it's an unconscious
appreciation, the way we appreciate our lungs or our heart, or our brain
for forming thoughts. The car and the driver have merged into a single
perception of speed and direction.

Where, in all of this, is what people refer to as the ego? We haven't
seen it yet, because ego happens when other people enter into the
relationship between car and driver.

Back to the person who doesn't like his car. That's not entirely true.
It's a beautiful car, and he knows this because other people -- other
drivers -- have told him so. He likes hearing it. When people give him
compliments he takes out a cloth and puts out a nice shine; he gives a
little energy, in the hope of more compliments. The more people who
praise him, the work more he does. But he only does the work others will
praise him for. He completely ignores the engine, because no one can see
that. He puts all of his energy into a fantastic exterior -- and then
never drives the car because that would only force him to clean it
again.

If no one stops by to compliment his car, he loses interest. He figures,
why bother. There is nothing about the car itself that pleases him. He
doesn't drive it, he hasn't learned what he has. He doesn't care. He
doesn't know it can do, because his only knowledge of it is in terms of
what other people say about it.

He could care less about the engine -- but he knows very well what kind
of exterior it has. If people compliment it, he'll know all about waxes
and what kind of paint and how many coats, in order to answer everyone's
wonderful questions. The point, though, is that he has no self-knowledge
whatsoever; he thinks only what others tell him. /His awareness of the
car's value exists only in relation to what other people think about
it/.

So on the one hand there is the reality of the car, and on the other
there is an image that gets built up and torn down in direction relation
to what others say about it. This image is the ego. It has nothing at
all to do with the car, only its appearance. The car never changes -- it
has been the same car all along. It's waiting to be driven.

The image, on the other hand, changes constantly. Every time a new
person sees it and makes a comment, the image is altered. The owner will
seek friendships only with certain kinds of people, because he realizes
that the quality of the image is dependent on consorting with people who
give the best comments.

If he were to meet a totally different crowd -- for example, a group of
race drivers who don't care about images at all -- he would feel utterly
lost, as though they had crushed him. His image doesn't exist in their
world; /he/ -- in terms of what he thinks about himself through the
opinions of others -- just doesn't exist for them. He would feel the
vacuum of non-definition surrounding him like a choking hand -- without
ever realizing that defining a car and driving a car are completely
separate matters.

Finally, humility in this scheme is very simple: Don't drive your car
where it can't go. Don't use it in a lake, don't drive it off a cliff.
Know that your car is a car, and use it accordingly.

Some believe that humility means not letting other people see their car
-- as a way to escape the ego, which is built on the comments of others.
They hide it in a garage and rarely drive it out, hoping in this way not
to be affected by what people say about their car. But this is not
humility; it is self-denial: wishing not to have the car at all, so that
one is neither affected by, nor affects, the world. No. You were given a
nice car to race it, not to reject the gift.

The driver represents the will, and there is only way for him out of
ego, and toward selflessness: Drive. When the thrill of racing down the
highway reaches you, there will be no more questions, no more doubts --
just the open road.
