:PROPERTIES:
:ID:       426DA112-4BE0-49A0-BA7B-AF11F7DC6D7E
:SLUG:     more-from-andalucia
:END:
#+filetags: :journal:
#+title: More from Andalucia

A favorite place after four is now the Plaça Industria, where a pair of
white benches remain in the shade for six hours, and people can be seen
strolling by endlessly. The town itself is not very large at all, so
that I'm beginning to recognize people as I see them for the fourth and
fifth time; as if we make it seem larger by all moving around, iterating
through the possible combinations of filling the streets so as to
portray at each moment a hundred different images of the same town with
the same people. I'm sure that on Friday an influx of visitors from the
city will come, but the slower pace of the week makes it feel eerily
like a dance that pivots around the only unmoving feature: the buildings
themselves. If we all stopped, how many would there really be?

People like to smoke here a /lot/. Sometimes I have this unaccountable
feeling of elation, and wonder if the air itself might have a measurable
nicotine content by now...

My plans to visit Switzerland have fallen through, so perhaps I will
spend three weeks instead in Marseilles. As I read the French on various
labels it make enough sense that maybe a quick language class there
would be fun. Ne c'est pas? They have the same here in Sitges for
Spanish, and Catalán.

Tomorrow feels like a good day for going into the big city (Barcelona).
All of my books are read, which certainly changes the character of the
day. Without that for a distraction, what will happen? It already makes
writing more attractive. The things we'd like to do but don't, for sake
of easier amusement...

A side note: Before beginning this trip I purchased a nice fountain pen,
to encourage writing. Now I cannot recommend one enough! It is like
drawing with a sixth finger on sheets of silk, the black lines rich and
always consistent and smooth, never skipping or blotting. Well, if you
are a pen and paper type, the joy of it had to be expressed.

* The beach cats' story
:PROPERTIES:
:CUSTOM_ID: the-beach-cats-story
:END:
This evening I ran across three beach cats roaming about. It was a
delight to see soft and furry shapes moving among the smooth, sometimes
shiny, human bodies. One was coal black, the others grey-striped. Since
they were very cute, and people do not pay them much attention, I think
it falls upon me to tell their story, of Blackie, Stripey and Bandy...

Blackie picked his way along the rocks, many times his size and well
away from the blue-green waves. At times he could find small lizards,
about a paw's length, clinging to the rocks and enough for an evening's
meal. But no, that one was too fast. Must find dinner elsewhere.

He trotted onto the sand from the rocks, where the beach merges with the
pier. It was just getting cool: he could feel it as a relaxation under
his warm fur -- often too warm. To left and right were still many of the
large, hairless ones who were always around when there was light. They
had so many different kinds of smells, and their behavior, capricious.
It was well enough to walk by the quiet ones, holding out a giant, bald
paw, but noise was a sure sign to stay away.

There, one is holding a paw still in the air. Sometimes that means food.
But not, just offering their smell. Sweet, like lilac.

Blackie passed towels, flat and smooth almost like grass, then under
broad umbrellas and onto the cement footpath. The cement was becoming
cool, but still too hard. Just a short distance more to the patches of
grass. Sometimes there were things to eat lurking there.

Ahead he saw Stripey, already at the grass, his head between the leaves
of a bush each the size of his head. Had he found something?

"Hola, Stripey, how goes it? Find anything good?"

Stripey lifted his head from the bush, sniffing the air. "Blackie,
nothing much, a beetle, a blade of crabgrass. It's not anchovy." (Here
Stripey used the local word "anchoa", lest you think he was speaking our
dialect).

"Maybe the Señor will have something today?"

"Don't be so sure. I were you, would not waste my time when a church
mouse might be choosing to skip vespers at this moment." Stripey showed
his "knowing" face, as if the doings of the hairless were anything but
utterly inscrutable.

"Well", called Blackie, "Perhaps, perhaps not. Fortune favors the
outstretched whisker!"

With that he tromped further into the city, Stripey giving a nod and
ducking his head back into the bush. On the other side of the monstrous
palm that was growing from the grass patch he saw Bandy, his old friend,
with his mouth around something green and succulent -- but bloodless.
Bandy's eyes were closed in the rapture of imbibing nutrients, which all
of their lean and matted kind sought so constantly. He did not see
Blackie going past, and so jumped at least a body-length to the side
when he finally looked up.

"Ay, Dios mío, Blackie, you could pick a better time for visiting.
Perhaps a heavier tread, or maybe you need a bell, like poor Tigrillo.
He will never taste a sea-bird again, poor amigo. Don't let them put the
bell of you, my Blackie! it tolls the anthem of our kind's sorrow, nor
peals any joy but by its silence when we finally lay to rest."

"Bandy, are you watching what you eat? Not every herb that tastes good
is worth eating. I think that succulent has left you addled."

"Ay, Blackie, it's not the plant but all these nights of ceaseless
wandering. To what end? I am still hunting this same stretch of shore,
still eking out my days and nights from hairless hands that want always
to touch me. I wonder if, as our Shakespaw put it, it is nobler to
suffer these slings and arrows -- though what those are, don't ask me --
or should I oppose and end them? To sleep in made beds, perchance to
dream, to find that country still undiscovered -- so different from
there grasses, every blade of which I must know by now. But ay mí, the
bell. No sooner the bell than like a fatted cow I head for pasture, and
there is no more Bandy. The same striped face, sí, but the lights
forever out, and no hope to kindle them again. To be a house-cat or not,
that is what I ask, Blackie! That is the question! What say you to
that?"

"Definitely the succulent, Bandy; stay away from that one, eh? Now I've
got to find something or start approaching more of the hairless than I
care to smell in one night. ¡Hasta luego!"

"Hasta, Blackie. Better luck to you, that these sad dreams may pass you
by!"

With a resigned look -- though to what outcome Blackie could not see --
Bandy turned his head to the succulent, just as Stripey rounded the
corner and started sniffing at the same. Blackie, with a significant
look to Stripey and a quick shake of his head, trotted past the grasses,
across the black asphalt, to another small patch of greenery where
larger bushes might hide livelier prey...

[[file:poem.falling.sun]]

* Crystallization has come
:PROPERTIES:
:CUSTOM_ID: crystallization-has-come
:END:
Tonight, while waiting for rest, the crystallization has come which I
knew was on its way. If felt much like the process of salt crystals
springing into being from a super-saturated liquid, forming intricate
shapes as you watch. This, combined with a feeling of euphoria and
freedom, is the real reason why some find the study of philosophy
irresistible.

The substance of the discovery itself is hard to put into words, without
sounding too much like terminology out of context, but essentially: I
had been dealing with the concept of God as within the scheme of
subject/object duality, in essence post-Quality, which caused other
experiences of quality to take on a competitive character. Viewed as
pre-Quality, the same experiences become cooperative, even supportive.
The major outcome of this will be to mollify greatly my tendencies
toward asceticism, since now the world seems a doorway, rather than a
distraction.

* Puzzled about unity
:PROPERTIES:
:CUSTOM_ID: puzzled-about-unity
:END:
Although "unity" remains a mystery, something has opened up that frees
me from a misapprehension that has been with me for at least a decade.

First, the understanding that my ideas of God -- however undefined they
have become -- are still, were still, framed in the mythos of the
subject/object duality. Thus, any perception of Quality in the world --
which must associate with an object, as it gives rise to an awareness of
that object -- was in a sense competing for my attention to higher
ideals. Whereas the way I am seeing it now, if God is outside of the
domain of objects entirely, even in the objective sense of an
indefinable quantity, one can view quality as the proof of an
intentional excellence potential in creation, in which attention pain to
quality is the very reason for attention in the first place. Quality is
like a brightness, the more of which there is, the more light is seen.

So now objects of quality take on the role, not of competitors, but
tokens, conjurations, candles. To behold quality is to see the proof of
the essence for which quality is the presence, for which objects
themselves are the means of display. It's then like a picture of one you
love: something to carry your focus back to that moment, at which time
the experience transcends the medium, while at the same time justifying
the medium itself. It leaves me wanting greater and further means of
experience Quality in my life.

* Purification permits seeing Quality
:PROPERTIES:
:CUSTOM_ID: purification-permits-seeing-quality
:END:
By purifying the heart, one can see clearly in order to find the
evidences of Quality, rather than be beguiled by the speciousness of
style...

This will mollify my tendencies toward asceticism. The pursuit of
philosophy is the hunt for such joys of discovery! Seeing God beneath
the dualism of the subject/object dichotomy...

On the one hand, Search[fn:1] is to find Quality: to sift among the
"changes and chances" of the world for signs, "footsteps in this
wilderness" that recall the True One.

Unity, however, is described as the collapse of all these differences
and distinctions. So now, with a more concrete conception of quality,
how does the relationship change with dawning of unity?

Quality is that which provokes a perceptible differentiation between the
unitary subject/object. "The Mother of All Things". Things are not
enduringly real, as in classical empiricism, but are real in so far as
quality makes them distinguished from the substrate of undifferentiated
unity. Is this where unity ties in?

Hence, you cannot "see" or even be cognizant of something, unless you
participate in this Quality-founded relationship. Further, such
"participation" is subject to will, making reality's degree of realness
susceptible to the focusing of attention/awareness. (That awareness
begets the world of the perceived harkens back to Sartre).

Instead of debating ontological "reality", let's call the moment of
Quality participation: experientially real. The degree to which our
lives feel real to us is directly related to the awakening of perception
through the presence of Quality, a comutual act whose degree is tied to
our willingness to experience it.

This is given in such sayings as "to stop and smell the roses". The idea
here is to take a moment to appreciate the quality manifest in the
bouquet of roses, the doing of which will not only make them more real
for us in at that moment, but will make life itself feels more real,
since it is, after all, comprised of an agglomeration of such moments.
It might also be described as "intensifying the reality of the present,
through a willful experience of Quality."

* Words often heard
:PROPERTIES:
:CUSTOM_ID: words-often-heard
:END:
Two words that are heard quite often here: "dime" and "vale". They are
both sounded with two syllables, as it "dee-may" and "vah-lay". "dime"
is used to begin interactive conversations, and seems to mean: Hello;
can I help you; what would you like; what is your choice? It literally
means "tell me". "vale" covers the whole range of: OK; right; well; see
you later; it's alright; that'll do; it's worth it; it fits; thank you;
and even sometimes, see you later. I think it literally means "it goes
with you", but I will have to look it up. So a typical exchange in the
shop sounds something like this:

#+BEGIN_EXAMPLE
Me: Hola
He: Dime
Me: Dame eso, pro favor
He: Bueno, es... (I hand money over)
He: Vale
Me: Gracias
He: Adiós
#+END_EXAMPLE

Quite an economy of words. Many exchanges are not more than one word
long from side to side!

* Buying a pillow
:PROPERTIES:
:CUSTOM_ID: buying-a-pillow
:END:
Right now I am in Barcelona itself, where I've come to buy a pillow. It
is raining for the first time, which is a good day to sit in trains and
subway cars. ... Now that the pillow is bought, I've decided to stop by
a restaurant to try the famous Spanish dish, paella, which looks like
sauteéd rice with seafood and another bits of vegetable...

* Paella
:PROPERTIES:
:CUSTOM_ID: paella
:END:
OK, that place must not be known for its paella. In fact, it tasted
rather like beef-flavored Rice-a-Roni. And I even prefer the little
vermicelli bits in Rice-a-Roni! Not to mention that it cooks in five
minutes or less. So, to date that's Paellas: 0, San Francisco Treat: 1.
Hmm... maybe even a market here for Uncle Ben's Paella? But this weekend
a friend is coming to Sitges; I'm sure she will help me find something
more representative.

A poem that goes for a Neruda-esque feel:

[[file:to.remember.me]]

* On Quality
:PROPERTIES:
:CUSTOM_ID: on-quality
:END:
This matter of Quality reveals a few places that Pirsig did not go in
his book. For example, by what standard is something of better quality
than another? He does not really go deeply into this, but does object to
its being entirely subjective. Perhaps quality is actually a response of
pre-existent reality to the function of awareness? The greater, the
better the awareness itself, the higher -- or maybe finer -- the
Quality. This implies that the best quality does not inhere to an object
or situation, but rather results from the best attempts to experience
such quality. However, this belies the fact that some situations do
facilitate the perception of Quality more than others. This results in
an inherent sense of scale, without identifying the nature of the scale.

Before the moment of quality there is no differentiation -- which Sartre
might call "the plenitude of being". Perhaps it is this state that the
Zen koans aim at when ask, "What was your face before you were born?"
or, "What is the sound of one hand clapping?" That is, what is that
essence of being which precedes the arising of subject and object?

* Finding /Atlas Shrugged/
:PROPERTIES:
:CUSTOM_ID: finding-atlas-shrugged
:END:
An interesting occurrence, which goes to exemplify the way things have
been happening on this trip: After reading /Zen/ the book which first
came to mind as dealing most directly with the issue of Quality was
/Atlas Shrugged/, by Any Rand. I'd always meant to read it again, but
where am I going to find a readable copy in España?

While walking by a photo shop, I noticed they had a very curious
selection of books in English, from Austen to Asimov to Tad Williams, a
favorite Scifi/Fantasy writer. It was a small selection, most eclectic,
but had a copy of /Great Expectations/, which I'd also been meaning to
read for a long time.

I went in to buy it, but it turns out to be some modern novel with the
same title. A bit disappointed, I turned the rack to see if there was
anything else. Just before the very last set of books, after pretty much
giving up on reading anything further here in Spain, was /Atlas
Shrugged/! How odd, I thought.

[[file:the.pretty.girls]]

[[file:the.sea.exhales]]

A first Quality-related poem, after a fine breakfast at La Granja Elsa:

[[file:loving.eye]]

[fn:1] This refers to the Valley of Search in the book /The Seven
       Valleys/, by Bahá'u'lláh
