:PROPERTIES:
:ID:       80BF2AD2-1D7C-428A-B82A-12C16E7C94B7
:SLUG:     estrucan-tombs-and-the-open-sea
:END:
---
title: Estrucan tombs, and the open sea
tags: journal
---

I am writing this evening from an old Roman amphitheater in Fiesole,
which is a town in the hills north of Florence, and also the oldest
settled town in Tuscany. There are both Langobard and Etruscan tombs
nearby, and even one lazy cat who thinks the shade under a wall of stone
is the best place to rest.

This is a pretty town, easily reached by bus, and quite different and
slower-paced than Florence. It has narrow streets and not yet any main
center I've found, except perhaps where the bus arrives. Tonight I will
eat at a place called "I Pulpa" (the octopii), and be able to comment on
food from smaller towns. (update: very nearly the same).

I have also found, here and everywhere, that Italians are fanatic about
that invention called "the receipt". Everyone wants you to walk away
with a receipt, as though by common agreement they had decided that
every hand brought into the world was deficient in the matter of holding
a receipt, and it was their given duty to remedy nature's lack. It
doesn't matter what kind of business, large or quaint: to leave without
that blessing in the form of printed paper was neither to be
contemplated or attempted. And so, carry bag filled with the proofs of
Italian commerce, I continued my journey onward.

* Roger continues his journey
:PROPERTIES:
:CUSTOM_ID: roger-continues-his-journey
:END:
Roger, from the short story a while back, also continues on his way:

Roger and his craft, together, came upon the approaching day. Without
the sun yet in the sky, it appeared as if they were nearing an island of
light beyond the horizon. First, the heavens turned a shade of pale,
draining color from the stars, until one-by-one they stepped out from
the hall of the sky. Then the waters became tinted as though somewhere,
a secret hand were feeding blue drops into the black of the sea.

Though at first, it was all grey, only grey, the way the world may have
seemed on its first day, before the creation of colors and of things to
reveal them. Just a faint, weak grey turning black into not-black. The
suggestion of colors occurred to the mind alone, who knew what they
would become, and where appear. Then the grey lost its somber purity,
admitting a secret joy that it, too, was eager to see the day come to
life. He yielded -- that pre-eternal, robed greyness of the first light
-- and stepped aside for the ladies, blue and pink and rose. Quickly
they came, playing marigolds into the sky, throwing bouquets that fanned
the light all over, from one side of the horizon to the other.

The sails of La Dolce Vita changed through every shade of white, now
becoming true, and even catching some of the colored rays as well as the
wind. The teak panels of the deck remembered their coffee brown, the
mast's aluminum its silver, the brass fittings their almost-gold, and
the flecked lines their flecks, as they ran fore and aft. The sun rose
to mount its throne in the sky, and he bestowed favor on all his
subjects, ranking them by the colors he chose to give.

All around, there was naught to be seen but the perfect sea. Nor line,
but the horizon's circle that kept the border of ocean from heaven's
blue. The sun, that could not be seen, made it all visible, and all one
by the many shades of blue: light above, dark below.

In the interface between water and sky, the constant congress of waves
made a stately progression from east to west. Some large, some small;
some true on their course, others erring to north or south; some
meeting, some parting, some synchronized at ever the same distance. No
two were the same, yet all were of one name, one essence. It was a
kingdom of forms whose brotherhood was absolute.

And somewhere in those depths, Roger knew, swam the great mammals of the
sea. Their pounding flukes offered towering sprays to the wind. Their
noble brow might gather ten thousand heads of men to equal such a
furrow. Their back slapped the seas like a child's hand in a bathtub.
Their heavy suspirations could be seen at a mile's distance. Their eyes
roved in watchful contemplation, whose sight had known all the fathoms
of the deep. And somewhere, they toiled and played, raised their pups,
sang great, epic poems whose heroes may have watched the first fires of
men with dark foreboding. Yet none were visible in all the folded carpet
of the sea's blue. It was empty, that sea; yet it was full. It was the
limit of the eye that made the difference.

Ahead rose the sun's ruby crown. The king awoke to his labors, setting
the waters aflame with ardor, summoning adoration by a mere glance, and
bowing all heads that could not master the vision. The sea was his cup
of wine, from which he rising head was wont to sip. As the redness of
morning passed, he lifted up a wreath of golden fire, and covered his
face in a veil of light that denied the furtive peeks of the profane. He
stood so his head looked over the horizon, and his considered his
creation thoughtfully, and found it merited another day.

But how long, a pilgrimage to that king; how far, the distance between.
La Dolce Vita climbed over the waves time and again, hour after hour,
but made no headway. He was the easiest goal to sail for, but the
hardest isle to reach. Even with wings she did not possess, the
wandering ship would have deepened her sense of failure. The whole of
the sky was his kingdom, forbidden to foot and sail; while the sea was
her domain: a great, vast, beloved journey, never beyond the reach of
his warm embrace. It was admiration alone that made the two as one,
united in their roles of king and subject -- as night and day are
divided and united by the sun -- so that in admiration she continued,
her eyes and heart a well-spring of treasures, while all else served the
clarity of her perception: waves and sky and sea.
