:PROPERTIES:
:ID:       C10BBD15-9F06-4708-B784-0976D2290368
:SLUG:     greeting-the-persians
:END:
#+filetags: :journal:
#+title: Greeting the Persians

Yesterday and today were spent serving at the Grand Canyon Bahá'í
Conference in Phoenix, Arizona. I was security there, which at these
conferences means standing at the door and checking for proof of
registration. I like doing it because it allows me to meet with the
people, and have a moment of connection with some I might otherwise
never meet -- from old couples speaking nothing but Persian, to young
ladies dressed to impress (and succeeding at it).

It was during this time, greeting a stream of Persian and other faces
and friendly eyes, that I came to realize something: I was not there
serving for the sake of God. That alone does not convey the satisfaction
it gave me, or that after fourteen hours of standing, I was exhausted
but not wearied. The way to explain it is that I came to see: these
people /were/ God. Whenever I did something for them, I was doing it for
Him. And whenever they smiled back at me (which most did, often), I saw
in their eyes a light as if He were smiling back at me. It was a time of
service that became like communion -- and exchange of gifts between
lover and Beloved. For this reason, when I was done, I felt I'd been
done a favor by the chance to be there, and look forward very much to
doing it again next year.
