:PROPERTIES:
:ID:       B9CD1BE9-60FB-40DB-84B1-436A2EEBD6BE
:SLUG:     variations-on-a-theme-of-sun-and-sand
:END:
---
title: Variations on a theme of sun and sand...
tags: journal
---

There has not been much novel happening, unless you count the ideas in
the novel I'm reading... So this letter hasn't much new to describe,
just lingering impressions of the area. It is small here, and I've
decided to move straight on to Florence, to spend seven weeks there
instead of one month. I have a contact who will introduce me to the
Bahá'í community, so there will be many more people to see -- for which
having more time than a few weeks will be nice.

It's been rewarding to slowly accumulate knowledge of a place, and
contacts with the people in it. There are several here now who greet me
in the streets, or converse with me in their free moments. And so far,
none of it in English. It has made language feel like a tool, with which
to catch a glimpse of the inner world of another soul. I suppose it's
always that way -- just easier to take for granted when it doesn't
require as much conscious thought.

Only one day of rain so far. The weather is surprisingly regular.

[[file:pressing.rain]]

* Coffee skin
:PROPERTIES:
:CUSTOM_ID: coffee-skin
:END:
#+BEGIN_EXAMPLE
Coffee skin; eyes, chocolate --
a dollop of cream
between the lips.
#+END_EXAMPLE

* Writing haiku
:PROPERTIES:
:CUSTOM_ID: writing-haiku
:END:
Much of the week has been spent trying to write a few good lines of
Haiku. The formula is simple: It follows a similar philosophy to the
Chinese paintings of the Ming(?) dynasty. The goal is to paint a picture
of what's missing, so that the unsaid element is perceived more directly
than the words. So, imagine something you want to describe, then remove
the main element you wish to convey. Then, find a combination of words
which makes this omission glaring. That "glaring" quality will provoke
the sense of astonishing beauty that we feel from good haiku.

I am finding there is a difference between merely "short poems" and
"haiku". If we define haiku as provoking that startling element of
sudden understanding, like standing in a room and realizing of a sudden
that no one is male. I think this is the reason why Zen loves it, in
fact since koan and zazen are aimed at the same experience. Good haiku
is a good /experience/.

Not all of the following poems count in those terms; some just strive
for a whiff of feeling.

* Various haiku
:PROPERTIES:
:CUSTOM_ID: various-haiku
:END:
#+BEGIN_EXAMPLE
Gossamer skirts
that trail in the breeze...
attendant ghosts.

A giant dipped his hand in the sun,
leaving a white thumbprint
between the stars.

A silver fish leaps;
a grey cat watches...
and nothing more.
#+END_EXAMPLE

* The town of Sitges
:PROPERTIES:
:CUSTOM_ID: the-town-of-sitges
:END:
In the quiet moments, the buildings of Sitges reach to the sky like so
many hands in prayer. They endure the peaceful calm, the soothing breeze
that wafts in from the south. If only this, it would remain a mute
testament to the nature of man, to prefer such contemplative vistas to
the raw utility of the interior.

Filling the space between are the thronging hordes, on weekends a stream
of humanity discharging to the sea and returning. They flow like
arterial blood, restoring the city's organism by pausing a moment in the
various shops and exchanging services for currency.

There is both an inward and an outward breathing: the salt air and the
travelers who come for it: a constant fluctuation despite the
unchanging, ancient character of the place itself. Among these flows are
various things to be seen: The rows of browning chickens in the
rotisería; fine pastries and cakes, of chocolate and raspberry and
vanilla; the many chairs and benches lining the outside of the
"restaurant bars", mostly filled with people smoking and watching the
passing crowd; gelaterías selling ice creams and sorbets; shops with
shoes, watches, clothing, bags, swimsuits and every other beach
accessory. Each article has its own shop, and each shop is the size of a
large living room, displaying in its own unique category of items.

The wares pass from rack to hand to bag, the swarms of the tourists
gathering their pollen like dutiful bees; in a moment of pause one can
almost distinguish the hum from the general background of the place
itself. And the shops, like variously colored flowers so attractive to
these flitting, buzzing figures, lay out their petals to the sun, and
gradually close as twilight brings on dark.

Today I cast about on the flow, a tiny raft braving the rapids. Down the
Carrer ed las Parelladas, down, down, until Gumá, where a short turn
leads me into a mini-casino, El Prado. Here leagues of retired men --
los ancianos -- play cards, checkers, chess, dominoes. I ask for a
chessboard and set it up, leaving the chair opposite conspicuously open
for a challenger.

Soon a young man sits down, by coincidence also named John -- Juan --
and also a student of Philosophy at his University. We take turns
pushing plastic armies at each other, with an occasional nod of the head
to signal appreciation.

This Juan is in his early twenties, studying Hüsserl, a precursor to the
philosopher of my own current study, Sartre. So we share a knowledge of
the difficulties of existentialism -- a bit of anguish to lend flavor to
the contest.

Juan's superior skill wins out, time and again, while I start losing
touch with the Quality of the game. As I do, I stop caring, faltering in
the responsibility even to lose well. A sloppiness ensues that makes it
hardly worth continuing. I only notice this parallel to the idea of
Quality afterwards. Now I am ready to return tomorrow, and to lose well.

Meanwhile, the characters of /Atlas Shrugged/ have been my only
English-speaking companions. The prose is so well done that at times I
have to close the book after each sentence, savoring it. That she is
writing about Quality is obvious: the first few pages are pictorial
references to nothing but. The theme seems to be, "What kind of world
would be left if ruled by those who care only about themselves, and not
about what they do or how well they do it?"

The sun overhead looks on all this with a dry amusement, its beaming
regard for humanity unchanging. For me, a pocket of shade at my favorite
cross-street, with seven tall trees standing proud and receiving the sun
with open arms.

To describe all this and fail to mention the water would be
unacceptable. Out there, where no clouds intrude today, there is nothing
to see but the purest blue. The whole earth is like a giant sapphire
with this little town suspended in the middle. Blue above, below,
reaching out to hug the limits of the horizon together. There is a calm,
steady blue, and a dark, undulating blue; the blue of hidden depths and
of revealed expanse. It makes the white of the buildings seem harsh and
intruding.

As if starved for this one color, chromatic lord of the seaside realm,
crowds flock to the sandy borders alongside and stretch out in mute
admiration, pilgrims to a temple grander and more ancient than hands
will ever build.

And beyond the legs and hands and backs and chests, beyond the fading
lines of foam constantly absorbed into the sand, and beyond the swimmers
splashing like clumsy fish, one can see the stately, tall gentlemen of
the sea, pacing east and west in crisp attention, the sails of their
uniforms starched and pressed, and puffed with pride in the afternoon
breeze.

This is the tableau of Sitges on a Saturday like most, while the
roasting chickens turn on their poles, and the birds above twirl like
drunken dervishes without care or purpose, and people amble below in
slow imitation of the same.

* More haiku
:PROPERTIES:
:CUSTOM_ID: more-haiku
:END:
#+BEGIN_EXAMPLE
The birds in lazy, looping circles.
The clouds have gone.
Not a sound.

The wet sand remembers
where my feet go,
but easily forgets.

Inhale the salt air...
one of those times
you taste with your nose.

Beneath the pale of mid-day,
birds are weaving
but forget their thread.

The night, the moon lonely;
a still, reflective silence,
the waves murmuring below.

Trees upthrust from the soil
reach for the sun
and do not look back.

A conference among the clouds,
the flash of argument;
tears of reconciliation.

Blurred images of speed,
plummeting, racing --
a small, quiet splash.
#+END_EXAMPLE

[[file:sea.and.her.secrets]]

* Rand's ideas of Quality and humility
:PROPERTIES:
:CUSTOM_ID: rands-ideas-of-quality-and-humility
:END:
Rand's idea (in /Atlas Shrugged/) is that life should be lived with
quality, and not coddled to compensate for any deficiency of will to do
so. Such tends to perpetuate a world of grown-up children, who, rather
than acting to realize their dreams, inveigh against the inadequacy of
life to realize them on their behalf. Rand gives us a definition of
maturity: to act, rather than hope and wait to be acted upon. She wants
people to wake up to who they are, and understand that dignity lies
entirely in how we face life. Live life for its Quality, and accept no
substitutes or platitudes in place of reality.

She also points out the false meaning of "humility" in popular culture.
It has come to imply: not making others feel badly for not achieving
excellence. The bright lights must hide, lest they blind others in the
dark.

The real meaning of humility is that light is the same no matter which
lamp it shines from. Greatness is universally available -- can assume a
myriad specific forms; there is no cause for one person to believe
themselves uniquely deserving of it, or special. If they shine, it is
because they have chosen to shine. If others do not, that is also their
choice. That is, the matter of shining relates to will, not privilege.
Humility is to recognize this fact; that the light from one lamp is the
same as the light from another. And so, being humble has nothing to do
with restraining one's self out of respect for the timidity of others,
while it has everything to do with realizing that they are equally
capable of shining -- whether they chose to exercise that birthright or
not.

From this, Rand also opposes systems of charity that encourage an
unwillingness to direct our lives. As children we start life entirely
dependent, crying when we need or want something. As older children we
still cry, but as we start finding this to be disgraceful, we modify it
to a whine. When even whining it too undignified, it becomes complaint:
the idle expression of a wish for life to do as we please.

Throughout these stages it is the same impulse, though it continues to
change form while we elude the obvious lack of dignity in doing so. The
form changes, but not the intent.

Real maturation is not about becoming a more clever or subtle whiner,
but stopping the behavior entirely: Ceasing to regard life as something
which must conform to our wishes, and instead acting to bring about our
desires.

Life is like an easel with many different paints. As a child we
complained when we did not like the picture; as an adult we should take
up the brush and make real the exalted visions of our heart. Then the
real beauty of which humanity is capable will become manifest. This is
the kind of activity that reveals Quality. Otherwise, we are like lost
souls wondering why we have such a great capacity to feel.

* Shunning mercy
:PROPERTIES:
:CUSTOM_ID: shunning-mercy
:END:
I do not want hand-outs, mercy, or free answers to the hard questions. I
was born with resources to test how I will use them, not to escape the
responsibilities of such a gift. Having has nothing to do with it. How I
face life must be done by myself alone. If I suggest that others live in
my stead, or compensate for my choices, where is learning, or nobility,
or the reason for being here in the first place?

[[file:call.of.life]]

* Those who blaze
:PROPERTIES:
:CUSTOM_ID: those-who-blaze
:END:
There must be, somewhere, people who feel the brightness of each passing
moment as if a spark of irrepressible joy were blazing in their gut.
Then they cannot but jump, or smile, or laugh, or write simple
paragraphs about such a feeling.

* Leaving Sitges
:PROPERTIES:
:CUSTOM_ID: leaving-sitges
:END:
There is not much more to write about Sitges, but for more poems about
sand and sun. I have met some of the people here; in essence like people
everywhere, though in form with a character all their own.

After these three weeks have ended here I've decided to proceed directly
to Florence, in order to spend more time in that city. And this weekend
I'll get a chance to see another town outside of Barcelona, since my
friend Ares has invited me to stay a night with her family and see the
beach, and learn to drive a motorcycle, and visit the foothills of the
mountains around the city.

* Real spirituality
:PROPERTIES:
:CUSTOM_ID: real-spirituality
:END:
There can be no real spirituality if based on removing the option to
choose otherwise.
