:PROPERTIES:
:ID:       09BFD725-4E41-4BCF-96FC-0C3E55B77514
:SLUG:     about-ego
:END:
#+filetags: :journal:
#+title: About ego

I have thought a lot about ego, because it is, I believe, a trap. Not a
trap that we become too full of ego, but a trap in which we avoid
striving.

Notice how little the Writings use the word ego. I believe it is
referenced a few times. It first came into use during Bahá'u'lláh's
time, so I believe it could have been used then if He'd wished.

Also, I am seeing a very distinct difference between just you, and you
as a member of humanity. In the case of the former, your success
distances you from the rest, you are seen as above, and them as below.
In the latter, your success is my success, since it is an human
achievement, and I too share that humanity. If you can succeed, it means
I can succeed, even if my avenue of success is different.

When you look at yourself in the role of a human being -- which is
really a supremely noble distinction -- then in fact you are everyone,
and they are you. When I look at a tall, proud building, I know think to
myself, "I made that." When I look at the moon, I tell it, "I could
reach you if I wished, and change you into any shape of my imagination."
Perhaps it won't be me -- John -- who does all this, but it will be Me
-- a human being -- who can and will if he desires it.

In this sense, Ego is impossible, because Ego implies something that can
only apply to you, and which I can never share in.

Today I was in a museum in the mountains of Cataluña, looking at some
wonderful Spanish paintings of the 19th century. As I realized that I
was looking at my own work -- at the work of us all -- I saw them as a
tribute, a thing to be worshiped. I could only thank the author, and
want to likewise fulfill the possibilities of human creativity. The more
we become, the more we all become. As if there is only one Actor, and we
are each a prop in His play. In this sense, all of the pronouns become
equal: If I succeed, you do, we do, He does, they (the rest of the
world) does. In all of creation, there is only one true Being, and we
participate in that being when we arise to excellence.

In fact, the painter in making that thing of beauty is encouraging me,
whispering to me, "Do you see what We can do?" He is urging me,
imploring me to outdo him, to continue the awakening to greatness of the
potential implied in human creation.

So when people praise your singing, they are praising themselves too.
They are saying, "My, what we can do when we choose to act." And since
it is an act you've given them, and not a description -- since it
radiates in the moment of the real -- they cannot but want to follow
suit; to stop talking and start doing. After that precious moment in
when the myriad excuses and complaints set in, the poisonous ideas of
ego and humility, which are a defense against the awesome, raw power of
potential. It frightens because it changes, it sweeps aside; people in
the presence of your singing cannot control it, they must be
transported! And this loss of control simply frightens all those who
have chosen not to be in full, complete control of their own destiny.
All the words, the wordy explanations, the cliches -- are attempts to
restrain the Spirit until those moments when its effect can be measured
and contained, and used to the lesser purposes of those whose goal is
not Quality, but lack of motion.
