:PROPERTIES:
:ID:       6D3ADD99-FB32-4EBC-B6F5-3575609D5CE1
:SLUG:     tales-of-cataluna
:END:
#+filetags: :journal:
#+title: Tales of Cataluña

Cataluña is the name of the district, or state, in northern Andalucia,
in the eastern part of Spain. If you have not looked at a map, I am less
than 200 km from the French border. Northwest of me is Madrid, where the
center of government is located, and above there the Pyrennes and the
Basque country. To the southwest, Andalucia continues down to Galicia.
This region is where the Muslims conquered for 700 years before the
Spanish where able to regain their country.

Catalán is the regional language, and is closer to Latin than Castellano
(their name for what we call Spanish), because Castellano contains many
Arabic-derived words. Catalan sounds like a mixture of French and
Italian, and is quite close to Castellano when you see it written. It is
also more expressive and more nasal, which add to its Italian feel.

This past week has been more exciting, in terms of activity. I met with
Kata's father, Toni, in Barcelona on Wednesday for dinner. He pointed
out for me many of the interesting things to see in the city. On Friday,
an old manager of mine from Borland happened to be in the city on
vacation, so I went to lunch with him and his girlfriend.

Friday night I left for Malgrat ed Mar, which is about an hour's train
ride northeast of Barcelona along the coast. This is the town where
Kata's cousin, Ares, lives with her family. Ares and her boyfriend,
Juanma (for "Juan Manuel"), are lovely. Her whole family is. They took
me in for the weekend, and treated me to Catalan specialties, and I had
a wonderful time.

Among the interesting things that happened: I got to try pizza with
caviar on it. Quite good. Then on Saturday, Ares' father, Manel, took us
out fishing on his four-meter boat. That was pleasant, and I got to swim
in the sea and dive in a very clear bay, but after swimming I felt weak
and became very seasick. I tried to hold out, to see if it would get
better, but it did not. Finally I asked to return, and slept in the
shade of a boat's hull on the sand.

Afterwards we had two kinds of Paella -- a rice dish cooked with mixed
seafood -- a specialty of the area that they serve everywhere. One was
the typical yellow, the other black. They were both quite good.

Then a nap, a few games of chess with her brother -- also named Manel --
and then Ares took me with her friends to go dancing at the discotech.
In America we would call it "bar hopping", since it consists of moving
from bar to bar, visiting different friends. Juanma knows about everyone
in Malgrat, it seems. He is very friendly! After a few bars, we stopped
at La Tropicana, and danced there until 3am. People who know me know
that I do not dance; well, things have been changing within me and now I
do. It is fun!

Exhausted, we returned home and slept until noon, thereafter to visit
the pool and lounge around in the sun. It has become very hot here, more
than usual. It should not be this hot until August, I am told. Combined
with the high humidity, it feels much hotter than Tucson ever does to
me, except for the blistering days. It is hot enough that one cannot
sleep unless very tired.

#+BEGIN_EXAMPLE
The heat! like a blanket
I simply can't remove.
I stick to the bed.
#+END_EXAMPLE

We returned from the pool to eat some home-cooked Catalan food prepared
by Ares's father: Pollo a'last (roasted chicken) and gazpacho (a cold
soup made from vegetable pureé). Add to these orxata ed xufla, and you
have some of my new favorite foods in the world! gazpacho is heavenly,
especially during these hot days. And the version Manel made was spicy,
which added extra kick.

The plan afterwards was for Ares to teach me how to drive a motorcycle,
first on a scooter without gears, then on Manel's Honda. However, we got
into a few rounds of the game Rummikub, and Ares fell asleep on the
couch, so it was not to be. I will have to learn when I get back to
Tucson.

At the end of all this they dropped me off at the train station and we
said our goodbyes. Getting to see them was one of the high points of my
time in Spain. The whole family has such character. Manel is a joker
with the most dead-pan face you've ever seen. They spoke mostly with
each other in Catalan -- which I could not follow -- but when I was
around they usually switched to Castellano. Only Ares could speak enough
English to make it worth the trouble, when Spanish wouldn't cut it.

* Visit to Montserrat
:PROPERTIES:
:CUSTOM_ID: visit-to-montserrat
:END:
This Tuesday I went to the monastery at Montserrat, located in a unique
cluster of mountains. People refer to it as the "symbol of Cataluña",
and it is quite famous. Napoleon destroyed it completely in 1810, but
afterwards they rebuilt the entire place. There I saw a museum of 19th
century Spanish paintings that held me in rapture, and heard a boy's
choir in the cathedral that was also beautiful. To see so much Quality,
the fruits of human creation, was well worth the trip.

After Montserrat the bus took us to a vineyard, where we saw the stages
of wine making. It was almost a cathedral of its own, except this one
dedicated to productivity rather than heavenly ideas. Seeing all the
massive tanks, and the two kilometers of caverns used to hold the oak
barrels, seemed worthy of worship itself, knowing that hands like my own
had made it all. The end product I may not appreciate as some do, but
the process of production made the wherehouse filled with bottles seem
like another kind of museum.

* Taking a boat to Italy
:PROPERTIES:
:CUSTOM_ID: taking-a-boat-to-italy
:END:
With the rest of this week I will go to Villanova, a quiet town to the
southwest, larger than Sitges though similar; and later to Barcelona to
see some of the constructions of Gaudí, the famous Catalan architect.
This upcoming Monday is the festival of Sant Joan (pronounced in Spanish
"San Juan"), when there will be fireworks displays in all of the towns.
On Tuesday I leave for Italy.

Most know that I did not have any plans made after arriving in
Barcelona. Originally I had thought to take the train from Spain to
Italy, since it seemed a nicer way to travel than jumping over by
airplane. Well, I was talking with Toni, and he mentioned that there is
a boat that goes directly from Barcelona to Genoa, Italy. I thought, Of
course!! How can I not go there on a cruise-liner?? It is big enough
that it should not make me ill, though even if it does, who cares? It
was too romantic an idea to pass up. When I bought the ticket, I learned
that it is also the cheapest way to get to Italy, costing only about $80
one-way.

That is all for now. My last job is trying to convince me to accept a
contract for three weeks, working in Prague. I think it will depend on
how much it would defray the cost of the vacation, since I would like to
see Prague. But it will be hard to pry me from the pastel hands of
Florence...

Now a few poems, although writing has been less during all of this
activity:

[[file:mood.of.night]]

This next poem is my first in Spanish, written in admiration of the
owner of La Granja Elsa, whose green eyes are both a joy and a torment.
It would not translate very well, though.

[[file:la.granja.elsa]]

[[file:the.waves]]

[[file:pain]]
