:PROPERTIES:
:ID:       1D8531CC-4358-46C7-9972-0BA078582034
:SLUG:     definitions-and-the-thing-defined
:END:
#+filetags: :journal:
#+title: Definitions and the-thing-defined

The following selection is from pages 221-2 of /Zen/:

#+BEGIN_QUOTE
He'd been speculating about the relationship of Quality to mind and
matter and had identified Quality as the parent of mind and matter, that
event which gives birth to mind and matter. This Copernican inversion of
the relationship of Quality to the objective world could sound
mysterious if not carefully explained, but he didn't mean it to be
mysterious. He simply meant that at the cutting edge of time, before an
object can be distinguished, there must be a kind of non-intellectual
awareness, which he called awareness of Quality. You can't be aware that
you've seen a tree until /after/ you've seen the tree, and between the
instant of vision and instant of awareness there must be a time lag. We
sometimes think of that time lag as unimportant. But there's no
justification for thinking that the time lag is unimportant -- none
/whatsoever/.

The past exists only in our memories, the future only in our plans. The
present is our only reality. The tree that you are aware of
intellectually, because of that small time lag, is always in the past
and therefore is always unreal. /Any/ intellectually conceived object is
/always/ in the past and therefore /unreal/. Reality is always the
moment of vision /before/ the intellectualization takes place. /There is
no other reality/. This pre-intellectual reality is what Phaedrus felt
he had properly identified as Quality. Since all intellectually
identifiable things must emerge /from/ this pre-intellectual reality,
Quality is the /parent/, the /source/ of all subjects and objects.

He felt that intellectuals usually have the greatest trouble seeing this
Quality, precisely because they are so swift and absolute about snapping
everything into intellectual form. The ones who have the easiest time
seeing this Quality are small children, uneducated people and culturally
"deprived" people. These have the least predisposition toward
intellectuality from cultural sources and have the least formal training
to instill it further into them....

#+END_QUOTE

One thing I think this is saying is that we can lose sight of the
world's beauty -- of Quality -- by gradually preferring the certainty of
definition to the certainty of our experience of the thing defined. I
think it's hard for this to happen in one lifetime -- to have such an
experience and then fall in love with the description instead -- but it
is easy if we have not yet had that experience.

This is when the knowledge of a thing blocks our ability to recognize
the thing. For example, if we idolize a great person by our knowledge of
them, we are almost certain to be disappointed by the reality. This is
not because the reality is lesser -- after all, the person himself is
the origin of that greatness and capable of more -- but because our
definition has rendered us incapable of seeing his value if he doesn't
take the form we expect: we can no longer directly perceive the
reality-before-the-description.

Or a foreigner experiencing a food he's never tasted. For him there is
only the experience. He will value it and always associate that value
with the thing itself. But for the resident it was new too long ago; he
now "knows" it too well. He may have completely lost the ability to
appreciate it.

The mind that does not yet know is aptly called by Zen "the beginner's
mind". Such a mind has to interface with life directly because it
possesses no knowledge that may interpose between.

There is nothing to discounted about knowledge, however. The first thing
God asked Adam to do was to name the thing of the world. He even went
one better: He named God Himself. Knowledge is a source of joy, so this
is not where our problem lies; rejecting knowledge will not offer any
solution.

The fault is solely in preferring the description of a thing to its
reality. It is accepting a substitute for the experience, and a
personal, immediate valuation of it. It is the difference between loving
the opera, and liking the opera because other people say how great it is
-- while feeling empty in your heart because you don't really like it at
all. The philosopher Krishnamurti spends a great deal of his time
talking about this distinction.

It is the hardest for religions, I feel. In Sunday school, as a child, I
was taught all about Christ. I was given all the definitions available;
but as Christ Himself is a rather inimitable figure, there was no way to
present me with an immediate experience of the reality behind what was
being taught. Christ faced this Himself with the Rabbis of his time --
likewise educated in all the definitions of Judaism and its prophecies
-- who failed to recognize that the living, undefinable spirit of those
prophecies was coming to fruition. They knew only the definitions, and
the reality was much too different from their expectations. Now it has
been so long that schools of definition combat other schools, with the
Ones who started all of the schools not even present in the debate.

Children are especially immune to all of this because they lack
knowledge, definitions. They also don't have much to contribute to
society as a result. But at least they know how to enjoy life and to
understand their own likes and dislikes. Without knowledge, of course,
the depth of their appreciation is severely limited -- but it is
genuine. To have both would be heavenly bliss. "Except ye be as little
children, ye shall never enter the Kingdom of God."

What can a person do? It is almost impossible, if not disastrous, to
erase knowledge. Perhaps we must simply seek anew what it is that has
given birth to all of our descriptions. To find love instead of
theorizing about love. "The death of self is needed here, not rhetoric."
We need to get into our car and drive it to the far horizon -- and put
away for a moment the travel books that have been written for us.

This is the mystic's search -- where a mystic is one who desires this
intimate awareness of his Beloved. The "mystics" who try to destroy
knowledge are like negatives contrasted with the positive; they have
corrupted the meaning of the word. The real mystic only wants to find
that Source of life of whom all knowledge is the sign and proof. At that
point, after the seeker ends his search and is consumed by love for his
Object, the lover becomes a knower, because he now knows why the
definitions of the world have the form that they do.

To seek is simple, if difficult. It involves only purifying the heart
and freeing it from all external influences. The soul of man is like a
compass always pointing north; but the cap must be removed and the
needle read. Each person is his own guide by this measure of the heart,
but he must release himself from his definitions to an incomparable
extent. Perhaps it requires an element of grace even to be possible. But
once found, this compass is seen to point the way, straight and true,
independent of every other consideration. "He will inhale the fragrance
of that City from a distance of a thousand furlongs..."

Once found, there are other difficulties to master and go beyond, but
these concern other issues beyond the relation of the description and
the described. All of them lead to joy, however, as the soul awakens and
undertakes its greatest pilgrimage.
