:PROPERTIES:
:ID:       CF60ED62-03AE-4C2F-8613-C9EC40782CF5
:SLUG:     a-poem-and-three-short-essays-from-florence
:END:
---
title: A poem and three short essays from Florence
tags: journal
---

Seeing people walk through the Uffizi:

[[file:rivers.of.people]]

* Commentary on /The Seven Valleys/
:PROPERTIES:
:CUSTOM_ID: commentary-on-the-seven-valleys
:END:
A commentary on /The Seven Valleys/ -- a Bahá'í mystical text -- based
on some of the ideas of /The Fountainhead/:

We search for Quality, for the living goodness which is the life of all
things great and beautiful. To find it we must be free of the judgments
and ideas of the world. When we stand thus, unashamed of our desire and
knowing our being's right and capacity to name it, then in proportion to
our effort we will find it: The good, the right, that which answers
"Yes" to the question of our being.

When we discover this quality, we must love it; it is the water of our
thirst, that alone whose sight justifies seeing. Then we will see how
much the world dishonors it, hates it, makes a mockery of it exactly for
its beauty. They do not know. Those who fear it as the destruction of
their idea of beauty, teach others to fight and destroy it. The more we
see this perfection in the hands of those who worship imperfection, the
more we want to rescue it from such hands, to save it from unworthy
eyes. We would rather destroy it then let the profane mangle it by their
words. This is pain, and the greater our love, the greater our agony.

This love would destroy us -- in a world that seems to honor lowliness
and forever sees greatness as apart from men -- until we learn the
nature of the good, and know its true sovereignty. The calumnies of its
enemies are like praise: they show how much they fear it and know its
power; their profanity honors it in the eyes of those who know: by
making obvious the contrast. The water they would pour to extinguish it
is changed to oil; the prison they would keep it in only banks the
flames and intensifies the illumination. It is unstoppable, and both its
friends and its enemies serve its cause.

Then we see that this good is everywhere, underlying everything. Nothing
can remain in existence without it. It is the life and potency of every
action -- even those directed against it. And it is all one, this basis.
It is one light, in the diversity of all its possible colors reflecting
from every created thing. It is one spirit and existence is the body
clothing that spirit. The world is a lamp, kindled to reveal its light.
A man's glory is not in his distinction from his fellows, but in his
revelation of this glorious good that shines through him more
completely, more perfectly, than anywhere else.

Now being seeks nothing more, for in its own being is true being: the
good, the beauty it had hoped and longed for. It sees that it itself is
the purpose for its own being, and that its self is the self of a
perfection beyond words. He reads, "Forget all save Me and commune with
My spirit," and finds the answer in his own being's purpose, echoing
Rumi: "The beauty of my own emptiness filled me until dawn." The single
man starts to fade away, and in his place dawns Man -- its meaning, hope
and goal. He sees himself as both king and servant in the same instant;
he is the seat of his Master, and the hand that answers to His will. He
is complete.

A being so at one with its object, so intimate in its relation to the
good, can see and appreciate its diverse forms with neither fear nor
longing. Its forms are limitless, its beauty beyond any mortal capacity
to bear. No limited thing can contain it, while no limitation can exist
without reference to it. It surpasses the highest understanding, the
deepest appreciation. The individual is torn apart in his desire to
embrace and honor it, but it leaves him panting and disappointed. The
good does not need him, but he cannot live without the good. He feels
himself destroyed and uplifted by its greatness at every moment.

Until at last the shroud of limitation is put off, and the drop merges
with the sea. This is not the death of the body and life hereafter, but
the death of the effort to contain, and the life of being contained, at
one. Now the drop and the ocean cannot be distinguished, nor can you
separate one ray from the brilliance of the sun. Such a being may live a
physical life, but he is no longer apart from the good, seeing it from
outside -- as the lover looks on with rapture at his beloved -- he is
become the good; its name is his name; there is no longer either
division or conflict. Look for him, himself, and you cannot find him;
but at the same time he is everywhere, taking part in everything. His
being is the same as the first of mankind and of its last. When a being
who strives for greatness looks him in the eye, he sees himself. For the
lantern is now lit in its full splendor, and its being is the light it
reveals; the iron of the cage around it is all but forgotten next to the
purpose of the lamp.

* Psychological implications of /The Fountainhead/
:PROPERTIES:
:CUSTOM_ID: psychological-implications-of-the-fountainhead
:END:
The ego that seeks the admiration of others represents the feeling of
ourselves as despicable and a desire to escape any knowledge of that
feeling. It is what we feel poignantly whenever we sit still and are
apart from others long enough.

Self-destructive behaviors are a desire to end this feeling, since the
ego cannot eliminate the fact that we despise ourselves. And since we
can only despise something we know to be honorable and good, as fallen
from its possible glory, it is our respect for ourselves we want to ruin
in order no longer to feel that we have a right to despise ourselves. We
hate because we love, and this love is tearing us in two because there
is something very wrong we are not facing.

The answer is not found in salvation, or sacrifice, or suicide -- or in
dedicating one's life to serving others because one feels unworthy to be
served. The answer is plain, simple knowledge. Find out why you despise
yourself, and you will know what to do to end it.

Every soul can find the answer to its problems. There are more solutions
than problems in the world, because the mind is active, living,
limitless; while problems stand alone, fixed, unmoving. A mind faced
with a problem can name a thousand avenues of approach -- while there
always remains only one thing that is being approached.

To claim a problem cannot be solved is a wish that someone else will
come and solve it. This is the same ego, wanting the world to live up to
its hopes and defend it from the existence of the problem. Where there
is knowledge and a will to know, however, the solution will be evident.

It is obvious that we do not like ourselves. Go anywhere and listen to
people talk about their spouse, their boss, their job, their government,
their country, their world. They are living in a place they do not like,
and somewhere inside them they realize that the form of that world is
only the contributions of those who live in it -- including them.
Everyone will tell you eagerly how much others have screwed up the
world. This is the alternate side of the ego: it works positively to
attract praise, and negatively to divert blame. We know the world is the
sum of its individuals, and that governments exist by consent of their
citizens; but only a few will admit, "I help to create and maintain a
world I despise."

For example, we are compassionate people who eat meat, knowing the
animals are not respected and cared for -- or trying not to know. Others
want to end the moral conflict by withdrawing, living in their own
gardens, naked and without convenience if possible to escape the
sickness of our global condition. How can this be the answer, to regress
all the hard-won efforts of civilization? Avoiding meat does not answer
the slavery, misery, and poverty sustaining the lives of those with
luxury and time to consider these problems.

How can we admire the world we see now? Id even one person willing to
state honestly that the world he sees matches his image of beauty and
perfection? We grow up in this turmoil, the mass confusion of a world
repulsed by itself; we make compromises with it, losing ours ideals one
by one to age and experience; we cut out a safe little corner listen to
others tell us that no one can change it all, that one person is
powerless against so much corruption, that if he lifts his head above
the crowd in pride, it will and should be cut off.

But we cannot so easily fool ourselves. We are honest, noble creatures,
every one of us. This is what makes depravity depraved: that one fallen
low should have been high. We are the custodians and authors of our
world; like any creation, it reflects our values and our commitment to
those values. We look at the world and must turn away: we must not know
what we have allowed it to become and remain. It is a mirror whose image
is too painful to contemplate.

In response to this, in honest assessment of what we are and are a part
of, we discover a horror too awful to admit. Numberless bromides,
reasons, excuses are thrown up to block out that knowledge. Because we
love ourselves, we cannot look at ourselves; because we love the world,
we must give up on the world. This is why the ego exists and why we
continue to do things to destroy our self-respect: If our respect for
our self became too great, we would have to answer for the state of the
world.

Why? Is one person so important he should consider himself responsible,
by sin of omission, for the entire world? It is exactly because one
person could change all of it, but runs from this knowledge, that he
also runs from himself.

The form of change cannot always be foreseen; it may set in motion
events that play out over centuries. But all such changes begin with the
certainty, not only that it can be done, but it is the nature of man's
being alone to do so. There is nothing in existence which does not bow,
in the end, to his creativity, his ingenuity, his persistence and
integrity, and his resource for co-operative endeavor. The universe
itself, in time, will become a means for realizing our vision, as has
the sea, the air, the mountains. Look at man's physical form --
beautiful yet powerless before nature's beasts -- then go to a zoo and
know who you are.

Only a man who bows before a problem cannot solve it; only the one who
regards the world's troubles with awe and fear cannot overcome them. Our
race, as it stands now, began with a handful of individuals a long time
ago, when the whole earth was a garden of dangers. Visit New York City
sometime, and see the changes their kind have wrought upon the world.

Most religions and spiritualists seek an end to the problem of ego in
humiliation, in completely devaluing one's self. This cannot, however,
but worsen the essential problem which causes men to look to others for
a sense of value. It is only by exaltation and discovering one's true
value -- and the consequent self-respect this must engender -- that the
cause of ego is undone, and man can face himself in the mirror of the
world again.

Let us acquire this knowledge of our nature and of our power, and set
out in life to do what will answer to our basic love of that life. The
crucial factor is self-knowledge, and discovery of that certitude which
moves not only mountains, but all the affairs of men if it has a mind
to. The ego will ask, "How? Am I doing it right?", but know who you are
and you will go out and do it -- whatever the form of your longing as
part-owner of the world. The solutions will present themselves like able
servants who had been standing, waiting, ready all along.

* Guidelines for Writing
:PROPERTIES:
:CUSTOM_ID: guidelines-for-writing
:END:
A projection of the character of Howard Roark into a set of guidelines
for writing:

Write what you want to read. If you were stranded on an island with only
your own work, how would feel about it? This is the goal to aim for:
that it's only your own work you would want to take with you.

In the beginning this means acquiring skills: grammar, vocabulary,
techniques of imagery, use of punctuation. It also means practice,
experimentation, effort -- as with any activity whose end involves a
performance of some kind.

As you develop, you will like what you write more and more. Writing will
become a joy in itself, an experience of your own creative power. Your
respect for your work will increase, and beyond one point it will seem
precious to you, too sacred for profane eyes. What you write will become
like love letters to your own soul, and you will treat them as such;
until the only reader worthy enough is your own self; when publishing
seems like a sacrifice of your finest pearls before the common eyes of
the public. As a lover guards his beloved's correspondence, reading them
again and again into the late night -- writing responses just because
and burning them to honor their sacred nature -- this is the writer's
highest experience of himself, his communion with the beauty of his own
soul.

What is conspicuously missing from this is the role of others. They have
no role. In the eyes of other people what you write may seem like
garbage. But you are not writing for an audience or for any other
purpose but to write. When an author has another purpose, he will start
looking for shortcuts to that end, ways around the necessity of writing.
But for the writer there is only writing; he must write; he needs to
write like he needs to eat and sleep, it is the food of his heart and
the breath of his spirit. Poverty as a writer is wealth to him, and
riches without, no life at all.

Perhaps, when the world offers its response to his words, you will find
him writing his future works on sand, or water, seated next to a
crackling fire that feeds on paper. He writes, not in reference to the
world, but to his own knowledge of whether that sublime quality he seeks
is present or not. His pen is a lighthouse, and his being, a barge on
troubled seas seeking land. What he writes is his gateway to heaven --
and he writes only to discover that door.

Such an act needs nor wants any explanation. It stands on its own,
complete in what it is. If people ask if you are a writer, hand them
what you've written, giving and expecting no words in return. Writing is
an act, not a title; it is the spirit, not the body. Everyone knows if a
body is dead or not in the first instant; a writer knows as surely
whether his work has anything to do with writing or not.

It may seem a lonely existence -- but how can it be? He has writing for
a companion! The very quality that makes for the truest, most satisfying
friendships, is the quality he summons by the movements of his pen or
the pounding of keys.

The harder part is not writing for yourself, but knowing what you truly
want apart from what others have told you to want. The two can seem
indistinguishable. If you like something, and never consider how much
someone else would like it -- if you haven't time for such thoughts in
the midst of your rapture -- this is a good sign.

If at the end there is no joy, if it does not make you feel the
happiness of a creative being creating, this is also good to know. Your
artform lies elsewhere. The first role of education should be to help
you find it; the second should be to give you the skill to explore it to
the utmost.

The function of the soul is to love, and it can only love the highest,
the greatest -- in everyone and everything. What you do in writing is to
exercise your capacity for that love and use your mind and faculties to
create what is deserving of such love. It is a matter of life and death
-- of the soul. This is what it means to live for the sake of your soul.
It is only by your deepest, your truest, your purest desire, that you
will learn the nature and quality of your soul's highest love: itself.
Writing is an act of conjuration; the recitation of it is a spell of the
highest power. And when you read another's work of this quality, you
will recognize yourself it. It is not a recognition of the self that
writes: but of the Self revealed by such writing.

This is why it is paramount to write only what you want to read. Forget
all else and commune with that spirit whose presence is the life of all
true effort. Then you will no longer need advice of any kind.
