:PROPERTIES:
:ID:       41A0BAC0-5E94-4501-B5B9-0FF9A6AF02BD
:SLUG:     a-cup-for-the-rain
:END:
#+filetags: :stories:
#+title: A Cup for the Rain

I don't remember how we came to be in that place, gathered beneath that
magnificent tree, its long branches touching the sky. All of us were
huddled together, though I don't know how. Nothing makes sense when I
think about it. But I do know we were dry, safe, and secure, wherever we
were -- and we were also thirsty.

Most of us did not recognize the desire as thirst. It was just a vague
burning that kept getting worse. Some tried everything to distract
themselves from it. We yearned and writhed, but no solace came. We spoke
to each other about it, but did not properly understood what it was. We
only knew that something was not as it should be, somehow. Peace eluded
us.

Outside the tree it was raining. Everyone could see that, could hear it.
What the rain meant, we did not know. Since very few had ever ventured
out from under the tree, we took it to be another of the unaccountable
details of life. Stories even built up about the rain and what it might
be. It was said to strip the flesh from a man's back, or to induce
insanity. Some who went into it never came back. Since we knew that the
tree offered safety and security, most of us remained there. We kept to
telling each other stories.

At some point a questionable character went off into the rain. He came
back claiming it was refreshing, and had relieved the parching thirst of
his tongue. He couldn't drink much, but he was obviously tantalized. He
tried to encourage some of us to follow him out, but we couldn't imagine
leaving the tree. I don't even remember what we did there, though I
recall not wanting to leave.

The adventurer did not give up, however. He went out again, for a long
while. When he came back, he held something that looked like a gourd. We
could also tell, from his eyes, that his thirst was gone. He had found
something we needed! Whatever could alleviate our terrible hunger was
worth considering. And thus, he told us a strange tale.

The rain, he claimed, was the very thing we needed. It surrounded us
always, pouring bounty from the clouds. However, as prodigious as it
was, catching it was not easy. Holding one's mouth to the sky gave a
little comfort, but not much. Then he told about the science of the cup,
and how it allowed one -- given patience -- to slowly gather the waters
into one place, from which they could be drunk. Even more, it permitted
the waters to be carried out of the rain: for example, under the tree.
This was how I first tasted what I had been longing for.

He held out the cup for each of us, but we only took a sip. There was
not enough for all, and certainly not enough to calm our thirst. If
anything, it made us feel worse, the burning more intense. He ran out
and back again several times, but the thirst was great and his vessel
small in comparison.

He told us we would each have to fashion a cup, and holding them to the
sky, walk out from under the tree. We would have to stand in the rain a
while, letting the waters fill our cup, and then we could drink, and
continue repeating until satisfied. If our thirst returned, we could do
the same thing to satisfy it again. The man had offered us a way out of
misery.

There were still many under the tree who refused to try, however, not
believing the water meant anything -- or calling it poison. We tried to
tell them, but they questioned the necessity of the cup. So crude and
awkward, after all, and the water so formless and transparent. It didn't
make sense how important they were, or the connection between the two.

So, these days I venture out from the tree of knowledge by myself, or
with a few others, and hold the cup of my religious discipline to the
sky, awaiting the bounty of heaven's grace to fill my cup. When I drink,
thirst is allayed and I see the reason for the thirst, the water, and
the cup to hold it. They all exist to bring us together, so that my soul
comes out from the tree, and looks up to contemplate the heavens always
above me. What strange creatures there; what amazing patterns in the
clouds...

This, I think, is the connection between the varying forms of religion,
and the ineffable, formless Mystery it conceals.
