:PROPERTIES:
:ID:       28C302FE-4002-4D28-9D86-63F85BC80459
:SLUG:     on-self-knowledge
:END:
---
title: On self-knowledge
tags: journal
---

What can we truly know about ourselves? Whatever I call myself depends
entirely on who's around me. Thus, I only seem anxious when others are
calm. Any term used to describe me can be confirmed or invalidated by
picking the right crowd to hang around. Is this knowledge? Or is it more
"appearance by context"?

If no externally descriptive attribute can be called knowledge --
because it is not stable, the opposite being equally true under
different circumstances -- I am left only with what refers to my heart.
For example, if I touch fire I feel pain. This is absolute, and I would
call the displeasure of such pain /in that moment/ a kind of
self-knowledge. The fire teaches me I didn't like putting my hand there.

My limitations are not really knowledge, since I am constantly learning
how to overcome them. I may feel I know my boundaries, but the flaw in
this "knowledge" is that it refers to future actions, while the future
partakes too much of the Unknown. Anything I may say about myself that
references the future instantly becomes unsure, and I cannot ever claim
it as self-knowledge.

Preference, however, has nothing to do with the future. It is of the
essence of vagary -- and yet is complete in its being. When something
pleases me, that moment becomes the fulfillment of all past time, in
that whatever has gone before led my soul to that condition of ecstasy.
What happens afterward is anyone's guess; and since only in the present
can ecstasy be known, it is only in the present that anything of my self
may be known. (I leave the understanding of "pleasure" to the reader,
since what pleases the soul must be discovered individually).

We can know what uplifts the heart because it has nothing to do with
what we do not know: that is, it can be known fully in the moment we
don't like something, even if a moment later we change our minds and
decide to like it. It's not the preference that we know, but the
experience of liking or disliking it in that moment.

Not only does this invalidate every name I might apply to myself, it
debars me from looking into the past, or projecting into the future, to
learn who I am. Even in the present I am too variable -- pleasure being
such a fleeting thing -- that it is not any particular state of being I
"know", but rather that very condition of being alive. I am not any
/thing/, but simply /am/. This would seem self-evident, if not for the
fact that I have also called other things knowledge.

If knowledge can only exist in the experience of being aware, what does
it mean to the task of striving to "know thyself"? The primacy of
awareness would imply that our present experience defines who we are.
Thus even if all the conditions of my life describe me as "content", I
am only content in so far as I /am/ content, without reference to
externals. To connect with [[file:feb2004#theego][an earlier entry]],
this implies that self-knowledge is of a wholly different order than the
definitions of self constituting the ego.

If nothing is true of myself until we experience it, it emphasizes the
importance of considering our present state of being. How many plans are
made for the sake of acquiring a name, and thus to "know who we are"?
But if I am only what I am in the moment that I am, it changes the
organizing principle of affairs to be what conduces to the experience of
self I most hold with. /My knowledge of self lies in the measure of my
awareness of being alive/; thus to waste precious hours in search of any
other kind of knowledge is to lose my chance at the only knowledge
available to me: that I am.

This reduces to a kind of pragmatism, in which my actions are measured
by and aimed at whatever will lead to an experience of the good. It
means there is no quality that adheres to things, perdurable and
constant, but only an ineffable Quality to life, the experience of which
is its marrow (see journal entries from [[file:summer2003][the summer of
2003]] on this theme).

If this is hedonism, let it be a spiritual hedonism, in that it is my
soul I aim to please. But how to pleasure my soul? I must place its
needs before all others to recognize what it attepmts to tell me through
the medium of experience. If I can know this, perhaps I will know who
and what I am; but if I do not know it, to what end should I direct my
life?

* Following our dreams
:PROPERTIES:
:CUSTOM_ID: following-our-dreams
:END:
On a somewhat related note, my friend [[http://mossayeb.org/][Sina
Mossayeb]] recalled me to an excellent article others might appreciate,
titled [[file:what.should.i.do][What Should I Do With My Life?]], by Po
Bronson. It addressed the question of how we choose what to do with our
lives, and the obstacles that sometimes hinder us from realizing our
dreams.
