:PROPERTIES:
:ID:       FF5AC4F3-2748-42D3-B733-D7CA29AE65BE
:SLUG:     athirst-in-loves-desert
:END:
#+filetags: :stories:
#+title: Athirst in Love's Desert

The rocks crumbling underfoot went unnoticed next to the burning sun
above. The air was dry, and quickly blew all moisture from Majnún's
skin, leaving a brief tingle as the evaporation cooled his arms. There
was hardly a cloud to see, and on the ground was only cactus and rough
bushes. Likely snakes and scorpions hid all around, but even they
avoided the heat of the day. Hiking the desert at midday takes a special
kind of madness -- or a very special reason.

The next hill remained forever distant from Majnún's laboring feet.
Dust, the color of calfskin, stretched in all directions, with only a
few sprays of green in the form of spiny plants. Even breathing took the
moisture from one's lungs, so Majnún drank constantly. His bottle of
water grew lighter with every step.

Somewhere in all this chaparral lived a fair maiden -- a princess of
great reknown. He trekked to find her, and to present his gift of love,
that she might favor him with a glance. It was said her gaze could heal
wounds, and the shape of her face granted wishes. Certainly the stories
he had heard in California promised nothing less. Could it be true? Had
he found one who would touch his heart and leave in its place a thing of
beauty and light? One foot following the other, he continued on his way
to find out.

Even her name was a mystery. A ravishing women from the East, named
after a famous /nom de plume/ of a century ago. They say that, in public
circles where many came to admire and capture her beauty, she used other
names and told other tales. This only heightened the mystery of that
precious being, who even now pulled at Majnún's heart like a magnet deep
in the Earth. Although the sun fell dim and blood red in the west, and
his bottle carried less than a trickle, he knew the time was drawing
near when he would find refreshment simply by her words, "I am here."

The creatures of the desert regarded the wanderer in silent amusement.
No fools for love, they. There is a wisdom in saving the heart, and
keeping one's focus on matters of food and shelter. But the lover who
catches a glimpse of his hope -- his beloved -- cares nothing for the
laws that govern ordinary lives. He goes from shelter to rain, from
surfeit to famine, just to hear her name one last time. He is a creature
foreign to the world of being. How well the Master relates:

#+BEGIN_QUOTE
Love accepteth no existence and wisheth no life: He seeth life in death,
and in shame seeketh glory.... Blessed the neck that is caught in His
noose, happy the head that falleth on the dust in the pathway of His
love.

#+END_QUOTE

And dust there was, everywhere; and Majnún with a longing to throw his
head -- his life blood! -- down upon it! to drain away his life in
remembrance of her; to prove, by becoming a stain upon the ground, his
undying devotion. To a lover, these are the marks of true living and the
heights of glory.

But first, to find her -- to tread this barren valley of Search on a
mare both intemperate and slow. For Majnún recognized that his own being
was the steed he rode, and so he willed each leg to chase the other down
dusty trails and up crumbling hills. Each step was an insult to his
thirst; every moment, a sliver of time pressing into his heart. But
since the Master counsels patience, he whispered to each leg, to each
cell, to hold back from their madness, until he could watch her smile
and feel the dawn of reunion breaking over the dark night of absence.

The awesome cactii, with dusty arms reaching for heaven, said nothing.
The rabbits here and there gave no comment. The first stars peeked in
the darkness, and twinkled, but remained shy. The brushing of scaly
bodies, and sinuous tracks through the dirt, was all that was heard from
the snakes. Only the coyote and his plaintive howl seemed to agree that
life without a sun is not enough. But while his sun had passed beyond
the hills, Majnún's had yet to rise in the East of recognition. Where
was she?

Searching high and low, under rocks and behind trees, he looked for her.
Everyone he passed, he questioned; every broken leaf he pondered for
signs of her passing. As the Master told:

#+BEGIN_QUOTE
In every face, he seeketh the beauty of the Friend; in every country he
looketh for the Beloved. He joineth every company, and seeketh
fellowship with every soul, that haply in some mind he may uncover the
secret of the Friend, or in some face he may behold the beauty of the
Loved One.

#+END_QUOTE

But he met so few on the trail, and of her there were only hints and
stories. He pursued them all, looking for whatever clue might lead to
her palace. In the end, he even fell down on the dust, and begin sifting
its grains, in case she had made the ground her home.

#+BEGIN_QUOTE
One must judge of search by the standard of the Majnun of Love. It is
related that one day they came upon Majnun sifting the dust, and his
tears flowing down. They said, "What doest thou?" He said, "I seek for
Layli." They cried, "Alas for thee! Layli is of pure spirit, and thou
seekest her in the dust!" He said, "I seek her everywhere; haply
somewhere I shall find her."

#+END_QUOTE

Where could she be? The hapless wanderer was out of food, out of water.
He lived now on the energy of his own tissues. He consumed himself like
a candle to give forth a weak flame in the night -- his only guide. And
like the candle, he wept hot tears streaking his face, and guttered
whenever biting winds rose from the north. Almost without hope he
struggled on, and lived for the one thought that perhaps she was near.
His state recalled the Master's tale:

#+BEGIN_QUOTE
From the rule of love, his heart was empty of patience, and his body
weary of his spirit; he reckoned life without her as a mockery, and time
consumed him away. How many a day he found no rest in longing for her;
how many a night the pain of her kept him from sleep; his body was worn
to a sigh, his heart's wound had turned him to a cry of sorrow.

#+END_QUOTE

When shall it end? Feet numbed from travel, a heart weighing like stone,
Majnún pushed ahead. Everything he'd brought fell to his side as he gave
up the final impediments. A trail of worthless belongings littered the
trail, marking his passage by tokens that offered no solace. Soon even
memories were swept away, knowledge -- the fragments of his very being.
Existence itself he sloughed off, to be replaced by the sole image of
his beloved.

#+BEGIN_QUOTE
Nor shall the seeker reach his goal unless he sacrifice all things. That
is, whatever he hath seen, and heard, and understood, all must he set at
naught, that he may enter the realm of the spirit, which is the City of
God.

#+END_QUOTE

How does one follow the track of a ghost? The weary one became invisible
to his own eyes, and so perhaps the story must end here. But he'd yet to
find the aim of his longing, and the strength of his yearning still
sparked the air and thrilled the atoms by its vibration. Everywhere he
went he brought life, which he gave freely because he himself sought
death. Or rather, he thirsted for the death of absence, to taste the
draught of reunion. "He had given a thousand lives for one taste of the
cup of her presence..."

A thing of pure spirit, he drifted over the desert sands. The animals
were still quiet; the bunnies flopped their ears, and paused to muse the
secrets of a blade of grass. What the snakes knew they kept to the
trails, and wrote only these lines in their gliding calligraphy:

#+BEGIN_EXAMPLE
Love's a stranger to earth and heaven too;
In him are lunacies seventy-and-two.
#+END_EXAMPLE

Some day, fate promises, the aching bellies will reach to the table of
bounty, and the parched tongues taste from the meads of delight; the
aching travelers will soak in the ocean of nearness, and besotted poets
drown their misery in the wine of union. But when shall these things be?

In answer to this, one must recall His words to mind, where He speaks of
the life of the soul, and the sweet death of the seeker who vanishes, to
enter the heaven of his Goal:

#+BEGIN_QUOTE
[Love] yieldeth no remedy but death, he walketh not save in the valley
of the shadow; yet sweeter than honey is his venom on the lover's lips,
and fairer his destruction in the seeker's eyes than a hundred thousand
lives....

For the head raised up in the love of God will certainly fall by the
sword, and the life that is kindled with longing will surely be
sacrificed, and the heart which remembereth the Loved One will surely
brim with blood. How well is it said:

#+END_QUOTE

#+BEGIN_EXAMPLE
  Live free of love, for its very peace is anguish;
  Its beginning is pain, its end is death.
#+END_EXAMPLE

#+BEGIN_QUOTE
Peace be upon him who followeth the Right Path!

#+END_QUOTE
