:PROPERTIES:
:ID:       068E766C-6C14-4687-8203-816482F466F8
:SLUG:     regard-your-enemy-as-your-friend
:END:
#+filetags: :essays:
#+title: "Regard your enemy as your friend..."

As nearly everyone has found, this principle cannot be applied brute
force. Enemies are enemies, and no tweaking of your eyes will see them
differently. It's like pain: there's no way around the fact that it
hurts.

However, as with pain, the context determines our underlying response.
People who train at a sport endure pain constantly -- by choice. If you
ask them, "Does practice hurt?", of course it does. But they willingly
submit, again and again, and in many cases look forward eagerly to the
next time they encounter this pain.

They do that because it's fun; because the pain is part of something
bigger that they love; and when love is involved, pain becomes
transmuted into something /that feels the same, but is perceived
differently/.

Back to enemies: They are a kind of pain that is part of the practice of
spiritual life. The soul must learn how to love in this world, so that
it may use that love to participate in the next world to the greatest
extent. Yet it is too natural to love our friends; that's automatic, and
even animals do it. Yet to love our enemies, that is special. Only
spirtual maturity can manifest love toward pain and hatred.

So we can't do it because the Writings say "we should". No one plays
sports and enjoys the pain of it "because they should". Spirituality
makes sense only if it's always about God, and not about the individual.
Thus, when one has fallen so deeply in love with the True One that he
yearns and prays for any and every access, suddenly pain is seen as a
doorway: since it is by pain that our spirit's faculties increase.

To see such pain, and our enemies, as propelling us toward our Goal,
makes us happy because through them we near that Goal ("...rejoice not,
save that thou art drawing near and returning unto Us.") And when this
knowledge fills our heart with joy, that joy overspills and makes us
thankful to the ones who had helped us the most to get there: our
enemies.

Then there is no one more helpful in our yearning for God than our
enemies; as Bahá'u'lláh wrote:

#+BEGIN_QUOTE
God is my witness! Had it not been in conflict with that which the
Tablets of God have decreed, I would have gladly kissed the hands of
whosoever attempted to shed my blood in the path of the Well-Beloved. I
would, moreover, have bestowed upon him a share of such worldly goods as
God had allowed me to possess, even though he who perpetrated this act
would have provoked the wrath of the Almighty, incurred His malediction,
and deserved to be tormented throughout the eternity of God, the
All-Possessing, the Equitable, the All-Wise.[fn:1]

#+END_QUOTE

The soul who does evil hurts himself, but he aids those who strive for
God. In the compilation /Crisis and Victory/, Bahá'u'lláh says: "Even if
all the losses of the world were to be sustained by one of the friends
of God, he would still profit thereby..." The concept of fire
transmuting base iron into a glowing, liquid heat, is a metaphor that
explains why the circumstances favorable to the iron will never allow it
to reveal its luminous potential. For that, trials, tribulations, pain
-- and even enemies -- are necessary.

For this reason I think we should love our enemies: because they are in
truth our spirit's best friends. I even wonder if, in the next world,
they will not occupy a very special place in our hearts -- because
whatever place we reach to there, in terms of our spiritual station,
will have been made possible largely through their influence.

[fn:1] Bahá'u'lláh, Gleanings, p.102
