:PROPERTIES:
:ID:       4404993C-508D-4A08-B9C7-D143F35E24B3
:SLUG:     the-steed-of-pain
:END:
#+filetags: :journal:
#+title: The steed of pain

In the mystical journeys of the Seven Valleys, a point occurs in the
valley of love where Bah치'u'll치h says, "The steed of this valley is
pain; and if there be no pain this journey will never end." I think pain
is a steed here because it offers proof to the lover: it is his foil,
his trial by fire. Until he experiences the transmutation of pain, he
has not passed the final test of love.

What I mean by a test of love is: If I met someone who claimed to be in
love with someone or something, I would ask a few questions:

- /Do you lose sleep thinking about him or her?/
- /Do you lose the desire for anything else?/
- /Are your thoughts only of him or her?/
- /Does time stop when she or he is near?/

And then the real question:

- /When you suffer pain for his or her sake, how does it feel?/

To the true lover, pain suffered for the beloved is sweeter than
pleasure. I look at programming, in my case. Programming is arduous,
requiring long hours of thought and debugging. This Friday I spent ten
hours tweaking a bit of code to run 20% faster. That's all; something
users will hardly notice. It took time pouring over tiny details,
debugging each problem that came up. It was exhausting -- it was
exhilarating. I looked at the movie times that night, but decided the
joy of coding was more attractive than sitting in a theater. The pain of
the effort was more appealing than the pleasure of being entertained.

This is a proof of love: how one experiences pain in the path of that
love. If bitter, one's love is not complete; if sweet, his love is true.
Thus, pain is the steed by which we know if we've found our love, the
barometer that measures the rarity of our devotion. Even the least hint
of bitterness should spur us on, telling us we have not found our goal.
Because when a person finds what they seek, all the world disappears...
He might walk through a valley of gold, but not know it was there.

The next time you meet someone with passion, ask about it. Listen to how
they describe it, what they say. What parts do they leave out? What do
they tell first? It may sound as if, by talking about it, they become
impatient to return. They will talk about the experience of it, the joy,
the /possibilities/. There are no limits, no stumbling blocks. The world
they describe can seem an infinite place of goodness and light.

Because I think, from reading the mystical literature and some other
experiences, that when we love God and life to this extent, pain no
longer finds a place in our hearts. Should it come close, it is
transmuted into something else, beyond pleasure and pain. Bah치'u'll치h
writes:

#+BEGIN_QUOTE
A lover feareth nothing and no harm can come nigh him: Thou seest him
chill in the fire and dry in the sea...

#+BEGIN_QUOTE
Love's a stranger to earth and heaven too; In him are lunacies
seventy-and-two.

#+END_QUOTE

[Love] hath bound a myriad victims in his fetters, wounded a myriad wise
men with his arrow. Know that every redness in the world is from his
anger, and every paleness in men's cheeks is from his poison. He
yieldeth no remedy but death, he walketh not save in the valley of the
shadow; yet sweeter than honey is his venom on the lover's lips, and
fairer his destruction in the seeker's eyes than a hundred thousand
lives.

#+END_QUOTE
