:PROPERTIES:
:ID:       0D6041A8-8080-4032-AC36-9D5DE645CAA4
:SLUG:     funeral
:END:
#+filetags: :stories:
#+title: Funeral

The stream of black coats entering the church seemed never to end.
Accompanying them were an equal number of black dresses and veils, all
crowding beneath the ancient stones of the Pennsylvania church. Once the
news had gone out about his death, it was difficult to keep up with the
phone calls asking for directions.

It was in Danville where we were, where his wife used to live. The town
was very small, and must have seemed flooded by black and mourning. Of
course our party was invisible to the outside world. The deaths of
unknown people are always just as unknown.

The church was the same that he had been married in. It was set off from
the road on a large property, quaint and simple beneath the sun. The
exterior was made up of large stones and brick, patterned in a fashion
very common among the older buildings of the East Coast.

The casket was being led through the front door when I arrived. The pall
bearers were sturdy men, the same age as he would have been, all from
the same fraternity of their college days. They carried both him and the
weight of realization on their backs. It appeared a very heavy load.

The casket was polished cherry-wood, very handsome under the cloudless
sky. As it disappeared into the doors of the church, swallowed up in the
maw of that great building, I said a prayer in my heart that everything
would go well that day, as a kind memory to his wife.

Others were coming, and we entered the building in slow procession. Now
we too were being swallowed up, consumed by the feelings and sentiments
surrounding the occasion. Anyone who enters the room of a funeral
somehow loses himself, and cannot feel anything except within certain,
accepted parameters: thoughtfulness, grief or despair.

Something similar happens at weddings. While rehearsing, everything
seems so ridiculous and funny, and people cannot help but laugh at the
absurdity of it all. But during the wedding, such emotions are
impossible, because they are curtailed by the decorous expectations of
the multitude.

I took my seat near the middle. In front of me were long-time friends
and family, serving as a barrier between the sacred memory of their
loved one and the rest of the world. Some were staring at places in the
church, others were talking, but most were silent. They were waiting for
what came next. We were all carried along by form, even those whose
grief was the most genuine.

Finally the event began, the solemn words and expressive tears. It was
plain that he was dearly missed. One speaker followed another, almost
every one coming from the front of the pews. Then one of them stood up
whom I remember quite clearly, since his words struck me as being
different in tone from the rest. Perhaps it would be best to describe it
exactly.

He walked to the podium with very audible footsteps, which contrasted
the almost fluid motion of his arms and legs. He seemed to float to the
center of the area where all eyes were focused, accompanied by the tiny
chatter of his footsteps.

He stood behind the stand, which was meant more as an emotional defense
than for any particular purpose. His feet were placed heavily, and it
seemed that his body sank into position.

Those of us in the audience felt time becoming painful. Each second
measured out slowly as his passed his eyes over us, taking in the sight
of those who had come to mourn his brother. I remember that the last
breath he let out, before he began to speak, seemed to consider all of
us, acknowledging our devotion in a way, agreeing with the tragedy of
the event. Then he spoke.

“I'm not sure what I should say to all of you. It touches me that you've
come. I only wish I could greet you under different circumstances.

"I expect that good form here is to say something touching. But I have
nothing to say. I never really knew my brother." He took a breath, and
held it long.

“None of you in the audience has ever been struck by me. I know this
because since my childhood I have never struck anyone -- except my
brother. I can't explain why, or what motivated it. Children are
foolish; they let foolish motives guide them. Well, I made someone
suffer because of the pathetic desires in my heart.

“As the years passed, all of this left me. But not so the barrier that
had been created between him and me. The walls went up, and what reason
did they have to come down? Life separates people, and it is too painful
to recall memories like that. It's so much easier to let them pass by,
and shift our focus onto other things.

“And so I never met the best part of him. Instead he showed it to you,
his friends. But I, who should have known him best, lost my chance
because of a stupid rivalry.

“That's why I have nothing to say to you today. But I am grateful to you
for being here, since now I can meet with that part him which touched
the hearts of others: that part I always knew was there from afar, but
never met. In your eyes I can see reflected the joys he shared with you,
and the magnanimity of his heart... How much a loss I never knew him...

"Thank you again for coming, and acquainting me with who my brother
was."

He lowered his head and only stared at his fingers. He must have felt
pinned, even though none of us would have judged him badly. Who hasn't
done such things?

But he raised his head again, and in his eyes there was more to be said.
He fought with it -- I could see his lips moving slightly -- and then
looked down again. But shortly afterward he began to speak.

“I guess things like this happen between people all the time. We always
consider that what we do is nothing more than an action, with certain
immediate consequences. But is that all it is? We hurt somebody and it
ends there? Maybe they're angry as a result, or maybe they say nothing.
Then we go on to the next moment of our lives, and soon forget what
happened. But I know that closeness depends on a very delicate
connection between people, which can be destroyed irretrievably if we
don't take care.

“I never really asked my brother for forgiveness. Maybe if I had he
would have just laughed it away, saying it was nothing. But the bond
between us had been lost, and I knew it would require tremendous pain to
recover. And neither of us wanted that. Life was too difficult already.

"I guess the only thing I can say is that I've learned something from
this: that the day will come when an opportunity can be lost, and when
you realize that the people closest to you you never knew. What's worse
is that we may never know them, as we hope foolishly for a magic day to
come when everything will be forgotten. But that day never comes."

He shook his head and stopped speaking abruptly and looked down again. I
think he understood the negative impression he had created, but it
seemed beyond his power to transition into something more hopeful. Maybe
he felt that an anecdote, or some word of optimism, would make too much
light of the experience he was trying to share. In either case, he
turned away from the podium and walked back to his place. And sitting
down he kept his eyes to the floor, never raising them, with the same
expression of thought always on his face.

Was he trying to resurrect some past memory that might exonerate his
misdeeds, which he had now confessed? Yet he never moved, not through
the next speaker or the one after; it was not until the final words were
said that he stood and departed from the room and its oppression.

Any time I saw him after that, I could always detect, if I looked hard
enough at his movements and his eyes, the impression of that day.
Perhaps it was in this way that his brother had finally become a part of
him: a gift as he later told me, because his brother had indirectly
taught him a very important lesson about the relationships between
people. Something which the memory of that day would never let him
forget.

I suppose just watching this process made an equal impression on me as
well, since I seem to think about it so much. Perhaps writing it down
will finally rid me of it, or maybe it will only infect another person,
carrying the atmosphere of that small Pennsylvania church far beyond the
confines its walls. At any rate, I hope the reader will forgive me;
sometimes the force of ritual events has an indelible effect on our
minds, making us loquacious over things we should probably remain silent
about.
