:PROPERTIES:
:ID:       1BB4C628-FCB9-4950-B529-18C9A8FAFEC1
:SLUG:     striving-for-sorrow
:END:
#+filetags: :journal:
#+title: Striving for sorrow?

I have been paying attention recently to people's "life ethic", or the
central philosophy which organizes their thoughts and activities. In
Western society, I find one to be extremely prevalent: "Really living
should feel like hard work."

My thinking is that really living should feel absolutely wonderful. Yet
I come across the above idea again and again, like a sun around which
Western life revolves. Where did this idea come from, and why are people
so unwilling to look elsewhere?

It seems too obvious to explain it as a Puritan ethic derived from
Christianity. It occurs elsewhere in the world as well. I think
Puritanism is simply a formalization of the ethic, rather than its
birthplace. I think it's been with us for a very long time.

I used to think it might just be the extravert's credo, since an
extravert would naturally prefer an ethic that removes him from
self-relative experience: better to feel suffering for another, than joy
in one's self. But then found that introverts are really no different.
They merely internalize the feeling of suffering as a noble punishment,
rather than a noble service.

I am not denying the merits of hard work -- and the need to make that
disclaimer shows how pervasive the ethic is -- but rather the idea that
really living should /feel/ like hard work; that one is not moving
forward until they regularly experience a state of suffering.

It is possible for the body to suffer, and the spirit takes joy in this
suffering. Athletes experience this, as do mathematicians seeking a
proof, as does anyone who really loves what they do. Working is
exertion, and exertion causes some part of us to suffer. Yet how we
experience that internally varies largely based on our feeling about the
activity. If we'd rather not be doing it -- say, mowing the lawn a kid
-- it can feel like agony; but if we love it -- a landscaper artist
doing the same thing -- it feels somehow divine.

It is the basic life ethic that seems to determine the tenor of how we
experience life. It guides our choices in whatever direction fulfills
the demands of the ethic. If we believe life should feel like hard work,
we put ourselves into those situations: a difficult job, trying
relationships, educational hardship, etc. It can be as if we're living
to make the ethic happy, and not ourselves happy.

Which makes me wonder if there should be any ethic at all. What drives
us should not be an ideal, but a thing that can actually be experienced.
An ideal, after all, is only an abstract never to be found in life, only
approximated. Whereas the quality of something we love is known in the
moment of our being near it. It's the difference between having an ethic
that says, "Life should be beautiful", and living for an experience of
beauty. In the first case one must always judging whether the
expectations of "beautiful" are being met, while the latter is based on
a visceral reaction that is quite immediate and obvious.

Maybe belief in an ethic is a form of desiring control over the
indefinite nature of life. In that sense, I can see it as a normal part
of our progression. It would only be in holding to it too dearly for too
long, that we would be hindered.
