:PROPERTIES:
:ID:       A9D73108-7F41-46A2-925E-58C5FCD388EE
:SLUG:     the-candle
:LOCATION: 325 Morrow Road
:END:
#+filetags: :poetry:
#+title: The Candle

#+BEGIN_VERSE
The candle is a master at love.
He stands tall, and presents himself
before his lover.
He kindles a divine spark in the heart
and sets the core of his being
ablaze with devotion.

The temperature rises:
it burns him with sweet fire.
He begins to melt away
in thought of her;
he sighs in hot wisps
that rise on the air.

As he thinks of his beloved
he weeps away precious tears,
for he soon comes to realize
one of love's mysteries:
that truly to love,
the lover must disappear.

Thus, his hardened self yields to liquid,
then to fire, then to light.
He brightens her face by his feeble flame --
and she calls it romantic;
he grants her a moment's peace
in fighting off the shadows of the night.

And though he burns his life away,
what he is now, is his lover's delight --
for he has found the immortal Way:
her happiness is his happiness.
#+END_VERSE
