:PROPERTIES:
:ID:       217B4ABF-A0C1-423E-B0D1-BEC712B0712A
:SLUG:     joshua
:END:
#+filetags: :stories:
#+title: Joshua

Joshua rested his face on both hands, gazing at the sea. It moved
rhythmically, with so much peace. He longed to stretch out his wings and
take flight over its vastness. But he had no wings. He was just a man,
and the sea a mythical creature beyond his ken.

"O my tears!" he cried, "are you some vestige of the sea seeking to
regain your heritage? I am but a lonely poet, cursed by my thoughts.
With no one to hear me your are my boon companion, my sea. With no one
to care for me, you are the only one left."

He looked at the white sand around his feet and drew patterns in its
whiteness. Sad, lonely patterns: solitary circles and lines, none of
them connecting. How miserable it is, this life! He lay his head back
and closed his eyes against the sun.

"Joshua?", a nymph's voice echoed on the rock. He dreamed of a fairy
princess with three wishes and a kingdom of gold. "And my first wish,"
he said to himself, "is to banish my need for wishing. If life were
enough for me, it would be a kingdom indeed."

"What's that, Joshua?" the nymph asked, now closer. Joshua opened his
eyes to see his wife's face haloed by the noon-day sun.

"Nothing, Marie. Nothing that time and a pool of tears won't cure."

"My word, if you weren't so gloomy all the time you might just notice
life. It's all around you, you know."

"It's all around me," he repeated, "like the darkness of night
enveloping me until I can see the light no more. That is what this life
is doing. How I can take heart in that?"

“Sometimes, Joshua, I swear that you create your own world just for
profit's sake. Who would buy your poems if they weren't so tired and
blue that people can't find them elsewhere? 'Joshua: ever loyal to his
fans,' they'll say, 'he never missed a moment longing for the next.”'
Marie sat down with a derisive smirk. They had been married far too long
for an exchange like this to provoke anger in either one of them.

"Joshua, do you remember twenty years ago? Then the moon was a symbol to
remind us that the sun was simply hiding, still shining its light. Sure
as the moon is bright, the sun still shines. But slowly it became
something else to you, like a midnight sun of its own, blaring with a
cold, lifeless light. Don't you remember how we used to gaze at the moon
together?"

"I still remember it," he said. "It's a pity that memories build up the
way they do, without asking. Otherwise tomorrow I might forget this
terrible sadness, and enjoy a day or two of happy childhood again."

"You a happy child? I'll bet you set the other kids into tears with your
moaning and complaining. You were never happy, Joshua. That's what makes
your poems so good. They're sincere to the heart. Which is scary
considering the things you write."

Joshua turned on his side with his eyes still closed. His wife continued
talking about something, but he just lay there, listening to the rhythm
of the sea.
