:PROPERTIES:
:ID:       62A1CB60-1ECF-4ADE-89D5-674A024F27E3
:SLUG:     the-aim-of-religion
:END:
#+filetags: :essays:
#+title: The aim of religion

Although it is true that every religion upholds the "twin pillars of
reward and punishment", yet this is not the purpose of religion. To
consider it so would reduce religion to a mere code of ethics, in which
the whole aim revolves around our development.

Schools use reward and punishment to create an atmosphere of learning.
And while the progress of each child is the reason for the school's
existence as an institution, the aim of schooling is the pursuit of
knowledge -- not solely earning the marks of progress. Many pursue that
knowledge for its pragmatic value, while a choice few will fall in love
with Knowledge herself, and find themselves natural-born philosophers,
distracted in their love of the Abstract.

Likewise, religion is about awakening the soul to its Creator, that it
might know and worship Him. Insofar as moral rectitude conduces to this
(especially in a group setting), religion preaches ethics.

#+BEGIN_QUOTE
... it is the relationship of the individual soul to God and the
fulfilment of its spiritual destiny that is the ultimate aim of the laws
of religion.[fn:1]

#+END_QUOTE

In this sense, the acquisition of perfections is functional, not
essential. That is, the aim of life is not the acquiring of perfections,
but the consciousness of God that such an acquisition facilitates.
Should we really spend our time worrying about our own development? It
would be like a lover practicing how to love so ardently, that he
forgets his Beloved standing right next to him.

As the Sufi mystic `Attár describes:

#+BEGIN_QUOTE
God from on High said to David: `Say to my servants: "O handful of
earth! If I had not heaven for recompense and hell for punishment, would
you ever think of me? If there were neither light nor fire, would you
ever think of me? But since I merit supreme respect you must adore me
without hope or fear; and yet, if you were never upheld by hope or fear
would you ever think of me? Since I am your Lord, you should worship me
from the depths of your heart. Reject all that which is not I, burn it
to ashes and cast the ashes to the wind of excellence."'

#+END_QUOTE

And the Báb wrote:

#+BEGIN_QUOTE
Fire and paradise both bow down and prostrate themselves before God.
That which is worthy of His Essence is to worship Him for His sake,
without fear of fire, or hope of paradise.

Although when true worship is offered, the worshipper is delivered from
the fire, and entereth the paradise of God's good-pleasure, yet such
should not be the motive of his act. However, God's favour and grace
ever flow in accordance with the exigencies of His inscrutable
wisdom.[fn:2]

#+END_QUOTE

We should not be anxious over the question of how to judge our progress.
The real aim is to find God, a search we are aided in if we undertake it
sincerely. We will find the confirmations we need, and be given
knowledge to continue on the Way. In this, prayer and meditation are
essential, and the most valuable tool:

#+BEGIN_QUOTE
For the core of religious faith is that mystic feeling which unites Man
with God. This state of spiritual communion can be brought about and
maintained by means of meditation and prayer. And this is the reason why
Bahá'u'lláh has so much stressed the importance of worship. It is not
sufficient for a believer merely to accept and observe the teachings. He
should, in addition, cultivate the sense of spirituality which he can
acquire chiefly by means of prayer.

#+END_QUOTE

Lastly, concern over our future state is one of the forms of attachment
that actually hinders our search! The Bahá'í Writings call it
"attachment to the next world". Whereas to forgo everything in our
search for God is what is called for.

#+BEGIN_QUOTE
For when the true lover and devoted friend reacheth to the presence of
the Beloved, the sparkling beauty of the Loved One and the fire of the
lover's heart will kindle a blaze and burn away all veils and wrappings.
Yea, all he hath, from heart to skin, will be set aflame, so that
nothing will remain save the Friend.[fn:3]

#+END_QUOTE

[fn:1] Universal House of Justice, Introduction to the Kitáb-i-Aqdas,
       pp. 2-3

[fn:2] Báb, Selections from the Writings of, p. 78

[fn:3] Bahá'u'lláh, The Seven Valleys, p. 36
