:PROPERTIES:
:ID:       72F7F379-C5F2-4869-82AC-D8A64C51082C
:SLUG:     stepping-beyond
:END:
#+filetags: :journal:
#+title: Stepping beyond

Having described the veil, and the merits of the veil, I was struck by a
thought of how to beyond it. It is not a passing of the body, however,
but only of the spirit. Our eyes remain on this side, with our vision on
the other. It's like looking at things from a higher perspective while
still seeing the details.

Religion says the veil may be crossed in a single instant. Although it
can take a lifetime, the journey is less than a hair's breadth:

#+BEGIN_QUOTE
Behold it is closer to you than your life-vein! Swift as the twinkling
of an eye ye can, if ye but wish it, reach and partake of this
imperishable favor...

Thou art but one step away from the glorious heights above and from the
celestial tree of love...

[The wayfarer] may cross these... stages... in a single breath, if God
will and desire it.

#+END_QUOTE

What can take us there? I think that just as the body is moved by the
motive force of will, the soul is lifted by the motive force of love. It
is not love of an ordinary sort, but the very love we are here to learn:
love for the whole. This is a love which manifests itself in different
ways according to the parts, but is directed at the being of the whole,
and the movement of that being. It sees the whole reflected in every
part, until it sees no parts at all, even though the eyes always will.

In thinking about the outward signs of such a love, I came across a
statement by Bahá'u'lláh about equality. He said that although treating
others equally is a station beloved of God, regarding others as higher
than one's self "is above this station"[fn:1]. Which got me to thinking:
this is exactly how a lover treats his beloved. He regards her as higher
than himself, such that he would willingly give up his life. This
reminded me of a statement from `Abdu'l-Bahá, about how the believers
should be when they meet each other:

#+BEGIN_QUOTE
Should one soul from amongst the believers meet another, it must be as
though a thirsty one with parched lips has reached to the fountain of
the water of life, or a lover has met his true beloved.

#+END_QUOTE

This points toward a view of things very much like an impassioned
lover's. Which creates paradox, in light of the following statement from
Rúmí, which is quoted in the Seven Valleys:

#+BEGIN_QUOTE

#+BEGIN_QUOTE
Love is a veil betwixt the lover and the loved one; More than this I am
not permitted to tell.

#+END_QUOTE

#+END_QUOTE

If love is a means through the veil, love is also a veil? This could
mean that love of certain parts -- preference -- can hinder us from
loving the whole: like a lover who falls so much in love with one person
that he can barely remember the existence of others.

In loving the All, every face is different yet the same, and there is
only one aspect to creation, just as all lanterns shine with the same
light, "... until none shall contemplate anything whatsoever but that he
shall see God therein." This does not contradict my earlier beliefs on
Quality, since the eyes themselves do not pass the veil. It is not the
places of the light's manifestation that I refer to, but the source of
their illumination.

The All is like a pure light, which is fragmented and perceived by the
eye. Seeing the All is seeing the light of the sun in everything, and
not viewing things as fundamentally apart -- until one communes with the
All itself, no matter how variable its manifestations, or the needs of
those manifestations. This is looking at the flower, but seeing it as a
mirror of the sun. "... and some have drunk of the wine of oneness and
these see nothing but the sun itself." To reach this vision requires
love, because otherwise the heart is not willing to step beyond.

Kindling this love is the difficult part. If we saw true Reality, I
think we fall in love with it in an instant. So we are ultimately faced
with the task of loving the All before we can see it. Isn't this the
very province of faith? Perhaps in developing faith, and being willing
to trust in the most positive view of life possible, such a love can
bloom.

[fn:1] This may be found in the Lawh-i-Ittihad (Tablet of Unity), which
       has been
       [[file:provisionally%20translated][http://bahai-library.com/provisionals/ittihad.html]].
