:PROPERTIES:
:ID:       ADE57782-FAC4-4108-BAC3-51995970E19C
:SLUG:     robot
:END:
#+filetags: :stories:
#+title: Robot

A young boy grew up in the control room of a giant robot, on shoulders
that towered fifty feet from the ground. The room had everything the boy
needed for life: food, water, entertainment, education; and on the
screens and displays around him, full contact with his world. On those
screens he could see whatever the robot's eyes were directed at, while
other lights and speakers gave account of the smells, sounds, and even
tastes the robot's senses came in contact with.

Using a set of hand and foot manipulators, the boy was able to move the
robot wherever his heart desired. During the days, the boy took his
robot to places he'd been given a map to find, by a pair of guiding
agencies called "parents". These too were once children, having grown up
in a similar exoskeleton, but since no one ever opened the robots --
there was no hatch, or cutting tools that would not also destroy the
occupant -- the boy assumed they were beings of a different order, and
accorded their directions much more authority than his own desires.

At "school", one of his daily errands, he met other robots, whose speech
forms and ideas were similar enough to his own to establish a strong
rapport, in which he ceased to think of them as robots but as "friends".
It was a strange though familiar world, filled with all these talking,
mechanical beings, seen and heard through viewscreens.

One day he found an object in his viewscreen which showed a robot who
obeyed all the same actions as his own. He was told this robot was an
image of himself; however, this was too odd a thought, since the image
was a robot, and he was a softer, fleshier being sitting behind a bank
of controls. He quickly put the idea out of his mind entirely.

As the years went by, the boy grew, mentally and physically. His
knowledge of the world outside the control room grew ever faster, with
all the things he saw and heard and felt through the soft manipulator
arms that hardened and changed texture according to whatever he picked
up. This catalog of objects and senses built up his awareness of a rich,
varied world that the young man took great pleasure in exploring.
Through school he even learned how to build new things, to add to the
immense richness of his diverse knowledge.

Soon the young man was no longer so young, and he earned a respectable
place in a growing society, working to fabricate parts for buildings. On
off days he played sports in a local league, straining his skills at
chasing a leathery sphere across fields of grass, taxing the abilities
of his robot body to the utmost. In the evenings, he returned home to
his companion, Lucia, an able and devoted 'bot who helped him in his
life, added a feeling of warmth and homecoming, and whom he regarded
fondly whenever her smoothly curved carapace sidled across his field of
vision.

His life had everything in it any robot might ask for: in fact, it
called for hardly any changes beyond the ordinary desires of interest
and activity. Until the day he met the bizarre small one.

The small one was very small. The man had to stoop his robot to get a
clear view of the pasty white face with its strange colored circles, a
flat, flexible slit in the middle, and protrusions on either side of its
"head". The strangest part was that the lower parts of the creature were
reminiscent of the man's own body. It had the same splayed fingers and
toes, and two arms and legs. However, the man had never seen anyone like
himself before, and had no more reason to assume a connection than we
might watching a lemur climb branches in the wild.

The small one did know the man's language, however, though he spoke in a
squeaky, tiny voice that was difficult to hear. By kneeling down to the
small one's level, and moving his metal head near the flexible slit, the
man was able to converse with this strange creature from the outer
world.

The small one said his name was Walt. The man replied, "Mine is John.
What are you, that you have a name?"

"Why, I'm a man just like you are, John! Haven't you met a man before
now?"

John replied in puzzlement, "What do you mean? There is no one else like
you. How can you even get around on such small legs? What can you do? If
you're like me, how do you get food and water?"

The little one named Walt was obviously amused. He clapped his hands on
his knees and chuckled long and hard. "Aha! My metal-bound friend, I can
certainly understand your doubt. I mean, how many others like me /can/
you have seen before? The old model isn't exactly popular!" At this Walt
broke into another stream of curious, tinny laughter.

"What do you mean?"

“Well, I admit my condition is somewhat of an accident, but afterwards I
had a lot of time on my hands to do a little snooping around, and I
discovered from the old records how our present state of affairs came
about. You see, there's not much call for people in my state, as no one
really believes I'm capable of doing anything. So they left me free to
rummage among the few thousand books still remaining in the museums.
There are advantages to being shorter than even the shortest robot's
field of view.

"Anyway, what the old books tell is that originally we were all as I am
now."

John gasped loud enough to startle Walt out of his recollections. Since
John's voice was so amplified, to bridge the usual distance between
robotic mouths and ears, it was nearly a roar to Walt.

"Yes, yes," Walt continued, "All like tiny, hapless me. That was long
before the calamity, the days of hardship, and all the other reasons we
retreated into the protected life of robotic augmentation."

John watched the author of this ridiculous tale, his fuzzy brown hair,
his small features difficult to make out without magnification. What
could he possibly mean by any of this? It made no sense at all. Maybe
the cold wind -- his sensors registered it being quite chilly outside, a
fact reflected in the slightly cooler interior temperature of the
control room -- had disturbed the mind of this strange, talking animal.
Maybe he should gather him up for the city zoo?

Meanwhile Walt continued, unaware that John had ceased registering the
details of his story, lacking as he did any relationship to what was
being described. "And that, my capacious friend, is why no one looks
like me anymore at all. For too long the atmosphere was unbreathable,
and living in domed areas impossible for want of adequate communal
structures. Or maybe we just made some bad choices, ending up with a
tradition of isolation in robotic carriers. For whatever reason, it
became tradition for too long, and now we even gestate our babies in
newly built walkers! No one knows it's unnecessary, and I've found no
way to describe to people that life could -- and should -- be very
different from a few tens of thousands of lonely people trapsing around
in the guise of gigantic metal men!"

"What do you mean by lonely?" John countered. "Lucia and I have the very
life we always worked for. I think no one agrees with you because you
make no sense at all. You describe something that doesn't exist, but
claim it should, all the while portraying our life as if it shouldn't
be! I think you are quiet mad, little one."

"John, John..." Walt sighed and wagged his head left, then right, then
back again: a curious gesture John could not fathom. "Of course you
think so -- this is all you've known!"

Walt stood up and waved his twig-like arms outward, pointing them at the
city beyond the hill they stood on. "Do you think this is all there is
to know? How can you possibly? You've never tasted anything, never seen
anything with your own eyes, never heard the birds, the wind, or felt
the rain pelt you with warm drops on a summer night! John, you've hardly
begun your life, only observed it through monitors and measures,
analyzing the chemical meaning of apple blossoms, but not filling your
nostrils and lying stunned on your back by the simple beauty of spring!
You read about life, purvey it, but as yet you are not part of it."

John squinted his eyes to see his screens better, tuned his ears to the
sound of Walt's voice, but could hear only the madness. For certain,
this little creature was excited about something, but he spoke in a way
only the malfunctioning did before being recalled for maintenance.
Perhaps the creature was in need of correction also? But where to find
the parts he needed, when it looked as though there were no seams or
joins at all, no ports for repair? A true mystery, and one John was
feeling less and less inclined to pursue by the minute. All this chatter
was going nowhere, and there was still more work to complete for the
day's quota. Why had he come out this far for lunch, thinking he would
watch the clouds pass serenely by as he listened to music and absorbed
the nutrient fluid that entered his bloodstream at midday? Instead, this
minute nuisance was spoiling all hope of serenity, and even his fluid
uptake was less satisfying than usual.

"Little one, whatever you are, this talk goes nowhere. Perhaps it's time
for you to rejoin your kind in the forest, or wherever you live, and
leave me to my function. Cities are not built by words, and that seems
all you are capable of."

Walt looked straight at the robot's forward sensors, his eyes very large
and rounded. John could clearly see there was more white to them than
color in this mode. It took a long moment before Walt began speaking
again, after which he said, “Have you heard nothing I've said?

"You are a man, not a machine! You live cooped up in a little room
inside a robot's head, seeing and experiencing the world through sensors
and pickups. It served us for a time, allowed us to survive in a harsh
climate, but those times are over! You can come out now! Don't let a
screen tell you what a rose looks like, or a readout describe its smell
to you! Come down from your prison of convenience and /live/ the rose,
prick your thumb on its thorns, dirty your legs as you kneel to smell
it, be stung by the honeybees that circle in the awed reverence of life
seeking life. You allow yourselves to be told what life is, what it
means; from age-old necessity you were bound to this crude form of
strength and digital enhancement; but now people mistake the rider for
the horse. If you won't come down, how can you even know if the image
you see is really what's before you? Your faith in sensory equipment has
become your definition of life itself."

With this Walt slumped down, his head facing the ground, silent after so
much agonizing, though still squeaky, speech. John caught a sense of its
pain, the sadness of this poor creature's life. After all, what could it
possibly benefit anyone to be created so weak and incapable of
influencing the world? Perhaps speaking was its last resort, its
unending complaint against the hand dealt by so cruel a fate.

And so John, always having been compassionate by nature, raised his
powered fist and ended the mystery of the aberrant little creature.
Surely it must be happier not to be, than so unlike the design both
nature and proven results clearly indicated.
