:PROPERTIES:
:ID:       35086717-9373-4752-BCD0-40C72C6ADE5E
:SLUG:     what-hell-might-be
:END:
#+filetags: :essays:
#+title: What hell might be

Imagine that our lives were like that of a foundling bird in its nest.
Newly born, he sees around him only a tall, thatched wall of brown and a
blue sky above. He shares his nest with several other little birds who
are just like him. And every once in a while a much Greater, Grander
Bird (and also exceptionally kind, for She is their mother) comes along
to bring them all food and keep them warm.

Imagine further that one of these birds (a brother to the one whom we're
imagining) has fallen in love with the idea of feathers. Every day, he
picks up the fallen tufts from the bottom of the nest and stores them
away in a little corner of the nest.

Over time, however, he is not content merely with collecting the
discarded bits. He wants clean, shiny feathers, like those found on the
wings of his brothers and sisters. So he makes them an offer. To our
little bird he offers all the wonders that he's found in the nest --
bits of wood and flowers, maybe a tiny crystal of quartz -- and in
return, baby bird must allow him to pull off his wings, so that his
brother can own all of those shiny feathers for himself.

Now our little bird has a choice to make. In his mind, of what value are
his wings, anyway? He cannot do anything with them; they only get in his
way from time to time. In fact, they do not appear to have any use
whatsoever, relative to his life in the nest.

On the other hand, brother bird has offered him real, concrete things;
things which are pretty and might be valuable. It doesn't seem like a
very hard question to answer: trading something pointless and
cumbersome, for the interesting objects offered by his brother.

So baby bird cuts the deal. And because his wings are so fragile, and so
tiny, removing them is not even painful. He definitely thinks that he is
a winner in the bargain -- and his brother is happy too. Everyone seems
to have come out well.

So the weeks go by. Baby bird is the envy of the nest because of all of
the wonderful things he has. And perhaps, because he is a nice bird, he
is even generous with them, distributing his wealth among the nest.
Indeed, he is a most popular and regarded bird, seemingly in possession
of all that an aspiring youngster could want.

Until that fateful day comes, as it always must. The nest is not big
enough for everyone now; it is time to leave. With great sorrow and
travail, each one of his brothers and sisters is helped up to the edge
of the nest by the Great Bird, and disappears. One cannot see where they
go, but one by one the nest is emptied.

Soon it is baby bird's turn. He approaches the rim with great pride and
satisfaction. After all, whatever it is, it must be full of
opportunities for him! Hasn't he lived his life well? Hasn't he taken
full advantage of whatever was available to him?

He walks toward the edge and is very nervous -- although delighted --
with anticipation. The Great Bird helps him to the rim of the nest, and
finally he discovers what each bird before him has already seen: the
Great Beyond.

Imagine that you are that bird, and have just now placed one foot into a
world far different from any you had ever imagined. Picture the wide
expanse of blue that must have seemed endless; or the exciting world of
/terra firma/, so varied in hue and color, not at all like the brown,
drab domain you had just come from.

Yet, imagine also the inconceivable, indescribable sadness that must
have worked its way slowly into the mind of our little bird: the mental
weight of realizing, after it was too late, exactly the mistake he had
made on that miserable day, when he had sold something, apparently
meaningless, for something else which had appeared valuable; imagine how
his perception of the world was now suddenly reversed: what had seemed
large was now small, what had seemed useless was now full of utility,
and what had seemed attractive was now deserving only of contempt.

The state of consciousness into which our bird must resign himself --
for he will never be able to fly without wings -- perhaps this we would
call hell: to realize fully what one had lost, and that such loss was
the result of one's own conscious decisions.

And yet, even as no story in this world seems truly to be final -- since
everything is contingent on the Mercy of our Father -- the following
words of Bahá'u'lláh come to mind:

#+BEGIN_QUOTE
I am the Royal Falcon on the arm of the Almighty. I unfold the drooping
wings of every broken bird and start it on its flight.[fn:1]

#+END_QUOTE

[fn:1] Tablets of Bahá'u'lláh, p. 169
