:PROPERTIES:
:ID:       5E7B192E-2C12-42A7-AEEC-00D6718FCD64
:SLUG:     joy-and-community-life
:END:
#+filetags: :essays:
#+title: Joy and Community Life

* What is a Bahá'í?
:PROPERTIES:
:CUSTOM_ID: what-is-a-baháí
:END:
What is a Bahá'í? What differentiates a Bahá'í from anyone else in
society? Or a Christian, a Hindu, a Muslim? Is it moral behavior, a set
of high ideals, particular characteristics, certain beliefs? These are
shared in common by many groups, both religious and not. So when we
think of a Bahá'í, what are the identifying qualities?

Christ referred to His disciples as "the salt of the earth". What is the
meaning of this salt? When we look at the material world, everything it
possessed comes from dust. All the time, money, ideas, institutions,
resources, etc., are generated or mined by the bodies and intellects
that abound on the Earth. There has never been a shortage of these.

There is a quality which has nothing whatsoever to do with the dust. It
does not issue from it, and does not return to it. It is not part of our
animal heritage, is not found in a perfect body, or heart, or mind. It
is a quality that cannot exist in nature unless a pure heart manifests
it. This quality Christ called "salt".

Bahá'u'lláh describes human reality as a mirror. Its capacity to shine
is what makes possibility the manifestation of divine realities in the
world. He writes:

#+BEGIN_QUOTE
O My Brother! A pure heart is as a mirror; cleanse it with the burnish
of love and severance from all save God, that the true sun may shine
within it and the eternal morning dawn. Then wilt thou clearly see the
meaning of "Neither doth My earth nor My heaven contain Me, but the
heart of My faithful servant containeth Me."[fn:1]

#+END_QUOTE

Human beings are thus capable of bringing into reality, and worldly
projects, a quality which can appear in any other way. Those who bring
this quality into the world are regarded as the beloved of God. In each
age and century they have varying names, but such have been called Jew,
Buddhist, Bahá'í.

* Our gift to the world
:PROPERTIES:
:CUSTOM_ID: our-gift-to-the-world
:END:
If this is our unique capacity, it also represents our power, our gift,
the one thing needed by the world above all else, which the world cannot
acquire by itself. Even the social and ethical teachings of the
Manifestations are not enough in themselves. Shoghi Effendi wrote:

#+BEGIN_QUOTE
Laws and institutions, as viewed by Bahá'u'lláh, can become really
effective only when our inner spiritual life has been perfected and
transformed. Otherwise religion will degenerate into a mere
organization, and becomes a dead thing.[fn:2]

#+END_QUOTE

It is this quality of spirit that deserves our focus, because nothing
can proceed without it, while all things will find their way to solution
when it appears. The National Spiritual Assembly said, "The millions of
Americans who are searching for spiritual truth are searching for traces
of God's love."[fn:3]

This spirit is of the nature of all things good, joyful, loving, true.
All sadness and misery come from the material, as `Abdu'l-Bahá spoke:

#+BEGIN_QUOTE
If we suffer it is the outcome of material things, and all the trials
and troubles come from this world of illusion.[fn:4]

#+END_QUOTE

Whereas He told us "the spiritual world bestows only the joy!" So joy
and radiance are the signs, the tokens of this spirit. They become the
measure by which we can judge the success of our spiritual endeavors.
And they relate directly to the value of what we achieve in this life.

The material world, being the abode of dust, abounds in dust. All the
wealth mankind could ever need springs from the ground itself. There is
nothing we can add that will not in the end decay and return. The world
does not need more wealth, or an ever finer parade of forms displaying
that wealth. It needs what it lacks, the salt. And if we neglect to
bring it, Christ asks, "And if the salt hath lost its savor, wherewith
shall it be salted?" In this sense, we are the bringers of light, the
bearers of glad-tidings, the heralds of grace; we reflect by our hearts
the true wealth from God, the "manna from heaven".

If this spirit, this joy and love and warmth is so profound -- the
defining characteristic of the servants of God, by whatever religious
name -- then our discussion should revolve around it, and aim toward it.
Worldly problems will never cease; sometimes discussing them makes them
worse! Whereas when we have joy, happiness, it is often the case that
the material gives way:

#+BEGIN_QUOTE
If we suffer it is the In times of joy our strength is more vital, our
intellect keener, and our understanding less clouded. We seem better
able to cope with the world and to find our sphere of usefulness.[fn:5]

#+END_QUOTE

* The present culture
:PROPERTIES:
:CUSTOM_ID: the-present-culture
:END:
Does our present culture foster joy, engender the spirit? This would
define a "Bahá'í" atmosphere, according to the previous discussion. We
know that prevailing social norms affect us, but do we understand how?
The current culture might be called a Christian culture with a slight
Bahá'í twist.

* Changing the pattern of activity
:PROPERTIES:
:CUSTOM_ID: changing-the-pattern-of-activity
:END:
Doing less can result in achieving more, in the mathematics of joy.
Spirituality is not like weighing ingredients to measure the recipe;
this was shown in the example of the loaves and the fish. When there is
true spirit, even raw flour is a king's meal.

#+BEGIN_QUOTE
Although to outward view, the wayfarers in this Valley may dwell upon
the dust, yet inwardly they are throned in the heights of mystic
meaning; they eat of the endless bounties of inner significances, and
drink of the delicate wines of the spirit.[fn:6]

#+END_QUOTE

My recommendation is that we follow closely Bahá'u'lláh admonition:

#+BEGIN_QUOTE
Lay not upon your souls that which will weary them and weigh them down,
but rather what will lighten and uplift them, so that they may soar on
the wings of the Divine verses towards the Dawning-place of His manifest
signs; this will draw you nearer to God, did ye but comprehend.[fn:7]

#+END_QUOTE

The prevailing culture of guilt and perfection retard our growth. The
soul has wings; in joy let it fly.

[fn:1] Bahá'u'lláh, The Seven Valleys, pp. 21-22

[fn:2] Shoghi Effendi, Directives from the Guardian, pp. 86-87

[fn:3] Feast letter of March 20, 2002

[fn:4] `Abdu'l-Bahá, Paris Talks, p. 110

[fn:5] `Abdu'l-Bahá, Paris Talks, p. 109

[fn:6] Bahá'u'lláh, The Seven Valleys, p. 30

[fn:7] Bahá'u'lláh, Kitáb-i-Aqdas, p. 74
