:PROPERTIES:
:ID:       03646473-1BE1-47EC-881D-3589A53155F6
:SLUG:     experience
:END:
#+filetags: :journal:
#+title: Experience

This is one side of a chat with a friend earlier this evening, which
connects with ideas from the entry on the beauty of existence:

Your nature is not you. It is only the carrier for your awareness. There
is no "you". There is only life, the experience of life. The experiencer
is the experience. There is no separate reality which stands outside it
all, dipping its hand in here and there. You are as much your experience
of the sky when you look at it, as you are your experience of your
nature when you become aware of it. You can appreciate it to a fuller or
lesser extent, but there is no controlling it.

Now, you can take actions which change the particulars of the
experience, and there is great value in doing so, but it does not change
the underlying nature of experience itself. So, in wanting to control
your nature as if to control yourself, you are dividing yourself in two,
between the experience and the experiencer. There is only life. Point to
anything that is not life. See if you can find even a shred of evidence
for its existence. Look for it, you will not find anything other than
your experience. Even memory is just the experience of remembering in
the present.

Here's what I think happens: we grow up with the message that we should
become something. That's a good message, especially when we are looking
for direction in life. We are taught that becoming "good" is the highest
form of becoming, and so many of us want that. Without any deeper
understanding of life, that is a pretty awesome goal, actually. But what
happens is that we become utterly absorbed in that task, because as
children, our parents, our society, gave us the task. It sets in, very
deep, the sense that we are fulfilling it /for/ somebody; as if someday
-- maybe in the after-life -- if we work hard enough to become good,
somebody will put a gold star on our forehead and say, "Yes, you have
now reached the stage I wished you to achieve." We are looking to
fulfill the original plan of our childhood, which is to become this
"good" we wanted to fulfill.

And so we pursue it, by many different means. Some of these means are
even the task of removing self. But the thing is, the entire scheme is a
scheme of the self. There is no part of us which can "be" good, since we
are only our experience. This doesn't mean that pursuing goodness is
wrong, just that we took it to heart in the wrong way. And even that was
not wrong, it was just... suited to a different mentality. It was what
we needed to motivate us. But here we go, seeking to acquire this
"goodness" so that we can gain the ultimate approval we've always
wanted. But when you start on the mystic path, for example, you reach a
fundamental contradiction. You cannot hold absolute unity, and the
concept of "becoming good", in the same mind. They contradict each
other.

Because what is it that can "be" good? Unity means there is nothing but
what is. What part are you going to cut away, to put the gold star on?
Once you cut it away, you undo the goodness you thought you had
achieved. It becomes a fundamental paradox, achieving selflessness in
order to "be good". You have to have the idea of a self, in order for
that self to "be good". Otherwise, there is nothing that can be good.
Now, this does not mean that pursuing goodness was wrong. It's just,
it's not about the self acquiring goodness. The self is not a "thing":
it's sight itself.

If experience is not deepened, it remains very shallow, like a form of
blindness. Because of that blindness, the real good of existence cannot
be seen. God's very brilliance hides him, because eyes are unaccustomed
to His Light. So the good that you seek is /His/ good, not the acquiring
of your own good. The deeper you go, the more one's experience is of
Him, and of His good. This is the good you've been seeking all along.
You become that good by becoming the experience of that good -- not by
possessing it, or acquiring it.

The Law is there to assist you in opening your eyes. There is no
existent evil, but there is the evil that blinds men's souls. The reason
for punishment is to help the individual avoid that transgression in
future. But it's all functional toward the experience of God's manifest
being. The whole world you think you see is your blindness, your self.
The veil that's pulled over your awareness. Everything is functional
toward the end of union with God.

And not union of a "self" with God, but union through experience: baqá.
I think heaven exists in the present moment. But that doesn't mean we
get to see all of it. If I were a man in a park, and then I turned into
a bird, I could see much more of it without having to go to a new place.
If baqá is knowing existence itself to be heaven, death is simply a
broadening and deepening of that basic realization. But what is
important is experiencing God, moving toward Him. Reaching out into His
infinity.

To that end, we must leave the self behind, and the quest to "become
good". Christ said: "Why callest thou Me good? There is none good save
the Father." As another example, imagine you knew a girl, and realized
she was the perfect woman for you. That would only be the beginning of
really getting to know her. It would only grow from there, never
reaching an "end".

You see, all I'm saying is that existence is the only thing that exists:
and this existence is the manifest will of God. We can either appreciate
it, become fully aware, or no. All of the things that happen in this
existence are still this existence, are still part of the constant
unveiling of His will this existence represents. So, it is entirely
compatible with having a family, a job, a "normal life", etc. It's not
the content that matters, but our awareness of it. There is beauty in
everything. It doesn't need to be in a monastery on a mountaintop. It
can be in counting out apples to sell in the market. The details do not
matter. They only matter insofar as they help or hinder us in knowing
God. All of the content of existence is functional toward the awareness
of that existence. Beauty exists so we can know beauty.

To say that "normal life" doesn't fit is like saying that the content of
existence has no place in existence. This is exactly one kind of trap
that some mystics fall into, because the content of existence is the
awareness of existence. But there is only existence. There is only He.
So whether you pray, or raise a family, or do your job, you are
existing. Some things you do will help your awareness deepen, some
things won't. In those terms, you should choose. But there is no actual
better or worse, evil or good. There is no self that can be any of
those. There is only God. All that we see, /that/ is our self. When we
purify the nafs, we are purifying our sight, not some separate reality
that needs purification. Just seek Him, and that is all you ever need to
do, "with all your heart, and all your soul, and all your mind", as the
Jews say.

We worry relative to the gold star, to the task of "becoming good". We
fear we won't be good enough when the time comes. But here's the kicker:
you will never be good; there is no "you", there is no "being good", and
there is no "good" as opposed to evil. There are no gold stars handed
out. All you will ever have is your experience. And your experience at
any moment is the result of your own effort to truly know. Your
experience itself is the reward, and the goal.

When I talk about blindness, I mean blindness as a lack of experience,
relative to what could be experienced. However, even focusing on
blindness is misleading, because blindness is not something separate
that adheres to any "self". Let's just say that there is only
experience, and experience is all there is. Experience never ends. In
one sense, it can't even be divided between "doing", "done", etc. There
is just being, ipseity... is-ness. When you sit to pray, that is all
there is.

If we choose rightly, we will appreciate and love existence. If we
choose poorly, we will not. Religion is a guide to right living, right
seeing, right knowing, right acting, all to the end of experiencing and
appreciating the good. And that good can be experienced at any time, by
anyone, anywhere. No qualities need to be "acquired" to achieve it,
simply that we free ourselves from our blindness. And even that is not
blindness in the typical sense. It's more like you are talking to a
friend, and suddenly you realize they have more quality than you'd
earlier given them credit for. Now you value the relationship more, and
you put more energy into deepening that relationship. And as you do so,
your appreciation of their quality grows. And then you put in more
effort, etc., and so on ad infinitum.

But the thing is, you are /always/ with that friend, conversing with
them, from day one. You don't need to achieve a certain level to be
talking with them. As you progress, you simply get more out of the
relationship, you value it more, and see more fully what it has to
offer. Prayer is one of the forms of conversation in that relationship,
but there are many, many forms of relating to life. So really, it's just
that the deeper you go, the cooler it is to be, the cooler being is.
However you want to play with the words. Our relationship with the
Friend goes through infinite changes, forms, joys, etc.

And nowhere in all of that do we need to be "good"; our search for
goodness is really a search to relate properly. The same way that an
architect looks for good in his buildings by making things square. He
does it because it makes the building livable, and not because the
building then becomes "good" in any absolute sense. That is why being
worried about virtue should make us laugh. Any fear is like fearing that
suddenly that we will cease to exist. As long as you exist, you are with
Him. It's just a question of realizing it. And it only gets better from
there.
