:PROPERTIES:
:ID:       12564D5A-023A-499D-8A70-60A1C225306E
:SLUG:     loving-imperfection
:END:
#+filetags: :journal:
#+title: Loving imperfection

Loving what is perfect alone leads to a distaste for what is imperfect,
weakening our appreciation of life's fullness. It starts a cycle of
striving for higher perfections that broadens our sense of life's
overall imperfection. Rather than achieving what is sought, the goal
recedes further, and the world is constantly seen in a more pitiful
light than before.

However, to cherish what is imperfect connects one's nature to the
imperfection in all things, and heightens our pleasure at any sudden
glimpses of perfection. Because love of imperfection creates a general
affinity for All, which paradoxically engenders a higher perfection --
unconditional love -- in the soul. Nor is this merely acceptance: Love
implies an active awareness, an appreciation that leads to a willingness
to act.

If one loves what is imperfect he can love all things, until that love
causes them to be seen as perfect, and "perfection" as their highest
fulfillment. Just as the farmer can appreciate the value of dirt,
however much dirty it will always remain: he understands its role, its
use, its function within the scheme of bringing forth verdure and
beauty.

* A mystical practice
:PROPERTIES:
:CUSTOM_ID: a-mystical-practice
:END:
After reading "The Book of Tea", by Kakuzo Okakura, I decided to make a
mystical practice out of calligraphy. My script is rather poor in my
eyes, and I seem unable to write my words without error. Perhaps it is
just untrained motor control. So I write now, not to perfect my script,
but to allow its imperfection a chance to roam: to exist in a spirit of
admiration, for its humility and "delightful foolishness".

It is rather soothing to write poorly, when that is the intent. Not to
impress, but to allow what is, to be. The mystical paradox is that the
more I do this, the better -- through practice and awareness of my
errors -- my script becomes. From the soil of the real appear the
delicate blossoms of a transient perfection, swiftly fading into dust.
In that moment, in the one, gorgeous character on my page amidst the
ugly, is revealed a poignant reminder of the drama of life: that by
reveling in what is ordinary, the eyes are opened, and will not miss the
precious moments of the truly extraordinary.

* The falling rain
:PROPERTIES:
:CUSTOM_ID: the-falling-rain
:END:
#+BEGIN_EXAMPLE
The falling rain:
how unorchestrated in its sound,
how symphonous.
#+END_EXAMPLE
