:PROPERTIES:
:ID:       3546E620-E785-4E99-9464-97D8F35362BA
:SLUG:     smoke
:END:
#+filetags: :stories:
#+title: Smoke

There was too much smoke; everything rushed at me at once -- I hardly
had time to breath. When I reached her she was almost gone, wheezing
from inhalation. I bent down, breathing heavily into my mask, and lifted
her onto my shoulders. She weighed almost nothing, my arms told me, but
I knew it was adrenaline. The fury of flames and smoke was eating
everything in the home like a locust plague, and I was pitted against
that plague. The clock on the wall wiped another handful of moments
away.

The woman was still unconscious, but only that. With a leap we made it
through the doorway. I let her down and she crumpled against the
fire-engine's tire. I looked under her smoke-lined eyes and saw a
peaceful face, calm as a baby's. In sleep there was no inferno, no
danger. Her skin was smooth and young, and I knew that she was lovely.
Perhaps when she learns of her unlucky child there will never be peace
on that face again.

Her hair was tangled in a thick vine of chocolate brown. I could see
bits of ash stuck here and there, escaping with the wind as she moved.
Would she thank me for saving her life, or condemn me for not leaving
her with her little girl? I was tortured between wanting to see that
beautiful face dawn with life, and wishing I could undo it all, never
having been a part.
