:PROPERTIES:
:ID:       5F498083-E4AD-45A2-8EDA-093CAC8E3E5D
:SLUG:     thoughts-on-the-valley-of-unity
:END:
---
title: Thoughts on the Valley of Unity
tags: essays
---

* Qualities of the wayfarer
:PROPERTIES:
:CUSTOM_ID: qualities-of-the-wayfarer
:END:
It has been mentioned before that Bahá'u'lláh gives three qualities as
the sole requisites for fathoming the depths of divine reality: "...
purity of heart, chastity of soul, and freedom of spirit."[fn:1]

In addition, as a soul progresses, he acquires -- or discovers -- new
qualities within himself as he ascends through the veils that oppress
our discovery of Truth.

I find evidence that a soul must embody four spiritual qualities before
he can make his way through the Valley of Unity. All of these are to be
found in the Short Obligatory Prayer; they are: knowledge, devotion,
powerlessness and poverty. The obligatory prayer reads:

#+BEGIN_QUOTE
I bear witness, O my God, that Thou hast created me to know Thee and to
worship Thee. I testify, at this moment, to my powerlessness and to Thy
might, to my poverty and to Thy wealth.

There is none other God but Thee, the Help in Peril, the
Self-Subsisting.

#+END_QUOTE

These qualities are certainly meant, not in a materialistic sense, but a
spiritual one. By knowledge is meant spiritual knowledge, or insight
into divine mysteries; by devotion is meant a whole-hearted praise not
comprehended by words, but only signified by them; by poverty is meant
spiritual poverty, independent of the possession or lack of material
means; and by powerlessness, something other than the absence of mortal
sovereignty is meant.

Three out of these four qualities we have already encountered by the
time we reach the shores of the Valley of Unity. That is, in the Valley
of Search we learn about the nature of poverty, of divesting ourselves
of all things: love, hate, knowledge, "whatever he hath seen, and heard,
and understood": that we might prepare ourselves to recognize the glory
of God's Manifestation when we encounter Him.

The state of mind resulting from such poverty is one of complete
receptiveness, of extreme sensitivity to one's surroundings and to the
evidences of truth or falsehood inherent in any statement. Modern
parlance calls this "a learning mode".

In the Valley of Love, we are taught the secrets of devotion, and the
ways of a lover's hope and despair. And in the Valley of Knowledge, our
most recent field of discovery, we are educated in the varied forms and
mysteries of divine wisdom. This leaves but one quality unachieved, as
found in the daily prayer: powerlessness.

If there really is a relationship here, between our daily
acknowledgement and the course of the Valleys leading to Contentment and
Wonderment, and from thence to the supernal station of faná, it follows
that powerlessness is a spiritual quality we will find indicated in the
Valley of Unity.

Already, I have found a few intimations of this theme:

#+BEGIN_QUOTE
He seeth in himself neither name nor fame nor rank, but findeth his own
praise in praising God.

He beholdeth in his own name the name of God; to him, "all songs are
from the King," and every melody from Him.

He sitteth on the throne of "Say, all is from God," and taketh his rest
on the carpet of "There is no power or might but in God."

For thus the Master of the house hath appeared within His home, and all
the pillars of the dwelling are ashine with His light. And the action
and effect of the light are from the Light-Giver; so it is that all move
through Him and arise by His will.

How can utter nothingness gallop its steed in the field of preexistence,
or a fleeting shadow reach to the everlasting sun? The Friend hath said,
"But for Thee, we had not known Thee," and the Beloved hath said, "nor
attained Thy presence."

O thou dear one! Impoverish thyself, that thou mayest enter the high
court of riches; and humble thy body, that thou mayest drink from the
river of glory, and attain to the full meaning of the poems whereof thou
hadst asked.

#+END_QUOTE

What sort of powerlessness is this? To address that question, we must
inquire into the nature of power, and why people seek it.

Power, in its most basic form, is that which allows us to assert our
existence. Being shorn of all power -- and I mean /all/ power -- is
something we ought to be too frightened to contemplate for those
accustomed to it. Imagine having no food and being unable to find any,
with death the immediate result. Worse is the frustration of knowing
that if only we had the means, we could prevail! I think people are even
more afraid of powerlessness than they are of death, since to fail from
lack of power is one the most deeply humiliating experiences of life.

As "humiliation" is close to humility in its verbal origins, which in
turn reflects on our desire to become spiritually humble, perhaps this
degradation resulting from insufficient power -- or rather the deep
awareness of our powerlessness -- is not something to be feared, but an
aspect of spiritual growth. In one of His prayers, Bahá'u'lláh writes:

#+BEGIN_QUOTE
Behold me, then, O my God, fallen prostrate upon the dust before Thee,
confessing my powerlessness and Thine omnipotence, my poverty and Thy
wealth, mine evanescence and Thine eternity, mine utter abasement and
Thine infinite glory.[fn:2]

#+END_QUOTE

Even deeper in this vein His states:

#+BEGIN_QUOTE
He, indeed, is endued with understanding who acknowledgeth his
powerlessness and confesseth his sinfulness, for should any created
thing lay claim to any existence, when confronted with the infinite
wonders of Thy Revelation, so blasphemous a pretension would be more
heinous than any other crime in all the domains of Thine invention and
creation. Who is there, O my Lord, that, when Thou revealest the first
glimmerings of the signs of Thy transcendent sovereignty and might, hath
the power to claim for himself any existence whatever? Existence itself
is as nothing when brought face to face with the mighty and manifold
wonders of Thine incomparable Self.[fn:3]

#+END_QUOTE

We are presented here with our sheer powerlessness to assert our own
existence. How can we reconcile our horror at such a fact with its
inherent truth? I feel the resolution of this dilemma lies in the Valley
of Unity.

Unity in its essence implies an abolishment of "here" and "there",
"then" and "now", "I" and "He". To accomplish this, even the veils of
love must be burnt and cast away. At the end of the Valley of Knowledge
He quotes:

#+BEGIN_EXAMPLE
Love is a veil betwixt the lover and the loved one;
More than this I am not permitted to tell.
#+END_EXAMPLE

Unity requires that we forgo insisting on any distinct, any separate
awareness from God. So also this directly indicates a state of utter
powerlessness, since all power thus resides in God. As long we bear any
claim to power, or any wish to acquire it, we create the very separation
that bars us from realizing this essential spiritual union.

I encourage all to meditate upon your own relation to power, whether
manifested as a desire for control, or to achieve, or for the goodwill
of others, or by any other means. Then, meditate on what life would feel
like without this power, and /without any future hope of it/. If this
results in a deep, despairing loneliness, a sense of shocking futility
at the prospect of continuing, please delve into the nature of this
emptiness, and why it might exist. If you have a different reaction, I
would be interested to hear it, and what you understand from it.

In closing, consider the following prayers for meditation, which relate
poignantly to the theme of powerlessness:

#+BEGIN_QUOTE
Inspire them, O my Lord, with a sense of their own powerlessness before
Him Who is the Manifestation of Thy Self, and teach them to recognize
the poverty of their own nature in the face of the manifold tokens of
Thy self-sufficiency and riches, that they may gather together round Thy
Cause, and cling to the hem of Thy mercy, and cleave to the cord of the
good-pleasure of Thy will.[fn:4]

Glorified, immeasurably glorified art Thou, my Best-Beloved! Inasmuch as
Thou hast ordained that the utmost limit to which they who lift their
hearts to Thee can rise is the confession of their powerlessness to
enter the realms of Thy holy and transcendent unity, and that the
highest station which they who aspire to know Thee can reach is the
acknowledgment of their impotence to attain the retreats of Thy sublime
knowledge I, therefore, beseech Thee, by this very powerlessness which
is beloved of Thee, and which Thou hast decreed as the goal of them that
have reached and attained Thy court, and by the splendors of Thy
countenance that have encompassed all things, and by the energies of Thy
Will whereby the entire creation hath been generated, not to deprive
them that have set their hopes in Thee of the wonders of Thy mercy, nor
to withhold from such as have sought Thee the treasures of Thy grace.
Ignite, then, within their hearts the torch of Thy love, that its flame
may consume all else except their wondrous remembrance of Thee, and that
no trace may be left in those hearts except the gem-like evidences of
Thy most holy sovereignty, so that from the land wherein they dwell no
voice may be heard except the voice that extolleth Thy mercifulness and
might, that on the earth on which they walk no light may shine except
the light of Thy beauty, and that within every soul naught may be
discovered except the revelation of Thy countenance and the tokens of
Thy glory, that haply Thy servants may show forth only that which shall
please Thee and shall conform wholly unto Thy most potent will.[fn:5]

#+END_QUOTE

* The elusive meaning of poverty
:PROPERTIES:
:CUSTOM_ID: the-elusive-meaning-of-poverty
:END:
Bahá'u'lláh says in the seventh Valley:

#+BEGIN_QUOTE
Wherefore, if those who have come to the sea of His presence are found
to possess none of the limited things of this perishable world, whether
it be outer wealth or personal opinions, it mattereth not. For whatever
the creatures have is limited by their own limits, and whatever the True
One hath is sanctified therefrom; this utterance must be deeply pondered
that its purport may be clear. "Verily the righteous shall drink of a
winecup tempered at the camphor fountain." If the interpretation of
"camphor" become known, the true intention will be evident. This state
is that poverty of which it is said, "Poverty is My glory." And of
inward and outward poverty there is many a stage and many a meaning
which I have not thought pertinent to mention here; hence I have
reserved these for another time, dependent on what God may desire and
fate may seal.

#+END_QUOTE

As He states, poverty is a concept with many stages, and many shades of
meaning. If we stop prematurely anywhere along our road, and give in to
our conclusions, I believe we will miss out on yet deeper meanings that
could inspire us.

In fact, I see one element of poverty as exactly this shunning of
conclusions, this divesting ourselves of the belief that "we have found
our answer". Such possessions never serve us, since God forever remains
in the realm of the Unknown with respect to our limited vision. And the
Unknown is approached through poverty, not acquisition (i.e., emptying
one's cup to receive, not by filling it). Krishnamurti, a modern Indian
philosopher, wrote:

#+BEGIN_QUOTE
Most of us are rich with the things of society. What society has created
in us and what we have created in ourselves, are greed, envy, anger,
hate, jealousy, anxiety -- and with all these we are very rich. The
various religions throughout the world have preached poverty. The monk
assumes a robe, changes his name, shaves his head, enters a cell and
takes a vow of poverty and chastity; in the East he has one loin cloth,
one robe, one meal a day -- and we all respect such poverty. But those
men who have assumed the robe of poverty are still inwardly,
psychologically, rich with the things of society because they are still
seeking position and prestige; they belong to this order or that order,
this religion or that religion; they still live in the divisions of a
culture, a tradition. That is not poverty. Poverty is to be completely
free of society, though one may have a few more clothes, a few more
meals -- good God, who cares? But unfortunately in most people there is
this urge for exhibitionism.

Poverty becomes a marvellously beautiful thing when the mind is free of
society. One must become poor inwardly, for then there is no seeking, no
asking, no desire, no -- nothing! It is only this inward poverty that
can see the truth of a life in which there is no conflict at all. Such a
life is a benediction not to be found in any church or any temple.

#+END_QUOTE

In the commentary to the "Book of Five Rings" (a Japanese text by a
master swordsman in the 1500s), something similar was said most
poetically:

#+BEGIN_QUOTE
To posit "beauty" or "book" or "unicorn" or "chiliagon"[fn:6] is to have
your mind stop. To think of death when you are faced with your enemy is
to have your mind stop. This is why the swordsman must remain detached
from "worldly" thoughts... If you can rid yourself of the "stopping
mind," you will achieve Satori[fn:7], and experience the moment as if it
were your own.

#+END_QUOTE

The mind that wants ownership is the "stopping mind", whereas poverty
implies a mind who is reintroduced to the entirety of life at every
moment, reborn in every second. The present contains all realities --
was it not created by God? -- and even in the seed or the leaf there are
written all the mysteries of the tree. Poverty is a preparedness to
receive whatever inspirations God may wish to send, and to be carried by
the flow of each moment into the novelty of the next. The opposite of
poverty is wishing to stand against this flow, to own it: even if only
conceptually!: to look around and see things from the standpoint of one
who is other than they, and thus capable of ownership (and power).

Even in the comments that have been made saying "we already have
everything", I wonder about the existence of "we". There is neither
having nor not having, being nor non-being; the Japanese call this state
of dependent reality "ku". Unfortunately, such simple words are too
trite to mean much, so we must continue in our delightful, verbal dance.

So even as I write these words, I erase them from my heart. Like the
monks from Laos who create sand-paintings to their best ability, only to
throw them into the river afterwards, our wish is to be filled /in the
moment/ with a deep love of God's reality, to let all these
understandings course through us in an ever-intensifying expression of
praise and gratitude.

It is like the lover bestowing a gift on his beloved: she sees nothing
of the gift, only the fact of the giving; and thus they carry each other
away in their ship of arms to a sea that refuses any name...

#+BEGIN_QUOTE
O my friend, look upon thyself: Hadst thou not become a father nor
begotten a son, neither wouldst thou have heard these sayings. Now
forget them all, that thou mayest learn from the Master of Love in the
schoolhouse of oneness, and return unto God, and forsake the inner land
of unreality for thy true station, and dwell within the shadow of the
tree of knowledge.[fn:8]

#+END_QUOTE

[fn:1] Bahá'u'lláh, Kitáb-i-Íqán, p. 211

[fn:2] Bahá'u'lláh, Prayers and Meditations, p. 90

[fn:3] ibid, pp. 133-4

[fn:4] ibid, p. 47

[fn:5] ibid, pp. 89-90

[fn:6] a thousand-sided figure; i.e., something that could exist, but
       cannot be envisioned by the mind

[fn:7] a full enlightenment, seeing into the true nature of things

[fn:8] Seven Valleys
