:PROPERTIES:
:ID:       C9ADFCBE-C295-4703-B2A2-0A9D5BC55A37
:SLUG:     the-cause-of-joy
:END:
#+filetags: :journal:
#+title: The Cause of Joy

I have heard a sentiment from many people over the years which I would
like to respond to in a clear, concise way. It boils down to people's
feelings about the purpose of life. In many ways, I hear it said that
our goal in life lies in preparation for the future. This might mean a
life after death, the future of society, or a future state when our
higher self is perfected. Whatever the form, the essential statement is:
"The purpose of living in the present is to prepare for the future."

I think the path of joy contributes most to the well-being of mankind. I
never want a person to feel that I overlooked their present being
because I was too busy working for their future benefit. Only if people
are happy /now/ do I consider myself successful. I want a world, not of
perfection, but where people are happy. It is their souls that matter to
me, and what will uplift those souls. Can the pursuit of unattainable
perfections do this? It hasn't for me. But joy... Joy is the one thing
which, if I had naught else for all eternity, I could ask for nothing
more.

These thoughts are examined in an [[file:cause.joy][essay]] written
earlier today.
