:PROPERTIES:
:ID:       B66F62EC-8FF7-4951-B17D-77A1CDD7EFEA
:SLUG:     the-observation-station
:END:
#+filetags: :stories:
#+title: The observation station

There was a group of us in an observing station, based somewhere on the
ocean near the Florida keys. From a satellite above, encircling the
Earth somewhere out there in the eternal night of space, there was an
image visible on the radar. It was sinewy and long, roughly the shape of
a slug, and it twisted around and around like a tornado. At the same
time, it was also tracing a roughly elliptical path near one of the
islands in the Florida Keys. This path was no more than a mile long,
with the object itself possibly a quarter mile tall, and a few hundred
feet wide.

Upon closer examination, we found that the object was in fact some kind
of vortex, deep black, and it was causing objects to disappear when it
touched them. But since the area was pretty much deserted (no one wanted
to go near it), there was no real damage being done.

After we set up the observing station, we looked hard into the vortex,
and found that a strange, shimmering light was visible. As we looked
more intently, we saw that the shape represented an image, visible
beyond the vortex. It wasn't on the other side of the vortex, since
there was only water there, and the island, but it was /beyond/ the
vortex. After a while, the image became clearer, and we realized in awe
that it was a gigantic space station.

At this moment we realized that the vortex was actually a tear in space,
and that we were looking into a different part of the galaxy! The space
station was enormous, several miles in diameter, and was made of six
concentric rings that were fashioned together to make a sphere. The
rings themselves were of a dull, gray metal, with tiny lights all along
them.

There was a great sense of excitement in the observation station,
because we had discovered an alien artifact. There was no sign of life,
but it was certainly not something made by humans. So we began to try
sending probes through the vortex, to get more information.

The dream continued by skipping time in jumps. A moment later we were
several months into the project. Somehow two of our engineers had been
caught by the vortex, and carried away into the other dimension. After
several days, they were sent back. We never discovered who sent them
back, but when they came back they were not the same as before. There
were electrical implants in their bodies, as if the tissue had died and
the aliens had repaired them. This was my impression, since they were in
all other respects healthy. Perhaps falling through the vacuum of space
had caused tissue damage, and the aliens had "fixed" the humans and sent
them back. The engineers did behave a little strangely afterward, but
they continued to work with the observation group.

Our project was highly secret, and no one knew what we were doing. The
world at large thought that the vortex was simply a strange atmospheric
phenomenon, and that the government "was keeping an eye on it". Even the
government officials didn't completely believe our story. I guess no one
ever came down to check.

One day, several months into the project, there was a high-pitched,
whining noise. All of sudden I had that sense that there was another
presence among us. One of the men suddenly lurched forward and fell, and
then another was struck by something -- something invisible. As I stood
up to find out what was going on, there was another whine, and then I
felt myself hit by something... or someone? And then it was gone. The
noise stopped, and the room was silent again.

When we looked around, we guessed that we had been visited by a presence
from the alien space station. Maybe there need for physical violence was
a fear response, and they thought we might try to attack them? Anyway,
several hours after the encounter I found a pair of compact discs. They
had handwriting on them, in black marker, listing a series of dates. At
first I thought there was only one disc -- and so did everyone else --
since the second disk was stuck to the first, on the bottom. The top
disc was yellowish, and the bottom completely silver. Since the top disc
didn't contain any really interesting information, everyone disregarded
it.

Later on, perhaps a few days later, I found the second disc stuck to the
first one. This disk /did/ have some interesting details on it. It
seemed to be described certain events that would be happening soon in
Earth's future. First there would be war, and pestilence; and then a
desolation of the land, and famine; and then the oceans would begin to
rise, washing away much of the coastal land mass. Finally, 550 years
into the future, a gigantic meteor would circle round the sun, and
impact with Earth on its return journey. This would have the result of
wiping out all life on the planet.

I realized instantly that the alien civilization was trying to warn us
of what would happen in /our/ time. You see, the vortex represented not
only a rift in space, but in time as well. Looking out at the space
station, were we seeing the future. We were seeing what /would/ be
built, somewhere in our galaxy, at sometime in the remote future. And
this race of beings had historic knowledge of our destruction, and was
trying to warn us.

I immediately rushed to the heads of our government, who were in charge
of the observation project, and tried to warn them. But no one would
listen to me. Not a soul! They all laughed, and seemed ignorant of the
presence of the second disc, and for some bizarre reason would accept
that it existed. They merely disclaimed all possibility of horrible
things happening in the future, and accused me of being a doom-sayer.

Even the members of my own team thought I had lost a marble or two. I
even showed them the second disc, but they acted like they couldn't see
it. As if it didn't exist! It was there in plain sight, and I could see
by the motion of their eyes that they did indeed see it, but they acted
as though the fact of its existence would never penetrate their
consciousness.

At this point I was in utter despair, because I felt in my gut that the
alien message was true. Except it was so far into the future! I would be
long dead before the trials began to occur, and at that time who would
warn everyone? Would the meteor catch us unawares, because no one was
willing to heed the alien's warning?

And in fact, some of the trials did start happening within my lifetime.
The ocean raised by a few inches (though the meteorologists said that it
was a temporary phenomenon, and that they would recede again), and the
land started to become drier. The governments were daily becoming more
agitated with one another, and unemployment was on the rise. It looked
like the prophecies were just beginning to become true -- and I even had
the blueprints for them in my hand! -- but no one would listen to me. I
was alone in my terrible knowledge of the future.

So I just continued to study the discs, to see if there was anything I
could do. But there was not. As just one man, there was no lasting
impact I could make on the understanding of those around me.

And so the dream ended, with nothing more than a terrible sense of the
future, and of what the alien's had tried to tell us. I don't know how
it will turn out. I still don't know.
