:PROPERTIES:
:ID:       CB4FCAA4-3535-4A32-90F3-86F5B18D9EBF
:SLUG:     a-metaphor-to-describe-the-bahai-fund
:END:
#+filetags: :essays:
#+title: A metaphor to describe the Bahá'í Fund

Imagine a society quite like our own: there is a city, a power plant,
and thousands of homes and buildings. The trick is to get the power to
the people, since once it is there it can accomplish innumerable helpful
tasks.

The utility of electricity allows society to grow and develop. It
permits us to discover realities that erstwhile were hidden deep in the
bowels of nature. It reveals discoveries and inventions that continue to
amaze us with each passing year.

Yet this energy does not appear by itself. The essential properties of
electricity were created with the beginning of the universe, when all
the rudimentary forces were created. It was then that the potential for
the appearance of such a force was brought into being. But for the most
part it has lain dormant, until the conditions were just right for its
appearance in the heavens above us in the form of lightning.

Men quickly acknowledged the transformative power of this force, and set
about learning how to harness it. It was at about this time that a
brilliant architect stepped forth, who devised plans and set forth
projects providing a means whereby this energy could be channeled and
put to use by the people.

But the people were completely in control of the material resources. The
architect and his fellow supporters were only a meager band, scorned and
misunderstood. The people-who had never witnessed the power of
electricity, except for some flashing lights-laughed at the idea that
machines could be devised that operated without the need for human
intervention.

Ultimately, however, the architect won the support of a small band of
followers, who were open enough to give his ideas a chance. Through the
aid of demonstration and example, they came to realize what a tremendous
potential this idea portended for the city at large. And so they set
about trying to communicate these ideas to others in a fashion that was
compatible with the ways and understanding of the people.

Gradually there arose a significant enough number of individuals to
champion the architect's cause. Of course it was still very minor in
comparison to the city's population, but it was enough for the
architect's "disciples" to take heart.

In the meantime, the architect had already begun producing electricity
and refining the plant. He had started this project even before there
were any supporters, because he knew the day would come when the entire
city would want the benefit of electric power, and that the plant would
have to be capable enough on that day-or else what was the benefit? So
in order to achieve this, development work had begun right away. It
would still be several years before the plant would be able to output
energy in sufficient amounts.

And so he began, putting faith in his disciples to accomplish what they
had to by the time the plant would be ready.

As more and more people joined the "faith" of this architect (as they
called it), they discovered that he knew much more than just how to make
generators: he also knew how to design a cabling system that would
canalize this potent energy into every part of the city. Yet to make
real his design, a great quantity of copper was needed in order to build
the cables.

Coincidentally enough, the coinage of this particular country was made
of copper. Copper coins-just the substance the architect needed to
fulfill his designs-were to be found everywhere, in the hands and
pockets of the people.

Now in the interim-because a great deal of time had passed-the original
architect passed away, but had left plans suitable enough for a
committee to follow them. It then elected sub-committees, and further
sub-committees, and so on, until there was enough infrastructure for the
"Company of the Faithful" to ensure that the work would go on.

This Company discovered that everything necessary had been planned out
in advance by the Architect (they now capitalized His name out of
respect, including all pronouns referring to Him). All they needed was
the copper.

As it became necessary, they grew the number of committees and
territories to include the ever-growing numbers of the faithful. Yet it
finally all boiled down to a question of copper: without it, despite the
best of intentions, who would lay the cables that would fulfill the
final objectives of His Grand Design? This simple metal would make
possible the groundwork that He foretold would precede the coming of the
Most Great Society-a society wherein every person would use electricity
to accomplish his task, and no one would be forced to toil in the fields
any longer like beasts of burden. All that was needed was copper; that
and the ongoing endeavors of the faithful to educate more and more
people about the Plan.

Campaigns were begun, and literature was produced by the thousands. It
seemed that the growing body of followers needed only a push-yet they
seemed somehow resentful of the constant reminders. "Why keep telling us
about the need for copper?" they said. "Isn't copper just a plain,
material thing? Too many people are already interested in copper. After
all, energy is the main thing. That's what it's all about."

And, "yes, that is what it's all about," the Company would say, "but how
can we offer this Most Precious Elixir if there doesn't exist a means to
transport it? Immaterial things require material vehicles. One cannot
carry water in his hands; it requires a vessel."

And they responded, "Yes, yes, we understand you. Forgive us. Here is
more copper. Now please leave us to meditate further on this Most
Wonderful Capacity. It is truly quite amazing! Think of all the things
we can do!"

It wasn't difficult to get people excited about the as-yet-unrealized
potentialities lying hidden, latent in the force of electricity. It was
more a question of how the Company was to fulfill the original dream of
the Architect: that of bringing unlimited quantities of energy to every
part of the globe.

Without copper-which was now being called the "life-blood" of the
Company's cause, since without it the work of the Company simply came to
a halt-the Architect's final plans, the most glorious stage of His
design, would be difficult to bring into fruition. It simply needed more
copper.

And so they laid out the cables furiously, these workers for the
Company, and some even gave their lives, spending their very last days
in the remotest parts of the earth. The Company received enough copper
to continue, but it was feeling the pangs of short supply. The arteries
had been squeezed tight, and its life-blood was now eking its way
through an ever-closing aperture. This, perhaps, is why copper was
referred to as a life-blood: because the degree of its availability was
directly related to the general availability of the Precious Substance
itself, which was the reason why this whole endeavor had begun in the
first place.

Yet even the Precious Substance was not the final goal. This was simply
a means to make possible the further realization of the potentialities
that lay hid in the society. The Creator had created man in order that
he might carry forward "an ever-advancing civilization". This
civilization had attained a certain degree of development in its last
six thousand years, but now was the time for a quantum leap: a leap that
would change the course of mankind forever. And the ultimate goal of
that change was a thing requiring the deepest contemplation. It deals
with the very purpose of life-the story behind the story-and that,
unfortunately, must be told another day. But to continue: the pioneers,
as they were called, had extended the Company's network around the
entire planet: even if this meant only a single wire stretched all the
way from the seat of the Company (in Israel, of all places), to the
furthermost reaches of the Antipodes. The pioneers sent back word saying
that the people were ready for more, and were poised to put this awesome
force to greater use, but that they needed more copper to do so. Those
wires took a lot of copper, after all.

So now it comes to today. Those things that the Architect foresaw a
hundred years ago are becoming manifest before our very eyes. The
Company is poised to make a critical move that will usher in the New
Society-one freed from all the hindrances of the past. This society will
base its very functioning on that Essential Force, and will discover to
a greater extent the reason why all these things were brought into
being. It seems dream-like, but somehow this new future promises to
bring to us an end to war, the equality of peoples, and the coming
together of all the other Companies in the world, who in their time had
introduced technologies just as revolutionary and useful, and just as
hard to establish in the hearts of men.

It only rests on us to offer the bricks that will build this building-
the copper that will thicken those cables until they carry the torrents
of spiritual energy required to fulfill His Great Design. What it will
look like in that distant future we can only dimly foresee, but what it
has done for us so far is enough to instill anyone with hope.

Millions of feet to lay, and the smelter is running low... And now a
budget in the U.S. of $27 million units in 1997 alone! Amazing! But what
an effect it will produce if we can muster the will to see it happen...
