:PROPERTIES:
:ID:       5DDF99D2-79BA-43D9-B85D-7A9361DA93A2
:SLUG:     duty-and-recognition
:END:
#+filetags: :essays:
#+title: Duty and recognition

What does it means to have a duty to recognize God's Messenger?

If I told you there were things about astronomy you did not know, it's
pretty easy for an honest person to recognize that indeed, you do not
know them. Perhaps it might require a little proof, but ignorance is
easily uncovered by the willing seeker.

Let's say you want to be an astronaut. I claim it's your duty to
familiarize yourself with those details of astronomy, otherwise there's
no chance of your heading into space -- or at least, you'd have to be
extremely lucky (blessed?) to reach where you wanted to go.

Bahá'u'lláh tells us that God's creation is ordered according to
spiritual laws, and that our own reality, being spiritual in nature,
cannot grow or become fulfilled except through acting within the sphere
of those laws.

Thus it is the duty of anyone who wishes to become a servant of God, to
recognize the fact of his own nature, and that no truth he finds is
genuine unless it be encountered within the confines of His Law (of
which there are both general and specific aspects).

The analogy does go further, since it's quite possible for someone to
obey a physical law without understanding it. But the /perfection/ of
nature cannot be unveiled without close attention to the laws governing
it. It's one thing to discover fire; it's another to reach out bodily
toward the heavens.

So while God's grace is liberally diffused over all human kind, and no
one is threatened by extinction (according to my reading), it is another
question entirely who will make the choice to plumb the hidden Depths.

To sum: A student who would attend a school must realize that his
teachers are there to teach, and he is there to learn. Thus a
recognition of station takes place, followed by an obedience of the laws
existing between those two spheres of being. Ignoring that duty leads to
expulsion from the school (albeit, not from life, or from trying again).
So if we wish to be heedless beings, it is our choice. But there is Door
waiting to be opened, a door whose key one must turn with the hand of
endeavor, and not just a hopeful wish.
