:PROPERTIES:
:ID:       F8C8EA9F-2EDE-480C-BC1B-2640A275BC06
:SLUG:     property-and-prosperity
:END:
#+filetags: :essays:
#+title: Property and prosperity

If I walk into a computer store and pick up a laptop, without paying for
it, someone will try to stop me before I leave. If I ignore them, they
will call on additional force. This interaction will continue to
escalate until sufficient force is brought to bear, and I am stopped.

However, If I walk into the same computer store, put down two thousand
dollars, and then walk out, nothing will happen. In this case, the
computer is publically viewed as my "property", and no one will stop me.
In addition, if someone else tries to take that computer from me, I can
bring the same forces to bear to stop them.

These "forces" are continually applied until the problem is solved. At
first it may be the store clerk, then rented security, then the police,
and ultimately the national guard if I choose to encamp myself with a
group of followers. The same forces will work for me in reverse, if
someone tries to steal my property.

So in a sense, property has nothing to do with the object I purchase.
Instead, capital, of which property is just a physical part, is a
contract between the powers of our nation and myself. By carrying two
thousand dollars to the computer store, I am "renting" our national
might to prevent the computer store from ripping me off, or anyone else
from stopping me during this legal transaction.

Then even as I sit here in my house, none of this is mine. Merely, there
is understanding between me, the people around me, and our government,
that the necessary forces will be brought to bear if anyone violates the
property lines that have been drawn. Looked at it this way, it is a
rather precarious arrangement, continually dependent on mutual assurance
and belief.

This arrangement is also directly related to the strength of our nation,
and its willingness to pursue vindication after acts of wrong-doing.
With a very strong government, no act of violation will go unseen, and
the notion of property is both fiercely defended and defined. With a
weak government, who hasn't the resources or focus to pursue every
instance, it requires social goodwill to maintain any notion of property
at all.

In our country, the government is strong and the corporations are
strong. The corporations, in their pursuit for continued existence, want
the ideal of property very well guarded, and so they willingly help the
government to be stronger. Government, in its turn, recognizes the
benefit of this mutual relationship, and responds by helping create an
environment where corporations can thrive.

When it comes to property, and protecting my personal and emotional
investments in society, this is a good thing. The stronger the companies
and government are, the less likely it is that anyone will trespass on
my property -- that is, any property which falls under the protection
arrangement I paid for. If the definition of property becomes more
strict (as it does sometimes when laws change), I may find that my
ownership has grown stronger, but smaller in scope.

Yet going back to the idea that ownership is really "renting the forces
of government", I find that this is the basis of my relationship with
our government. Government exists to promote the social welfare, which
means creating a place where everyone can pursue their own ends in
harmony. It restricts liberty wherever such liberty would cause a loss
of freedom to others.

Nor is government a heaven-sent entity that existed before me, will
exist after me, and nothing can be done about it. Our government was
created by people very much like myself, who saw a need for establishing
standards of agreement, and ensuring they would not be violated.
Property is one of these standards, as it gives people a wide berth to
act and consume resources, without forever concerning themselves with
threats from outside.

However, our culture has progressed (or digressed) since that time to a
state of extreme materialism. Our society seeks to promote material
welfare to the exclusion of all else. The is epitomized in companies,
whose growth and development depends on material acquisition. For them,
the "bottom line" is the only defining reality, and everything else is
subservient to this end. Such may not be the case for me personally, or
for others, but it will always be for them as they are currently
constructed.

A company's bottom line is determined by their customers, the increase
of whose desire is their main reason for growth. Thus, at some point, I
ceased to be a human being to them. I became only a customer, a
demographic; and whatever they can do to increase my thirst and need for
their product or service, is in their best interest.

To this end, the media and its machinery have begun to perceive me as an
economic unit, rather than a person. This goes far to justify many of
the practices we see today. Take sexual attraction, for example. It is a
natural and powerful agent for motivating people. Companies see the
compelling nature of this agent, and have exploited it to make me a more
eager and regularly spending consumer. Gone is the thought that perhaps
I do not want my life dominated by sexual impulses; absent is the
concept that perhaps I don't want their product, or that advertisers
should leave me alone. I am but a unit of currency in their forecasts,
and both media and government (who is intimately linked to the
corporations) have begun to believe this.

What we need to change is not the existence or role of our corporations
and governments. They are strong, and serve us in some ways, such as
guarding property, very well. What is lacking is the human element, and
the pursuit of a higher ideal than property and materiality. In such a
world, spamming could have no place, because spamming assumes a
fundamental disinterest in the one being sold to. What we need is a
realignment of our excellent structures toward a higher social ideal,
rather than a mere restructuring.

This is something I believe communities are indeed perfect for. By
collaborating together to achieve a sense of who we are, and what we
want to achieve as a civilization, we can /en masse/ influence our
government, and use this influence to chastise the corporations, who
have become like economic tyrants. But this cannot happen constructively
without a common, positive vision for the future. Anarchy is not the
solution, for along with the evils we see today, it would dissolve many
of the goods that have come from the structures that currently prevail.

The situation we are living with now is not unlike that of a rich man
with no aim in life. Which course will he choose, but the one most
readily apparent? And if those arise who are indifferent to his view,
they are swept aside by the force of his resources. Isn't this what is
happening now? Some of us cherish freedom, and see potential for the
human mind to grow along paths undreamt of. We can achieve far more than
the mere economic security we've established so far. But our powerful
organizations, which we have each and all created by our effort and
cooperation, are defining their own goals now, leaving us by the
wayside, causing us to wonder at all of the lawsuits, patent abuses,
advertising methodologies, etc. By failing to understand and express our
own vision for the future, we have left these behemoths to pursue their
own, most facile course.

The solution, as I see it, is not merely the creation of communities as
an antithesis to government and big business. They should be a place for
us to converse openly, freely, on the topic of our common future. Once
this is done, and we realize the necessity for change, and the
requirement for plans to help us accomplish this goal, our aspirations
can make their way through government to the powers that be, and as a
collective whole we will begin our ascent to a new level of social
well-being.

In short, what we have now is good, it is only misdirected; and this
lack of direction has encouraged the discord we see around us, as if a
room of powerful robots had been left without a plan. Let us come
together, and by so doing scatter these forces of confusion, for only
such a union can bring about the evolution we need, rather than mere
revolutions, whose historical short-sightedness have only continued the
problem under different guises and using different names.
