:PROPERTIES:
:ID:       13E5D303-A902-48CB-BE8F-C1D57BE3DBCB
:SLUG:     thoughts-of-march
:END:
#+filetags: :journal:
#+title: Thoughts of March

The Fast has reached its end. What an interesting month it's been, with
hard moments intense enough to make me sick, and high points so
glorious, they chased away all awareness of time. I think the
predominant theme of this month has been that of a humbling
self-education. I am not who I thought I was at the beginning of this
month. And yet, though I come away with a sharper understanding of my
imperfections, at the same time I bear a higher appreciation of their
beauty.

In beholding the magnitude of my flaws with a new perspective, I realize
that I can never make any real headway against them within one lifetime.
Even if I spent all my life's energy on just one, I would be worsening a
host of others due to a lopsided focus. This being the way of things
completely changes my private goals. Becoming perfect is no longer a
hopeful dream. In those terms, I'm screwed. Life /must/ be about
something other, or Someone other, Whose nature is able to satisfy my
soul's craving for perfection. Even what I identify as my imperfections
are only such in the context of the company I keep. I cannot even
perfect a knowledge of my imperfections! The whole bubble must be left
to burst, being as it is both empty and insubstantial -- and thus
unworthy of attention.

To what, then, do I direct the labors of my life? Perhaps earlier
entries have already pointed the way. For there /is/ one thing, having
nothing to do with me or my imperfections, that has the capacity to
satisfy me -- insofar as I perceive it. I have called it many names:
such as Quality, perfection, God. If this truly is the goal, then the
only requirements for living rightly are the steps that take me there.

[[file:qalam]]
