:PROPERTIES:
:ID:       20A6D3C7-C630-4788-BAD7-35DFBA4675E1
:SLUG:     the-concept-of-self-and-the-kitab-i-iqan
:END:
#+filetags: :essays:
#+title: The concept of self and the Kitáb-i-Íqán

The word "self" is used in different contexts in the Bahá'í Writings.
Its most common use when not capitalized, and excepting for certain
instances, is definitely negative:

- the satanic self
- the darkened self
- the prison-cage of self
- the shadows of the valley of self
- this fire of self
- the Satan of self
- the tomb of self
- the idol of self
- the bondage of self
- the veil of self
- the treacherous hand of self
- the dust of self
- the wall of self
- the clay of self

Where the self is mentioned positively, it is almost always qualified:

- his inmost true self
- thy proper self
- the higher self

And in the first of the Four Valleys, Bahá'u'lláh describes a view of
self which is not negative at all:

#+BEGIN_QUOTE
On this plane, the self is not rejected but beloved; it is well-pleasing
and not to be shunned.

#+END_QUOTE

How are we to understand all these different uses of self, some of which
seem contradictory? If Bahá'u'lláh truly applies different meanings in
different places to the same word, how can we ever know which meaning is
intended?

It is my assertion that self has two basic meanings that are related,
yet differ fundamentally in degree. Further, that the Seven Valleys is a
manual teaching us how to progress from the lower degree of self to the
higher, while the Kitáb-i-Íqán is a historical exposition of this
difference with respect to the Manifestations of God.[fn:1]

The meaning of the two selves, and their relationship one to the other,
is summarized in the following statement from Bahá'u'lláh:

#+BEGIN_QUOTE
Know verily that whenever this Youth turneth His eyes towards His own
self, he findeth it the most insignificant of all creation. When He
contemplates, however, the bright effulgences He hath been empowered to
manifest, lo, that self is transfigured before Him into a sovereign
Potency permeating the essence of all things visible and invisible.
Glory be to Him Who, through the power of truth, hath sent down the
Manifestation of His own Self and entrusted Him with His message unto
all mankind.[fn:2]

#+END_QUOTE

Here we find that Bahá'u'lláh, when considering His "own self" (in the
possessive), "findeth it the most insignificant of all creation".
However, when He contemplates the higher realities of His nature, "that
self is transfigured before Him" and is seen as "the Manifestation of
His [God's] own Self".

What is this lower self, and what form of contemplation leads to such a
transfiguration, that what seemed the most insignificant thing in all of
creation now appears to Bahá'u'lláh as the Manifestation of God's own
Self?

I believe the Kitáb-i-Íqán represents an explication of this theme. In
it, Bahá'u'lláh repeatedly asks of the people who deny the
Manifestations, "What could have been the reason for such denial and
avoidance on their part?" This question is repeated several times
throughout the text, interleaved with descriptions of the historical
sufferings of the various Manifestations of God. One particular
discussion culminates with the well-known analogy of the Sun:

#+BEGIN_QUOTE
Consider the sun. Were it to say now, "I am the sun of yesterday," it
would speak the truth. And should it, bearing the sequence of time in
mind, claim to be other than that sun, it still would speak the truth.
In like manner, if it be said that all the days are but one and the
same, it is correct and true. And if it be said, with respect to their
particular names and designations, that they differ, that again is true.
For though they are the same, yet one doth recognize in each a separate
designation, a specific attribute, a particular character. Conceive
accordingly the distinction, variation, and unity characteristic of the
various Manifestations of holiness, that thou mayest comprehend the
allusions made by the creator of all names and attributes to the
mysteries of distinction and unity, and discover the answer to thy
question as to why that everlasting Beauty should have, at sundry times,
called Himself by different names and titles.[fn:3]

#+END_QUOTE

Here He compares the particular, daily appearances of the sun with the
sun's constant, enduring reality. That is, the sun which rises on a
particular day has a certain name, and a certain designation within the
Zodiac; but this plurality does not mean that there are multiple suns.
The reality of the sun is one, although it can be seen to manifest
itself from different places on the horizon, and is referred to by
different names.

In like manner, the Manifestations of the Sun of Reality, although they
appear in the garment of a human frame, and manifest signs of
distinction, are in truth independent of this distinction, and all sit
upon the same throne of Unity. This distinction should be very familiar
to most Bahá'ís, and can be read about in more detail by perusing the
Íqán. But what does this have to do with selfhood, and the Seven
Valleys?

The analogy of the sun shows in very plain terms the difference between
the immanent and the transcendent, to borrow terminology from modern
philosophy. The immanent is what appears to us in the moment, in its
present form; the transcendent is what the immanent "refers to", or
implies by its being. All of the Manifestations of God, as they appeared
to humanity, were without a doubt distinct and different people; that
is, their immanent form was of a particular man from a particular
village, speaking whatever language was common. Yet the essence of those
Beings was something utterly beyond their appearance. Whatever they
seemed to be, they were something far greater. This greatness could only
be hinted at, or demonstrated through signs, but not seen directly since
it does not appear as immanent.

Through understanding and recognition of signs, some are able to
transcend the experiences of eyes and ears, and become aware that These
are not ordinary beings as They seem, but Rays of a Sun whose brilliance
we cannot imagine. This higher station of Theirs is not obvious, and yet
it is Their true Reality; it is far more real than the physical Beings
Who walked among us. What is this thing which is not obvious to our
senses, yet is more real than what senses are capable of? Such is the
nature of the transcendent.

To go back to the analogy of the Sun: every day has a particular name on
the calendar; this is how we known each day in its immanence. There is
no "nameless day", no "ideal day". Every day is a day of a particular
name, be it Monday, Tuesday, etc. By looking at the reality of Monday
and Tuesday, we notice that each of these refers to a another, more
constant reality. That is, every day of the week shares certain
qualities with every other day. By applying our understanding, we can
transcend our awareness of each day as particular and distinct, and
become aware of another reality we call "day". We transcend the
particular toward the abstract. However, this abstraction is not just a
name; "day" is a very real concept, and each particular day contributes
to the reality of that concept. We can look at today and say, "This is
not Tuesday, it is Monday", and at the same time say, "This is Monday,
which is a day just like Tuesday". In the first instance we consider the
two days in their separation, while in the second we see their
transcendent union with all the other days.

Given these terms, we can now define "self" more precisely: self, as
negatively referred to in the Writings, is our immanent self, our
particular self. It is the self which has a name, and is distinct from
every other self. In this station, we are separate from others; we can
look at someone and say, "That is not me". We can also prioritize the
desires of our self above those of the selves of others, since the
desires of others will not aid our own self.

Just as with the Manifestations of God, there is also a "higher self"
that we all participate in, a station by which all human reality is
essentially united: the transcendent self. In this station, we are all
leaves of the same tree, rays of the same Sun, flowers of the same
garden. The desires of another are coequal with my own desires, since
they are the desires of one reality. It does not matter, for example, if
"I" perform a certain service, or "another" does it; in both cases in is
"a servant" who has performed it, and since this is the transcendent
reality of human beings, in fact there is no difference in who did it.
Ego does not have authority on this plane, nor can it claim anything for
itself.

When one's vision accomplishes this transcendence, he is now aware of
Divine Unity, a station depicted again and again in the Seven Valleys.
It is in this station that we see the Manifestations of God as one,
their Reality as one, their Being as one:

#+BEGIN_QUOTE
It is clear and evident to thee that all the Prophets are the Temples of
the Cause of God, Who have appeared clothed in divers attire. If thou
wilt observe with discriminating eyes, thou wilt behold them all abiding
in the same tabernacle, soaring in the same heaven, seated upon the same
throne, uttering the same speech, and proclaiming the same Faith. Such
is the unity of those Essences of being, those Luminaries of infinite
and immeasurable splendour.[fn:4]

#+END_QUOTE

He states this idea even more directly in the following passage:

#+BEGIN_QUOTE
From these statements therefore it hath been made evident and manifest
that should a Soul in the "End that knoweth no end" be made manifest,
and arise to proclaim and uphold a Cause which in "the Beginning that
hath no beginning" another Soul had proclaimed and upheld, it can be
truly declared of Him Who is the Last and of Him Who was the First that
they are one and the same, inasmuch as both are the Exponents of one and
the same Cause. For this reason, hath the Point of the Bayán -- may the
life of all else but Him be His sacrifice! -- likened the Manifestations
of God unto the sun which, though it rise from the "Beginning that hath
no beginning" until the "End that knoweth no end," is none the less the
same sun. Now, wert thou to say that this sun is the former sun, thou
speakest the truth; and if thou sayest that this sun is the "return" of
that sun, thou also speakest the truth. Likewise, from this statement it
is made evident that the term "last" is applicable to the "first," and
the term "first" applicable to the "last;" inasmuch as both the "first"
and the "last" have risen to proclaim one and the same Faith.[fn:5]

#+END_QUOTE

In the Seven Valleys, Bahá'u'lláh uses the metaphor of color and light
to describe the fundamental difference between the immanent and the
transcendent. In His example, the immanence of particular colors refers
to the light which shines upon material objects. Were man to comprehend
the meaning of unity, he would look at the colored objects and see not
just the colors, but the sun from which they derive their color and for
which they exist as evidence. In order to see this truth we must
"transcend" the difference of individual colors, and, through faith and
understanding, see the reality of the sun these colors represent and
reveal:

#+BEGIN_QUOTE
... colors become visible in every object according to the nature of
that object. For instance, in a yellow globe, the rays shine yellow; in
a white the rays are white; and in a red, the red rays are manifest.
Then these variations are from the object, not from the shining light.
And if a place be shut away from the light, as by walls or a roof, it
will be entirely bereft of the splendor of the light, nor will the sun
shine thereon...[fn:6]

Thus when the wayfarer gazeth only upon the place of appearance -- that
is, when he seeth only the many-colored globes -- he beholdeth yellow
and red and white; hence it is that conflict hath prevailed among the
creatures, and a darksome dust from limited souls hath hid the world.
And some do gaze upon the effulgence of the light; and some have drunk
of the wine of oneness and these see nothing but the sun itself.[fn:7]

#+END_QUOTE

In the Seven Valleys, this example is given to describe the nature of
those who journey in the Valley of Unity. Yet it is awfully similar to
the analogies given previously in the Kitáb-i-Íqán. In fact, Bahá'u'lláh
ties the two together when He says:

#+BEGIN_QUOTE
Yea, these mentionings that have been made of the grades of knowledge
relate to the knowledge of the Manifestations of that Sun of Reality,
which casteth Its light upon the Mirrors.

#+END_QUOTE

The "grades of knowledge" are the levels of understanding from which we
view the realities of the world. Were men to forgo the attraction of the
immanent for the virtue of the transcendent, and not allow the beguiling
nature of differences to distract him, he would in every age have
recognized the Manifestation of God by His signs, rather than expecting
someone of his own fancy. Because men are so attracted to titles of
distinction, "a darksome dust from limited souls hath hid the world",
and thus the underlying unity of all things, and especially the unity of
the Manifestations of God, has remained a very difficult concept to
grasp.

#+BEGIN_QUOTE
Thus it is that certain invalid souls have confined the lands of
knowledge within the wall of self and passion, and clouded them with
ignorance and blindness, and have been veiled from the light of the
mystic sun and the mysteries of the Eternal Beloved; they have strayed
afar from the jewelled wisdom of the lucid Faith of the Lord of
Messengers, have been shut out of the sanctuary of the All-Beauteous
One, and banished from the Ka'bih of splendor. Such is the worth of the
people of this age![fn:8]

For some there are who dwell upon the plane of oneness and speak of that
world, and some inhabit the realms of limitation, and some the grades of
self, while others are completely veiled. Thus do the ignorant people of
the day, who have no portion of the radiance of Divine Beauty, make
certain claims, and in every age and cycle inflict on the people of the
sea of oneness what they themselves deserve.[fn:9]

#+END_QUOTE

These proofs, then, relate not only to our acceptance and rejection of
the Manifestations of God, but also to how we view our own reality. Just
as the station of God's Messengers is that of Lordship, Dominion and
Authority, our station is one of servitude, humility and obedience. As
the Manifestations are all One with respect to their True Reality, so we
are all one with respect to ours. The Writings are replete with
references to this theme.

Looking at ourselves in this light, it is plain that conflict can exist
only between our lower selves, since with respect to our higher self we
all serve the same purpose, and aim at the same goal. Distinction and
contradiction can occur between colors, but not within light. Lanterns
may vary with respect to size, shape, design, etc., but not in respect
to their function and purpose.

Human reality is no different, and the Seven Valleys depicts a
progression of human understanding from perceiving the world in its
immanence, to discovering the transcendent realities implied in that
immanence. By this progression we come first to recognize our goal, then
to see how our lower self obscures that goal, then to surrender of that
self, then flee from our self and discover unity, and finally to abandon
the self and exist on the plane of oneness:

#+BEGIN_QUOTE
And when thou hast attained this highest station and come to this
mightiest plane, then shalt thou gaze on the Beloved, and forget all
else.

#+BEGIN_QUOTE
The Beloved shineth on gate and wall Without a veil, O men of vision.

#+END_QUOTE

Now hast thou abandoned the drop of life and come to the sea of the
Life-Bestower.[fn:10]

#+END_QUOTE

Notice again the distinction between "drop", a unique isolation of
water, and "ocean", which is an undifferentiated agglomeration of water.
We abandon the drop by letting go of our confined self, "the wall of
self", "the prison of self", "the bondage of self", and merge with the
ocean of His Will, Who is the creator of our true reality.

Reading further, it also appears that "self" and "soul" are distinct
realities, and that the soul can choose to align itself with either the
limited self, or its unlimited Creator. In "Summons of the Lord of
Hosts," Bahá'u'lláh writes:

#+BEGIN_QUOTE
Know also that the soul is endowed with two wings: should it soar in the
atmosphere of love and contentment, then it will be related to the
All-Merciful, and should it fly in the atmosphere of self and desire,
then it will pertain to the Evil one; may God shield and protect us and
protect you therefrom, O ye who perceive! Should the soul become ignited
with the fire of the love of God, it is called benevolent and pleasing
unto God, but should it be consumed with the fire of passion, it is
known as the concupiscent soul. Thus have We expounded this subject for
thee that thou mayest obtain a clear understanding.[fn:11]

#+END_QUOTE

This shows that the soul is not the self, and that the soul can choose
to relate itself either with its Creator and His attributes, or with the
lower self and its desires. As with a lamp, the soul can identify its
reality with the iron of the individual lantern, or with the universal
attributes of light that shine from it. Whichever it favors will gain
the greater strength, and eventually come to overpower the other.

When the soul makes this higher choice, and favors absorption in the
Divine over independent selfhood, what becomes of the self? Is it
destroyed, eliminated? Or is its relationship within the scheme of
things merely set to rights? Perhaps, instead of obliteration, oblivion
would be a better word. That is, the self does not become "nothing" in
itself, but with respect to our regard for it, it becomes "as nothing"
in the sense of that our soul now identifies with God and the
universality of His attributes, rather than the lower orders of Creation
and their separate qualities. Perhaps an analogy will help to clarify
this:

Soil is a very rich substance, able to impart life. The tree that grows
from it gives us the food we eat. In this sense, the tree cannot exist
without the richness of the soil.

Let us consider that the nature of our lower self is like this soil. It
has a certain richness, and is filled with potential. However, it alone
cannot feed others. The lower self is needed to beget the tree, but it
is God's grace that provides the seed and makes the tree.

Now the soul is related to both our selves, the soil and the tree; if it
focuses on the bounty of the tree, it sees the soil merely as a servant,
worthy of respect and care, but not deserving of any special attention
during the harvest. Once the harvest is made, the needs of the soil are
once again cared for, so that it may continue to be fertile.

If the soul focuses upon the richness of the soil, however, it considers
itself the "author" of the tree, or the one responsible for everyone's
gain. It claims for itself the rights of bounty, and strives to view its
fertility as coequal with God's powers of creation. And yet, sadly, this
attitude only causes it to dry up and cease to be productive.

In this sense, the independence of the soil to create is a complete
illusion, and can lead it to flights of vanity which are entirely
unjustified. Compared to the beauty of the trees and flowers, soil
should be like a humble servant. It has a wonderful role to play in the
growth of creation, but it is only the custodian of the higher powers
that have been placed within it as a trust; in itself it is powerless.

When we let go of seeking to attribute powers to the soil, we allow God
to do his work with it, adding sunlight and rain, and casting His seeds
over it. In fact, soil works best when it does nothing at all (in
respect to its relationship with the seed). It is poverty itself without
the seed, mere dust; it is powerlessness itself compared to the seed's
ability to grow. However, at the same time it is the matrix of the seed,
and, conjoined with the seed's capacity to grow, serves it in ways
entirely necessary for the tree to flower.

What results from the soil's service to the seed is a far more beautiful
reality than the filthy, yet honorable, soil. The tree stands proud
beneath the sun, gathers the rays of that sun, and strives to grow
toward the sun. It yields fruits and flowers that can feed the many, and
continue the process of fruition.

But does even the tree merit individual recognition? We do not love the
tree for itself, but rather for the attributes it reveals: the ability
to sustain life, its beauty. These attributes are universal among all
fruit-bearing trees, and we love them all equally for exactly that
reason. A rose in the East smells just as sweet as one in the West.

So humanity, in all its uniqueness and individuality, carpets the earth
in a mantle of fecundity, awaiting the seeds of God's grace to shower
down upon its soil. If we relinquish our own will, and do not strive
against the Divine Pattern, bountiful trees can come forth. In this
second life we are all coequal; although there is distinction in color,
shape, variety, at the same time there is unity of virtue, objective,
purpose. We are able to feed the many only when our lower selves exist
as servants to the higher self, which itself is not "ours" but a
manifestation of the attributes of God. Viewing the world through this
lens, we see the soil in its role, rather than identifying our soul with
it. Rather, the soul participates in a grand, never-ending struggle
toward the Divine, in which any form of identification acts as
hindrance.

The process of this coming forth of the higher from the lower -- or
rather, the discovery of the higher by the renunciation of the lower --
reveals God's attribute of "Creator". Were it not for this creation, how
could we understand His ability to create beauty from nothingness? Our
lower selves receive the potency of His Will, and are given a chance to
cooperate in the manifestation of a higher reality. The illusion is that
we do any of this, or deserve any individual praise for it, or that our
reality is in any way truly distinct or superior to another's. When we
see this, we transcend our belief in exclusivity, and enter the realm of
the inclusive: we leave behind lack and experience abundance: we let go
of the confining space of the drop -- whose essence is still water --
and merge with His mighty Sea.

If this analogy bears any resemblance to truth, it is clear that the
self is not evil, or to be shunned, but merely that it has a particular
place in the scheme of reality -- and this place is not as the throne of
the soul. The self is an abject, abased reality in comparison to God;
yet, in relation to the operation of God's will, it assumes the
respectable nature of serving as a foundation for our aspirations
God-ward.

A letter written on behalf of the Guardian clarifies this notion of self
further:

#+BEGIN_QUOTE
Regarding the questions you asked: Self has really two meanings, or is
used in two senses, in the Bahá'í writings: one is self, the identity of
the individual created by God. This is the self mentioned in such
passages as "he hath known God who hath known himself etc.". The other
self is the ego, the dark, animalistic heritage each one of us has, the
lower nature that can develop into a monster of selfishness, brutality,
lust and so on. It is this self we must struggle against, or this side
of our natures, in order to strengthen and free the spirit within us and
help it to attain perfection.

Self-sacrifice means to subordinate this lower nature and its desires to
the more godly and noble side of ourselves. Ultimately, in its highest
sense, self-sacrifice means to give our will and our all to God to do
with as He pleases. Then He purifies and glorifies our true self until
it becomes a shining and wonderful reality.[fn:12]

#+END_QUOTE

Hence it is that we "free" ourselves from the lower self, and
"subordinate" it to our more godly and noble side. The self, like the
soil, is not to be reviled or destroyed; rather, it assumes its proper
place in relation to the Grand Design of the Tree, nor does it seek to
excel it. We are created to be loving servants of all, and it is in the
fulfillment of this role that we find our perfection, when all aspects
of our being work in harmony toward one Goal.

The above is one view of how the self is variously referred to in the
Writings, and its connection with the Kitáb-i-Íqán and the stages
depicted in the Seven Valleys. It shows also how our understanding of
the unity and distinction among the Manifestations of God might be
suggestive of a far more universal theme -- one perhaps hinting at the
very underpinnings of reality.

[fn:1] The text, Gems of Divine Mysteries (Javáhiru'l-Asrár), ties
       together these two presentations into a more united form,
       although demonstrating this in English will await a future
       translation.

[fn:2] Gleanings, p. 102

[fn:3] Kitáb-i-Íqán, pp. 21-2

[fn:4] ibid, pp. 153-4

[fn:5] ibid, p. 161

[fn:6] Seven Valleys, p. 19

[fn:7] ibid, pp. 20-1

[fn:8] ibid, pp. 19-20

[fn:9] ibid. p. 21

[fn:10] ibid, p. 38

[fn:11] Summons of the Lord of Hosts, p. 154

[fn:12] Lights of Guidance, pp. 113-4; from a letter written on behalf
        of Shoghi Effendi to an individual believer, December 10, 1947
