:PROPERTIES:
:ID:       066A8023-DB3C-4BAA-800B-E4CB65AD277C
:SLUG:     living-in-the-now
:END:
#+filetags: :journal:
#+title: Living in the now

I find that many people have a hard time "being in the present" because
they think the experience should take a certain form. After all, one can
only be in the present. What part of us has the ability to roam into
past or future? If we remember the past, we do so in the present; if we
project into the future, it is still a present activity. All activity,
thought, and being, is only and ever in the present.

Understanding that, there is nothing one needs to "do" in order to live
in the now. When we think there is a "right way" to be present, this
causes us to continually step back and ask, "Am I doing it correctly?"
And though asking that question is also done in the present, it doesn't
feel "right", and so we take another step back, to see how to correctly
ask the question. The result is major anxiety! And that anxiety is
something we seek to be distracted from. Funny, isn't it?

If one is naturally distracted, just be distracted. When that is OK, it
makes the present a much friendlier place, and there is no reason to
escape.
