:PROPERTIES:
:ID:       A8DFE605-7267-4BD0-8379-1DC3C35A0ECE
:SLUG:     contexts-of-perception
:END:
#+filetags: :journal:
#+title: Contexts of perception

After thinking, here is another analogy to explain the functional,
relative nature of concepts: If I look at a tree in a meadow, I can
point to it and say, "That is a tree, while the rest is not." The
concept of "tree" isolates one part of what I'm seeing from the rest.
But if I say, "There are just atoms over there," or, "There is only
energy in front of me," I no longer have any reason to distinguish
"tree" from the whole. "Tree" does not exist in terms of pure energy,
but only in the macro scale of plants and vegetation.

Which is more accurate, to say there is a tree composed of "energy",
like everything else; or there is energy, part of which I label "tree"?
Is tree the reality, and "energy" a supporting identity? Or is energy
the reality and "tree" merely supplemental? There are many ways to
classify what I see -- infinitely many -- in some of which "tree" has
meaning, but in most of which it does not. "Tree", then, is applicable
as a term only when it is understood that I am using a particular
framework of description: a context of perception: a paradigm.

In other contexts, "tree" disappears, though we might overlay contexts
so that "tree" is perceived while talking about atoms and energy. Unless
one context can be said to have priority over others in terms of what is
really there, we have no more reason to believe that "tree" exists than
we do to believe it does not. In everyday life we rank our perceptual
contexts, or paradigms, according to a hierarchy of values which are
directly related to the goals we want to achieve; but these priorities
are not inherent in the contexts themselves.

To ask the famous question of a tree falling in the forest, there is no
objective reason to differentiate between the "tree", "forest" and
"sound" it makes after hitting the ground, unless we have a purpose for
doing so. Without a perceiver these terms do not exist. It would be
equally valid to say that "energy was" before the tree fell, and "energy
was" after the event. In terms of energy, nothing happened. Even to say
it was reconfigured depends upon context, since infinite ways exist to
visualize the original and subsequent configurations. Since energy was
neither added nor removed by the event, in terms of energy its state did
not change. Thus change itself is found only within our paradigms; it
cannot be said to apply to the underlying reality, or what all the
paradigms refer to in common.

This implies that no reason exists to think that what we see is "there",
in the sense of saying, "There is a tree over there in the meadow." The
sentence remains useful for many purposes, but to say that a tree is
/really there/, independent of the paradigms in which we perceive
"tree", is no more valid than to say it is not there at all. The words
do not describe what we are seeing, they only identify the context used
to convey the scene. We could describe the scene in other ways, even
experience it in other ways -- such as in memory, dreams, or under the
influence of chemicals -- in which neither "tree" nor "meadow" are seen.
This abandonment of terminology yields a loss of words, as with any
novel experience with no determined context. The later invention of
context might offer a common frame of reference for describing the
event, but it will never accurately portray its content.

The use of concepts to achieve purpose is inestimably valuable, and
deserves all the refinements we constantly make. It is only when we
confuse description (ideas, concepts, contexts, paradigms) with the
inexpressible reality, as with mistaking a map for the territory it
describes, that we find it difficult to see things in terms of other
paradigms, or to appreciate the mystery that we have never really known
what we see: a fact that should always engender a deep sense of wonder
and curiosity.
