:PROPERTIES:
:ID:       9BBAFB47-453B-4BEC-BAE6-D2BBFE40CDC1
:SLUG:     a-lovers-pain
:END:
#+filetags: :journal:
#+title: A lover's pain

What comes below follows directly from earlier essay,
[[file:the.hidden.door][The Hidden Door]], which had a profoundly
unsettling affect on me (and my sense of "me"). That essay led to
several weeks of feeling strange, and jumping at shadows, disturbing as
it did many long-held notions I'd had about what was real.

Then this, two weeks ago, with an even greater affect. It opened
floodgates of past and present sorrow, which had been held off for so
long by not accepting them. Some of it was even unleashed on the dearest
people in my life, before I knew what was happening. Which leaves me
today staring out over a black pit -- but one with a bright and growing
center...

I appreciate everything I am given, to the extent I do not ask for more.
If it all must end today, I accept. If I lose everything and everyone I
hold dear, one by one, I do not regret. Anything beyond the present
moment is unexpected, unknown. Everything is His again, though I thought
them mine for a time. But how can I lose anything? The fear of loss --
the things in my life; the people, relationships, freedoms; the
capacities of mind and body -- their loss reveals only my belief in
their possession. All was lost to me some fifteen billion years before I
knew it was here; and everything I know must escape me.

#+BEGIN_EXAMPLE
Hold your breath and you will lose it;
set it free and it must return.
#+END_EXAMPLE

I love life enough to no longer wish it; because by wishing, I wreck the
very thing that makes it wonderful. Trying to preserve what I think to
be my life, I fail to see its nature. I cannot both be and seek to be.
Always looking for the dangers, I fail to see the rest. A life that
seeks security, secures itself against life. Is happiness possible while
worrying about unhappiness? Thus, to live one hundred percent is to be
just as willing to die.

Willingness to be anxious is relaxing, because the anxiety is no longer
troublesome; guarding against anxiety is the most anxious. There seems
to be in life a fundamental paradox: that we gain through loss; that
knowledge is useful primarily in revealing our ignorance; that the
difficulty of being detached is the striving for it; that the
distinctions we use to understand life blind us to its essence.
According to this paradox, the Perfect can be found in the midst of
imperfection; the self separates us from God because "we" love "Him";
our "life" is the veil that keeps us from living; our desire for
security is what makes us insecure; our search for God is what makes it
impossible to find Him. "Leave thy self behind, and then approach Me."

I think the answer to joy lies, like a hidden door, in the very heart of
pain. "Joy" and "pain" are, after all, distinguished by me, not in
reality. In fully embracing all, I no longer need to escape one part in
favor of another. By accepting self, it must dissipate, because it was
never real to begin with. Our contention with life is like fearing
shadows: the fear itself is what makes demons of them. In loving those
demons, they return to the mere nothings they always were.
