:PROPERTIES:
:ID:       DC159D7C-C303-40CE-801F-97D41FBA0D9A
:SLUG:     the-fund-is-the-base
:END:
#+filetags: :essays:
#+title: The Fund is the base

In computer engineering-particularly chip manufacturing-there is a
concept called a "substrate". A substrate is a medium for design; that
is, it is the actual substance that a computer chip's design is
imprinted upon.

The whole idea of a computer chip is that it directs the flow of
electricity coming in through one or more of its input pins, to a
variety of locations situated elsewhere in the computer. This flow is
governed by a design, which is very much like the flowing of water along
canals. Canals have to be dug somewhere, however; without dirt, even the
best of architects cannot create anything.

Dirt is to the canal builder what a substrate is to the chip builder.
The most common substrate is silicon, but there are others. The main
point is that even if there are huge amounts of electricity and the best
of designs, without a substrate, neither can influence the affairs of
men. It is then only an idea, or a lofty concept. The rubber does not
meet the road until a substrate is provided.

In like manner, so it seems to me, the Fund is to the spiritual designs
of Bahá'u'lláh what a substrate is to the chip manufacturer. Bahá'u'lláh
has fashioned a New World Order, and provided for our lasting peace, but
unless the physical mechanism for conveying this vital energy is
erected, humanity will not receive its benefit.

By giving to the Fund we offer exactly that material ingredient. Our
money goes toward the expansion and maintenance of the Bahá'í
Administrative Order, of which Shoghi Effendi wrote, "Bahá'u'lláh has
given to the world institutions to operate in an Order designed to
canalize the forces of a new civilization."

These forces are spiritual in nature, and hence intangible, in the way
that water is intangible and will slip through our fingers if we try to
hold on to it. If we wish to bring that water to someone, a vessel is
required. This is how the material serves the spiritual. And this, I
believe, is how the fund relates to the communication of those energies
latent in the Bahá'í Faith to the rest of the world.
