:PROPERTIES:
:ID:       6483E7BF-9036-4415-AA7F-81C13368A488
:SLUG:     fear-of-god-like-spiritual-inhibition
:END:
#+filetags: :essays:
#+title: Fear of God like spiritual inhibition

Picture you're in a 7-11, and the clerk steps out of the store
(unlikely, but just humor me). There you are, with all that candy in
front of you and nobody watching. Do you pocket any? I can imagine you
saying, "No". Ok, let's say I'm asking you to do it anyway. Would you
still say no? Where is the limit, when would you would finally do it?
Would you never do it?

This agency, whatever it is that /prevents/ you from taking what is not
yours, is the fear of God. It stays your hand from violating His Will.
It's deeper even than conscience, which most people feel only after
they've committed a crime.

This kind of fear is a protector, a guardian, against one's own
insufficiency of understanding. Take the Fast for example. Many people
don't comprehend the wisdom of the Fast, but they observe it anyway.
Why? What about when no one is around, why do they still not eat? Some
shrink back from shame, or fear of being punished. But most are simply
/averse to breaking their Covenant with God/. It's not emotional terror
that strikes them, but a fear much deeper, and much stabler. It's like
being afraid of violating your own integrity. Emotional terror can be
countered by sufficient will, but the fear of God is a true fortress for
the spirit:

#+BEGIN_QUOTE
The fear of God is the shield that defendeth His Cause, the buckler that
enableth His people to attain to victory. It is a standard that no man
can abase, a force that no power can rival. By its aid, and by the leave
of Him Who is the Lord of Hosts, they that have drawn nigh unto God have
been able to subdue and conquer the citadels of the hearts of men.[fn:1]

#+END_QUOTE

When one comes to appreciate the Fast, they can observe it for love of
God and admiration of His beauty. But until then -- and this is true of
any of the Laws -- the believer is stuck between mystery and
enlightenment, and the fear of God is their only refuge. Since obedience
itself is one of the means by which we grow spiritually, it is paramount
that we understand this concept.

#+BEGIN_QUOTE
In formulating the principles and laws a part hath been devoted to
penalties which form an effective instrument for the security and
protection of men. However, dread of the penalties maketh people desist
only outwardly from committing vile and contemptible deeds, while that
which guardeth and restraineth man both outwardly and inwardly hath been
and still is the fear of God. It is man's true protector and his
spiritual guardian. It behoveth him to cleave tenaciously unto that
which will lead to the appearance of this supreme bounty. Well is it
with him who giveth ear unto whatsoever My Pen of Glory hath proclaimed
and observeth that whereunto he is bidden by the Ordainer, the Ancient
of Days.[fn:2]

#+END_QUOTE

There are many times in my past when I saw myself as a "Bahá'í for lack
of opportunity". I used to bemoan this, wondering how I could be true to
my Lord when circumstances determined my faithfulness. The answer is the
fear of God. If I wed myself to that ideal, and properly fear God, I
will learn true faithfulness, despite my frailty and lack of
comprehending the wisdom of all of His laws. By working on this one
area, I give myself the freedom and time to develop my understanding,
without worrying that I will fail due to lack of knowledge. I no longer
have to depend on agreement with the Law to abide by that Law!

Does this mean I crush my mind under a weight of obedience? Think of it
this way: If one believes in the truth, they would never want to betray
that truth. Some believe in truth, but lie under pressure. How can one
be true to the truth, in defiance of their own emotional frailty? The
fastest way is to identify one's self, psychologically, with the ideal
of truthfulness, making dishonesty appear as a destruction of their
self. This is what the medieval knights did, when they accepted the code
of righteous conduct: death before dishonor. Did they have to fully
grasp the meaning of honor, in all its implications? No, they merely
recognized that without honor, they were comprising their existence as
men.

This is the fear of God, to realize that obedience to the Covenant is
the foundation of our soul's well-being, and that to violate it is no
less tragic than for a knight of the Round Table to accept dishonor. The
foundation of our spiritual life /is/ our recognition of God and our
obedience to the Covenant. When a transgression is as fearful as
plunging a knife into our own heart, I think we've begun to fear God
properly.

But do we cower in fear at the thought of stabbing ourselves, all day
every day? No, we never think of it at all. In fact, the healthy fear of
authority we all possess -- which causes us to obey traffic lights and
not shop-lift -- never occurs to us as an emotional fear. I don't think
the fear of God should either. So it remains true that "Love never
dwelleth in a heart possessed by fear" -- the kind of fear that worries
or terrorizes, not the kind that protects one from willful
self-destruction.

[fn:1] Bahá'u'lláh, Gleanings, p. 272

[fn:2] ibid, p. 93
