:PROPERTIES:
:ID:       DFA5C539-2E19-41EA-A107-020CCB752017
:SLUG:     what-lies-beneath
:END:
#+filetags: :journal:
#+title: What lies beneath

The vast wilderness of the real opens to view, and I am struck mute. A
feeling of awe, strangeness -- a disturbing discordance with all I'd
imagined. And yet, it feels right. Like breathing deeply after holding
one's breath. It is belief in our ideas and knowledge that impoverishes
us, cuts us off, divides us according to countless, meaningless
distinctions. The values we ascribe to life are borne of our own
understandings, but are not attributes of true reality. There can be no
differentiation in reality -- only between the concepts of our minds.
Just as the eye sees shape, the mind sees distinction: close the eye,
and all is visually uniform; close the mind, and reality returns to
singleness.

Yet the mind is part of reality, and what the eye sees is more beautiful
than darkness. The key is: what we see is not the same as what is there.
For example, shape is determined by lines, and lines are perceived
through contrast of color. The lines are not /there/, but merely
observed where colors differ; when colors are similar, we see
uniformity. Both distinct and uniform are merely fields of color. So it
is not the presence or absence of objects that I see, but degrees of
color variation. The notion of separate objects is something I perceive
in the uniformity of light striking my eye. Within the varied
frequencies of that light, I form impressions of the world. And just as
my eye's perception crafts shapes from light, my mind's eye generates
experience from reality. I call one thing good, another bad, and with
respect to my organism, these distinctions have value. But the
experiences are no more real than my perception of them. If you were to
deprive my body of all sense, I would no longer experience the world.

To continue with the analogy of vision: When I look at a scene -- as I
am now, at a restaurant -- I am both seeing and not seeing what is real.
All the shapes and colors exist in my mind alone, as perceptions. The
light forming them, however, exists the same for all viewers. But no
amount of staring will allow me to see the actual photons comprising the
image. Without them, I could not see, so obviously they are always being
seen; however, since my perception is of the information they carry --
and not them, themselves -- I cannot ever see them. I might say I know
what I'm seeing, but in fact I've never beheld the essence of sight,
/despite its being around me at all times/.

Back to reality, it is similar: Something utterly mysterious underlies
my perceptions, being itself always experienced and yet imperceptible.
Nor do I need to know what it is to experience it. Nor can I know!
Always in view, it cannot be seen; ask me, and I do not know what it is.
To see is to look upon it, and to live is to know it intimately.

The upshot of all this concerns how we interact with reality. If I
regard my perceptions as "real", and disregard the significance of the
unapproachable, unavoidable "real real", I am liable to think that a
memory of my perceptions is a memory of reality. But how could it be?
Memory of a thing perceived -- as with projections of the future -- /is
lacking exactly that component which made it real/. Memory is like a
body from which the spirit of life has passed. It seems remarkable,
then, that we should be standing some place and choose to dwell on
memories unrelated to that place, like turning from a living person to a
man made of straw for conversation. Perception may have a certain value,
but it is not endowed with life. "Life" is the inexpressible
underpinning of the present moment, without which perception could not
be.

The value in these thoughts? To know the poverty of the mind, in
conjunction with its powers; to see that some /thing/ is making life
possible, and to heed its value beyond the perceptions we derive from
it; to see our perceptions as forming our awareness, but unreal
otherwise, and thus not deserving of too much gravity except to a
recognized measure; and to put tremendous stock in the magic represented
by all that we presently experience. There is a real Spirit there; and
to approach it is to /be/.

--------------

#+BEGIN_EXAMPLE
There was Something undefined and yet complete in itself,
Born before Heaven-and-Earth.

Silent and boundless,
Standing alone without change,
Yet pervading all without fail,
It may be regarded as the Mother of the world.
I do not know its name;
I style it "Tao";
And, in the absence of a better word, call it
  "The Great." -- Lao Tzu, *Tao Teh Ching*
#+END_EXAMPLE

--------------

#+BEGIN_EXAMPLE
To realize that our knowledge is ignorance,
This is a noble insight.
To regard our ignorance as knowledge,
This is mental sickness.

Only when we are sick of our sickness
Shall we cease to be sick.
The Sage is not sick, being sick of sickness;
This is the secret of health. -- Lao Tzu, *Tao Teh Ching*
#+END_EXAMPLE
