:PROPERTIES:
:ID:       BE7490B5-7FF0-4799-BCEA-A0949E4759BA
:SLUG:     the-veil
:END:
#+filetags: :journal:
#+title: The veil

Driving the road between Yosemite Park and San Francisco, my skin
toasting in the sun and my heart communing with the spirit of Driving, a
thought came to me about the nature of this world -- the veil. It stems
from a story written by `Attar. He writes that a great king once
possessed such dazzling beauty, his subjects expired instantly on
meeting him. Wishing the well-being of his people, he locked himself
away in his castle, but set up a huge mirror so he could still wave to
them and show them that he loved them. He separated himself out of love,
that they would not be overcome, and have a chance to know his love.

This caused me to imagine a perfect Being, possessed of an equal love.
Since it is the nature of love to express itself, and shower its light,
He chose to bring into being creatures to receive that love, the way
some parents are inspired to have children. This, then, would be the
reason we are here, because He wished that love to be known.

Having created us, He could not reveal His love right away. Such an
outpouring would obliterate us before we could appreciate it. If the sun
rose too quickly, plants would not survive the transition from darkness
to light, from coolness to warmth. The way of fragile things is
graduation, so He needed a way to manifest His love gradually, in order
for it to be known.

If love is light, then we are the eyes to see it. But if a bright light
appears too suddenly, it brings only blindness and pain. We would not
appreciate a single moment of its brilliance. Thus, in consideration of
our frailty, darkness was created. In the relative darkness we can open
our eyes, and accustom ourselves to vision. By appearing gradually, we
learn to appreciate the light, and its infinite varieties of shape,
texture, and color. We can see the beauty hidden in the light because it
is reduced from its pure whiteness, to the shades and hues of physical
objects. The world is our veil -- and our filter, allowing us to see
what otherwise would overwhelm our vision completely.

So the perfect Being created a world of limitation, of seeming
imperfection, to attenuate His love to the hearts of its recipients. Out
of love, He created the veil of the world: an act of love to protect us
from the overpowering force of that love. The imperfection we see are
mercy, for without them, we would carried away by His awesome beauty.
Without the limits of our awareness, we would not be aware at all. Our
limitations, then, aid our awareness, much as warming up aids physical
exercise. There is nothing but love implied in the nature of our being.

If this rings a note of truth, it indicates a fundamental shift in how I
view my flaws. They are like the lid upon my eye, at once obscuring my
vision, but also protecting it. To see, I must open my eye -- and remove
the obstruction. /But until I am ready to see, the lid serves me at the
same time it inhibits me/. Removing the veil in order to see is a boon
to awareness; but having flaws is also a boon to awareness, protecting
it until the time is ripe. It may even be that the process of removal is
what prepares my soul for its accomplishment, much like a protective
skin to be shed off as I grow.

It means there is nothing but love to be seen in the fact of creation.
Even what seems to have nothing to do with love, is another kind of
love. I cannot imagine the alternative, a world full of peril and
deceit, with a wrathful God waiting to judge our mistakes at the end of
life. I think, rather, He simply reveals himself to the extent we have
matured. Our flaws are there to give us the chance to grow. The purpose
of life is not only to remove them, but to outgrow them, in order to see
what lies beyond.

Otherwise, we would be like hapless citizens meeting that beautiful
King, and throwing away our lives away at His feet. How can we know His
love, unless we live long enough to feel it? The nature of this world,
the veil, is like a nursery for rearing tender plants, guided by the
loving hand of the Gardener. What gardener plants his seeds, only to
scorn those that grow more slowly than others? He would know only love
for them all -- and sorrow for those who give up on growing, and slowly
recline into the waning hues of death.

The veil is both our life and our death, just as sleep is both the enemy
and the friend of consciousness: Enough of it, and we are readied to
face the new day; too little, and we cannot concentrate; too much, and
we miss the day entirely. If this is true of all our flaws -- of the
veil itself -- then, like a bandage on a wound, let us appreciate its
role until the need is ended. The purpose is to know His love, after
all. Dwelling on our flaws, or fearing them, or focusing solely upon
them, is to give them much more importance than they deserve.
