:PROPERTIES:
:ID:       F8ACC844-9290-4C51-82B0-30148A694D6A
:SLUG:     detachment-and-desire
:END:
#+filetags: :journal:
#+title: Detachment and desire

My thoughts have been leading me toward the belief that all religious
truth stems from, and returns to, love. If love is not considered,
spirituality makes little sense me, or leads to a frustrating illogic.

A key example of this is detachment. I see detachment as merely a
condition of love. It has nothing to do with rejection or denial. If the
foundation of detachment is negation, what would fuel our efforts to
achieve it? The soul, like a mule, does not move quickly when flogged
from behind -- but with alacrity if attracted by something greater. I
believe that in a similar way, only love can power the soul's flight.

Which would mean that detachment from negation is impossible. It
exhausts the heart, and troubles the mind. It consumes vast sums of
energy. It pits us against our own nature. How can a creature in a state
of internal war expect to live joyfully? The battle must be renewed at
every moment, without rest -- and still nothing is achieved. Perhaps
this is why some retreat to mountains: to focus the whole of their
resources on the problem. Yet this sanctity is too often fragile,
because the essential problem of one's nature has not been solved.

It seems odd that any concept of spirituality should be destructive to
the wholeness of human life. God created our minds and bodies as well as
our spirits: shouldn't there exist a state of being in which all are in
harmony, all directed toward one goal? Shouldn't religious truth be
freeing, joyful, energizing?

I understand the concept of jihad -- the effort a believer makes in his
quest for God -- but I think this refers to the effort of a student, not
a laborer. We cannot escape our nature, any sooner than we could jump
from our own skins. Such understanding eventually leads to a longing for
death: because it's the only lasting solution to the problem! Love,
however, suggests an utterly different conception of spirituality.

If I love my being, I am not at war. There is no struggle. God created
us, and adorned us with the perfections of both worlds. These become
apparent, by degrees, through the course of education and time.

A part of human nature is caring about the things we value. If
detachment follows from rejection, it implies we should care about
nothing. We would always be at war with our interests: we want sex, but
we want to be detached. How can any healthy person ever resolve that
dilemma?? (Except of course, by looking forward to death).

Spirituality does not aim at death, however, but the fulfillment of
life. It should make a person much /more/ alive, not less. The schools
of asceticism I've read about leave people withered, and barely involved
with their physical self. They strive to save the spirit by cutting away
the body, denying the heart, and emptying the mind. How is this
different from the condition of a living corpse?

Real spirituality should have the opposite effect, if it involves love:
It would inflame the passions, excite the intellect, and invigorate the
body. I can imagine such a person would radiate vitality and life. They
would long for excellence in all things, and have a heart to conquer
mountains. How could detachment ever be compatible with such a fondness
for living, and richness of potential?

At this point I have to ignore detachment, because I cannot make sense
of it by itself. By itself, it feels like a conceptual grave for the
heart. By itself, it is productive of nothing.

But imagine a person who has fallen in love with someone, a beloved too
dear to describe. Watch what happens to that person. If he goes to her
house, and she is dressed plainly, he does not care. If she has no tea
to offer, he is unaware. If sickness has taken away her voice, he hears
her anyway. Love has transported him beyond the material aspects of
their union. Even if poor, sick, or cast into prison, he would still
feel alive through her presence.

If the beloved's dress, her tea, her words, are metaphors for the things
of this world, then I can understand detachment. It is only natural for
the lover to see material things as a means to an end: reunion. He does
not reject the part of his being which cares about things and becomes
attached. He fulfills that part by caring about the one he loves and
attaching himself to her. And if we speak in terms of God, it is the
same: falling in love with Him will render meaningless every other
thing. The only purpose for existence is to connect the seeker and his
Goal. There is no war, no effort. The only thing required is for the
lover to find the one he loves.

Another example of this is selfishness. It is impossible not to be
selfish, because that is our nature. We are always at the center of our
own awareness. There are then two ways to approach the problem: by
negation, or rejecting our self in favor of others; or by affirmation,
or extending our concept of self to include others. If we go the latter
route, /we enlist our natural inclinations toward a greater purpose/.

If the example of selfishness is too abstract, try the family. It is
human nature to prefer one's family to outsiders. Then how do we create
a tighter society? Negation would ask us to devalue our family, and see
everyone as an equal; but affirmation says: make everyone your family,
and engage your natural impulses toward a higher function.

The consequence of this is that there really is no "detachment" /per
se/. You are never "detached". Detachment simply describes how you
behave when you relate to something that you love. Maybe one person is
attached to money; yet show them a thing they want to buy, and suddenly
they are willing to part with that money. Their attachment to money
stems from its having a temporarily higher value than other things.

So the solution is not to deny the body, but to educate the soul that
there are better things in life. Seeking detachment is like trying to
stop a child from paying attention to something: it's fruitless to
command them; the quickest and most effective way is to give them
something more interesting to play with.

This implies that God is, by His nature, the most interesting thing that
exists -- if spirituality, as taught by religion, is to work. He must be
greater than all the great things of this world, if we are meant to be
detached from the things of this world. In one place Bahá'u'lláh writes:

#+BEGIN_QUOTE
Say: He is not to be numbered with the people of Bahá who followeth his
mundane desires, or fixeth his heart on things of the earth. He is My
true follower who, if he come to a valley of pure gold, will pass
straight through it aloof as a cloud, and will neither turn back, nor
pause. Such a man is, assuredly, of Me. From his garment the Concourse
on high can inhale the fragrance of sanctity.... And if he meet the
fairest and most comely of women, he would not feel his heart seduced by
the least shadow of desire for her beauty.

#+END_QUOTE

Is Bahá'u'lláh creating a snafu here, and indirectly saying that no one
is good enough, that we are all bound to fail? Is He speaking in the
language of negation, and telling us that we should see as valueless the
things we value most? Or, is He using a very subtle language. Is He
speaking in the language of affirmation about something that is not
directly mentioned in the paragraph, but which the whole paragraph is
about?

His language implies that a Thing exists which is so valuable, it would
cause a man to completely ignore a valley of gold; and so beautiful, the
same man would fail to notice the most comely of women. It's as though
the words are painting the outline of something... And the proof of a
person finding that Thing would be his perfect detachment: a detachment
stemming from complete and utter rapture in that implied Reality.

If the glory of God fits this conceptual "hole" in the paragraph, then
it must be /amazing/. I mean, to ignore a valley of pure gold, and the
most comely of women? Can I even imagine something so beautiful, that it
would distract me to that degree?

It spurs my interest to learn how to see this Reality. And the more I
see of it, the more it consumes me, and the more naturally -- and
effortlessly -- I become detached from other things. When detachment is
hard, I know I'm fighting my interests; but when it's easy, I know I've
found something much more worthy of those interests.
