:PROPERTIES:
:ID:       EF56A947-EB68-40F9-96E4-AAF7190A3962
:SLUG:     detachment-and-emotions
:END:
#+filetags: :journal:
#+title: Detachment and emotions

If the world is like a mirror reflecting the attributes of God, we can
say that the mirror shines because of the Sun within it, and not by its
own power.

To look at one of the many mirrors and fall in love with it is perfectly
natural, because the soul is a lover of light. The question is, are you
in love with the particular mirror, or with the Sun that shines within
it? If we love the Sun, we will cherish its light wherever we find it:
in small mirrors, large ones, clear ones, somewhat dusty ones. Our
powers of detachment permit us to see past the mirror, and focus on the
reality it reveals. If we love the mirror, however, we have failed to
understand the role of things in Creation. Then if another mirror comes
we will treat it poorly; or if the Sun departs from our beloved mirror,
we will still cling to it. The people of the past rejected the
Manifestations of God because they were lovers of a particular mirror,
instead of lovers of the Light. They were attached to the Sun's places
of appearance, and not to the Sun itself.

Being detached from wordly things, therefore, is a separate matter from
emotion. Our emotions exist to strengthen our bond to God, and shouldn't
be ignored. But in order for the fulfillment of emotion to take place,
we must detach ourselves from everything that exists -- the mirrors --
so that our sight can be wholly focused on God -- Who shines within the
mirror.

And so truly loving people comes from seeing God within them. This will
enable a person to love all of humanity. But if we look to the
particular attributes of people, sometimes we will love them and
sometimes we won't at all. Detachment is what saves us from getting lost
in their myriad failings and thus fail to appreciate their fundamental
beauty.

As far as humans being able to perfect detachment: Before we get too
stratospheric and lift detachment to an impossible level, perhaps all of
us already know how to be detached. For example: There is a concept
which I will call "Orange". I know what Orange tastes like, what it
looks like, what it smells like. When I want Orange, I go to the store
and buy an orange and eat it. This particular orange I buy allows me to
experience an Essence which I knew long before that physical orange came
into being.

Now let's say that I buy three oranges and I pull one of them out to eat
it. But something happens, I drop the orange and it falls down a storm
drain. An adult will say, "Oh well", and will reach into the bag to get
another orange. This is because he knows that Orange is what he wants,
and each particular orange is simply another manifestation of the same
essence. One is as good as another. He is completely -- perfectly! --
detached with regard to the particular, in favor of the Absolute.

A child, though, might have a completely different reaction. He may cry
and say, "But I wanted /that/ orange!!" The adult tries to tell him they
are all the same, but the child has fallen in love with the one orange
that disappeared. He is not detached, because he loves the particular
over the Absolute. The adult wants Orange, but the child wants orange.
He still has some learning to do.

So I think we all know what detachment is, in many respects. We have
already perfected detachment over and over again. The ultimate form of
detachment is setting aside the world -- these particular manifestations
of the Divine -- in favor of God, the ultimate Absolute. Although it
seems vastly more difficult, it is an extension of the same basic idea.
I even think ordinary detachment exists to educate us and give us
examples of that spiritual Detachment.

But it's not so impossible. We've done it before, many times over. It's
a question of extending what we learned with those tiny lessons to their
ultimate degree: Applying our many experiences with detachment to master
that Detachment which is the purpose of those other forms.

Now, although the metaphor of the orange tries to cut to the heart of
the matter, it also drops a few subtleties along the way. Take for
example love of a sibling, a brother; if they are lost, it is not like
dropping an orange. In that case, the metaphor needs to be refined: What
one loves about a brother is never lost. His soul is immortal, and will
continue through all the words of God. Although it is a very sad thing
to lose one's point of connection to a special person, in reality that
connection is not lost at all when they pass.

For example, a brother has already gone through many stages in his life.
He was an infant, then a child, then a teenager, then an adult. At every
step an older form of his being was "lost", when he exchanged it for a
more mature form; but the essential connection is never lost. I love the
essence of my brother, so that even if his body's cells are completely
replaced every six years, I spare no grief for his body of six years
ago.

Likewise, when he matures again in passing from this earthly life.
Recently I was at the deathbed of a good friend of mine who died the
next day. When I saw him after his heart attack, it made me so happy to
know that his life had been spent serving God, and that I knew where he
was bound for. The falcon was about to be freed from its cage. I also
knew that once he passed we would have an even more intimate connection,
because at least one of us would no longer be impeded by material
restrictions. I continue to pray for him until this day, and sometimes I
can feel him helping me.

Now, if we can love the Essence of a thing -- its soul -- beyond all
places and times of appearance, we can love the Essence of Essences
beyond all its many forms too. A brother is not the orange that was
lost, he is the Orange that survives all changes. And in his soul one
can see the signs of God, and our love for him will be a cause of
drawing nearer to God. Is God a particular Essence which requires
turning away from one's brother, or is He the life of all Essences, and
therefore is seen by looking to that brother?

There is nothing which, in the end, does not serve the purpose of
knowing and worshiping God. It is holding to this purpose through all
changes and transformations that distinguishes the detached. In this
respect, not one of them would ever reject a Messenger of God, or be
distracted by His changed appearance in each New Day.

#+BEGIN_QUOTE
In this station the truth of the unity of God and of the signs of His
sanctity is established. Thou shalt indeed see them all rising above the
bosom of God's might and embraced in the arms of His mercy; nor can any
distinction be made between His bosom and His arms. To speak of change
or transformation in this plane would be sheer blasphemy and utter
impiety, for this is the station wherein the light of divine unity
shineth forth, and the truth of His oneness is expressed, and the
splendours of the everlasting Morn are reflected in lofty and faithful
mirrors.[fn:1]

#+END_QUOTE

[fn:1] Bahá'u'lláh, Gleanings, p.71
