:PROPERTIES:
:ID:       14DEC185-89C0-4F4E-B13D-715CFFED3F8B
:SLUG:     transparency
:END:
#+filetags: :journal:
#+title: Transparency

Everything hidden requires a manifestation to first become known, just
as the soul, without a body, would remain pure spirit and invisible. So
without His various Manifestations, God would likewise be forever hidden
from us. We require a medium to hear His Message -- that medium being
the Holy Books, the lives of the Prophets, the world and its peoples.

But the medium can confuse we of limited understanding, causing the
seeker to strive to develop keener vision, to make the "world" more and
more transparent until the Divine is seen in the face of the mundane. In
this way, the mystic's path lies in the development of insight.

Take for example a television. It may have many flaws, or it may have a
truly amazing picture. In both cases, people will look at the television
itself and wonder at the aspects of its being. Then a movie starts
playing, and suddenly the television is gone. It has become transparent
in its role of conveying the broadcast. I remember growing up with a
thirteen-inch black-and-white television that I watched all the time in
my basement. Now there are plasma screens with high-definition video
that looks like a window onto other worlds. However, my memory is not of
the tiny screen and its lack of color, but the programs I watched. In
fact, it doesn't matter what TV I watch a program on, if it's
fascinating enough my mind will transcend the medium. Even if there are
flaws on the screen, a bug crawling across, a scratchy speaker -- my
interest in the program causes every distraction to be eliminated.

I think religion teaches a path that can cause a similar thing to happen
in the heart with respect to God. That is, some behaviors lead to
improved transparency of view, such as prayer, fasting, meditation,
detachment, etc., and some make it more obscure -- back-biting being one
of the greatest of these, since it blinds us from seeing other people
and "quencheth the light of the heart". `Abdu'l-Bahá even wrote, "... it
[back-biting] would make the dust to settle so thickly on the heart that
the ears would hear no more, and the eyes would no longer behold the
light of truth."

So some activities improve transparency -- allowing us to focus on the
message beyond the medium -- and some degrade it. These two directions
would describe the soul's morality, since one path leads us closer to
knowing God-through-the-world, and the other leads away from it. Perhaps
this is "the Straight Path" of mystical literature, implying that the
whole of the journey lies in the development of vision and education of
the heart, rather than actual travel. We are at the Goal, from day one,
but the dizzying array of its possibilities has blinded us, as if a
light our eyes weren't adapted to see. Then what will improve sight, and
what impair it, and what are we aiming to see? These are questions I
think religion must address directly, if its promise is to guide the
soul on its way.
