:PROPERTIES:
:ID:       9FC81A87-F3F5-42C2-A182-E4157567D227
:SLUG:     thoughts-on-time-travel
:END:
#+filetags: :journal:
#+title: Thoughts on time travel

We tend to think of the universe as a stable system progressing from one
state to another, methodically. This has been the dominant view for
centuries. However, modern experiments have shown that the universe is
basically unstable -- /yet is always observed to be stable/. That is,
looking forward in time there are innumerable possibilities, but looking
backward in time we always see a coherent universe.

For whatever reason, we see only a coherent universe and not the quantum
flux that is its underlying reality. This has interesting implications
for faith, prayer and free will, but essentially the universe has two
faces: an utterly chaotic quantum flux we cannot observe directly, and
the highly ordered system we've become accustomed to.

For example, we see many properties of the universe as "laws", such as
the law that objects at rest will stay at rest. However, there is no
such law: we have simply observed such perfect consistency in that
regard that we infer the operation of a law. As far as the universe is
concerned objects can move spontaneously, but as far as history is
concerned, they do not (unless you consider miracles).

If consistency is only observed and is not a feature of the universe per
se, it means that stability is something the observer imposes on the
manifold possibilities of reality. We see a consistent progression of
history because something about the function of observation demands it.
Thus, if you go back in time and change something significant, you
cannot alter the fact that observers after that moment must observe a
coherent world. This is what makes time paradoxes impossible. People
used to think that the universe itself was stable and therefore a
temporal paradox would destroy its stability, but quantum mechanics says
that only our observation of the universe must be stable and thus no
matter what actions we perform in the past, it is impossible to destroy
the stability of future observations.

As for the future we "came from", it now exists as a separate potential
along a branch in a parallel universe that is no longer real from the
point of view of those who observed the change we made. A new and
different universe new proceeds after the point of the change, to
conform to the stability requirements of those who observed it. There is
always a single history and uncountable futures. Perhaps you could even
say that what we call historical time is the same as the reality of
those who experienced it -- that the fabric of our souls is made from
the outcomes we observe, rather than a separate substance altered by
such moments.
