:PROPERTIES:
:ID:       128215B8-B43D-49EB-9DCD-68C43FDAA2C9
:SLUG:     meditation-on-gods-love
:END:
#+filetags: :journal:
#+title: Meditation on God's love

One of my very dear friends moved to this country a few years ago and
has been steadily improving her English. Whenever we chat, I help her by
pointing out if things don't sound quite right. However, this situation
has created a dilemma for me, which prompted the following meditation:

The thing is, her manner of speaking is so utterly charming that I've
fallen in love with the way she uses English. "Fixing" her accent and
usage is really the last thing I want to do. She sounds so cute and her
word choices are so endearing, I find myself torn between acting as a
friend to help her, or being selfish and letting the errors slip.

It reminds me of when my last cat was a kitten, how joyfully he played
-- though he wasn't too coordinated. I didn't want him to grow up. I
loved every minute of his being a kitten. I knew maturity was
inevitable, and he needed to learn things to take advantage of it, but
that doesn't mean I was happy to give up those precious days.

My friend says the dearest things without meaning to. In Persian she
expresses herself quite eloquently; in English, her ideas are touched
with a special sweetness because of the new language. I know it's better
for her to learn more, but another part of me wants her to stay just the
way she is.

It made me wonder if God sees us this way. We all make mistakes and get
things wrong, but perhaps in His eyes those errors have a delightful
quality He simply adores. As I thought of this, I felt an intense sense
of His love for who we are, right now. I hadn't perceived it so fiercely
before. Then I wondered: what if I saw myself and the world this way?
