:PROPERTIES:
:ID:       E61C088F-FAA6-47CE-A67F-220373F97C74
:SLUG:     the-real-world
:END:
#+filetags: :journal:
#+title: The real world

I was asked recently what I thought about the nature of beauty and
truth. Since these are typical questions for Philosophy, I wanted to
know my presents thoughts on the matter. After a moment's reflection, I
replied that I think the experience of the present moment is all we can
ever know of truth and beauty. Anything beyond these -- such as the
principles and ideas we abstract from experience -- exist in the realm
of human concepts and limitations, creating an impression of the real
world which my uncle calls "the phenomenal world".

But thinking further, my opinion has changed. It is not the present
moment which holds beauty, but a capacity of the present to reveal it.
It's like looking into a mirror: you see whatever is reflected at that
instant. Take the mirror aside, apart from what's showing, and there is
nothing but your own face staring back at you. Is beauty "in" the
mirror? No. But it possesses a capacity to reveal it.

Then what is it that we look at? I remember seeing an old castle in
Germany, which had been standing for many centuries. It was in good
shape, with huge stone blocks and impressive, iron-banded doors. It
presented a convincing image of strength and stability.

That perception of strength and stability is what my uncle calls the
phenomenal: existing only in the momentary experience of those who
perceive it (however they perceive it) -- a trick of time and shape (cf.
Qur'an 27:88, comparing mountains to clouds). Peel aside the glossy
exterior of most buildings and likely there are veins of rot, rat
warrens, insect burrows, and other things we'd rather not know about. As
the veil of time is lifted -- moving into a distant future -- that
castle is already crumbling into dust, its memory fading away until the
space is only an empty field again.

That we are beings of phenomenal experience makes this perfectly okay,
since we're not asking the castle to endure forever. Or are we? The
image of the castle certainly feels almost like a promise -- and we want
the physical object to make good on that promise. We put a certain
degree of trust in it, invest some of our heart in it. We begin to have
faith in it. And this is where I think we go wrong.

It's not that the phenomenal world is a sham -- any more than a mirror
is a sham, though its images might still amaze -- but that we buy into
it, expecting it to become something more. Even if we're told it's just
smoke and mirrors; that the whole, pretty world we know is only dust and
energy in manifold forms; we still want it to end up real in the end.
Because if it doesn't, where else can we turn?

The man who stores up wealth in his bank account wants that phenomenal
wealth to somehow turn into real wealth, since the phenomenal wealth of
gold and dollars seems to hold a certain promise. Yet it doesn't. Christ
warned us of the easy susceptibility of mortal wealth to decay and
theft. But it just feels so real and solid; can't we believe it is?

This hoping -- a faith that the mirage will become the real river --
leads to a constant sense of dissatisfaction with life. It's just never
turns out "as it should". Every generation for century after century has
expected better times around the corner: religion, philosophy, science,
poets, have written and dreamed that one day, the phenomenal world is
going to turn around and finally become what it promised to be. In that
day, decay and theft will either be gone or mitigated. If it doesn't
happen in "this life", it's believed to happen in some other life. But
the consistent idea is that present reality just isn't quite right, and
that we're all waiting for existence to finally get its act together.

A natural consequence of the failings of phenomenal reality to satisfy
is the belief that it has failed because somehow we failed: either by
being essentially unsuitable for a better reality, or having failed in
the prerequisites to achieve it. The falsehood of the phenomenal becomes
a criticism of our own hope in it; and this, I fear, can only lead to an
condemning cycle of self-hatred. When the world itself is a constant
reproof, to where can a person turn?

But I think this is a problem we've created for ourselves. In wishing
the phenomenal to be more "real": more enduring, permanent, grand,
perfect -- those eternal qualities we glimpse in the ephemeral -- we've
created a dissatisfaction which demands an answer: Why shouldn't it be?
The mind tries to resolve this flaw in the world and comes up with the
idea that we screwed it up: that we didn't get it right and must labor
to right those wrongs. Religiously it becomes a perception of moral
flaw; scientifically, a flaw of understanding; artistically, a flaw of
technique or inspiration. The imperfections of the world around us
/become our imperfections in our own eyes/, and this, because we
believed it should have been better.

What is the real world? Plato's "real real"? When we see past time and
space, past distinction and multiplicity, what presents itself to the
mind's eye? What is it we keep wanting the phenomenal to become? The
alchemists wanted to reach it, to discover the secrets of capturing the
real, in order to restore the arts of perfection and ever-lasting
health. They wanted to bring its quintessential nature into the human
sphere so as to correct the flaws they perceived in the world around
them. Who hasn't been striving to "bridge the gap", to reconnect the
soul with the reflections of God it perceives in the mirage of life?

In some way, I think everyone is trying to bridge the phenomenal into
the real, or imbue the phenomenal with its qualities. They want the
facade of granite and steel to become a real building that can never
fade; they want their wealth to become an unassailable quality whose
value does not decay; they want their ideal to reflect truths that are
as unyielding to argument as truth itself. In so many ways, we take the
phenomenal to be real, and then try to patch up the weak spots so it
somehow becomes the real.

In all of this there is a critical misjudgment, which I think begins
with /believing in the images of the phenomenal/, and mistaking the
forms for their essence. It's not that any one form contains the
essence, but that /the essence lives by the infinity of its forms/, a
kind of Aristotelian home for Plato's perfections to dwell in. It is all
one masterpiece, not a broken promise. We make the errors in it that we
see, by demanding something of the eye it can't deliver: a perception of
flawlessness in a world where flaw is the salt of beauty.
