:PROPERTIES:
:ID:       FE338887-EB1A-40D1-A5BE-AE320D52D972
:SLUG:     spirituality
:END:
#+filetags: :journal:
#+title: Spirituality

On the subject of spiritual things, I think that true religion always
brings with it joy and happiness. Whenever these two are missing,
something has either been lost or not yet found. Spirit is like a
vibrant, beating heart; a shining light glowing from the center of human
life; a palpable energy that reaches out and touches hearts. Religion
educates us how to experience this reality, how to draw on its energies
and share them with other people. This "plugging in" would produce the
abundance of spirit and joy I keep reading about in the lives of the
martyrs.

But how to transform? Without this spirit, people are like unlit lamps,
or mirrors in a dark room. Human reality is one of the most beautiful
things in existence, but it must be "turned on" to reach its potential.
Spiritual transformation kindles the lamp, and turns the mirror to the
sun. It's like unveiling a masterpiece so that everyone can see how
truly wondrous it is. And I believe people have this beauty within them
at all times; it only waits to be awakened. Turn a mirror toward the sun
and even if it is dusty it will glow brightly.

Transformation, then, is not changing, but a shift of focus. When the
heart is concerned with material things, it is dark and forlorn; when it
turns toward the Divine, it becomes bright. Whatever the heart is
occupied with, it reflects. Thus, when a person is fully concentrated on
God, they will begin to manifest godly things.

The real trick is what is meant by "God". If one's concept of God is too
abstract and separated from the world, focusing on it will tend to turn
people away from the world too much. They will not appreciate the beauty
of life and will tend to forget about others. They begin to see material
things as "bad" and their heart slowly turns sour.

Because the joy and happiness are missing, I would say that such an idea
of God is wrong. We know God is near when we feel the melodies of heaven
reverberating within us. God is heat and light: can shadow ever be its
substitute? I think real attention to God would result in a deep
appreciation of the world -- such that even the smallest things are
cherished and seem valuable. And it will turn the heart towards people.

What kind of "God" would produce this transformation? If spirituality is
falling in love with God, and virtue simply the natural behavior of a
lover, then love of what God would produce a Bahá'í both in spirit and
deed? It would be an idea which gives value to the world, which reveals
people as glorious and wondrous in nature, and which unveils secrets
within the smallest of things: by which atoms become lights and suns,
and drops reveal the mystery of oceans: in terms of which nothing is
ever meaningless, and every moment of life reveals a deep and
everlasting love. What form of belief yields this?

I'm not sure it can even be named. What my heart turns toward, can I
ever tell it? Any attempt at words would repeat the very mistake I mean
to avoid. God -- as He relates to human life -- is something profoundly
alive, brilliant, warm, full of hope, bountiful, and glorious. When I
say "Allah'u'Abha", I'm not just saying that God is most glorious: I'm
actually defining for myself what God is. Wherever there is glory, I see
His face; whenever I feel wonder, I am touched by His presence; at
whatever time I'm lost in awe, then I know He is near.

And so I believe that spiritual transformation does not happen by effort
alone. Our efforts do not make us into something we're not; they open
our eyes and purify our heart so that we can see what is already around
us -- and has always been with us, "standing within thee, mighty,
powerful and self-subsisting".

#+BEGIN_QUOTE
Blind thine eyes, that thou mayest behold My beauty; stop thine ears,
that thou mayest hearken unto the sweet melody of My voice; empty
thyself of all learning, that thou mayest partake of My knowledge; and
sanctify thyself from riches, that thou mayest obtain a lasting share
from the ocean of My eternal wealth.

#+END_QUOTE

When we reach this state, we become a pure, receiving organ, capable of
detecting the fragrance of God from great distances:

#+BEGIN_QUOTE
So great shall be the discernment of this seeker that he will
discriminate between truth and falsehood even as he doth distinguish the
sun from shadow. If in the uttermost corners of the East the sweet
savours of God be wafted, he will assuredly recognize and inhale their
fragrance, even though he be dwelling in the uttermost ends of the West.

#+END_QUOTE

At that point, the seeker goes into the world and searches for his
Beloved. Where will she be found? What form will she take? He seeks and
seeks, casting away every idea and conception, waiting until his heart
thrums with nearness to his Love.

I think this is why it cannot be told: because every seeker must find
this Reality for him or herself, must go through the process of
purification and discovery before he can fully appreciate the Truth. Yet
after a person finds the Beloved, He becomes the point and origin of all
transformation and virtue: "Whensoever the light of Manifestation of the
King of Oneness settleth upon the throne of the heart and soul, His
shining becometh visible in every limb and member." This is gaining
access to the world of spirit, and discovering how to "soar in the air
even as thou walkest upon the earth". `Abdu'l-Bahá says:

#+BEGIN_QUOTE
Those souls that, in this day, enter the divine kingdom and attain
everlasting life, although materially dwelling on earth, yet in reality
soar in the realm of heaven. Their bodies may linger on earth but their
spirits travel in the immensity of space. For as thoughts widen and
become illumined, they acquire the power of flight and transport man to
the kingdom of God.

#+END_QUOTE

These are a people whose happiness does not come from effort or
"trying", but as a result of the world they experience. Their vision has
been transformed, not their substance. Once a person sees the glories
which have been deposited in human reality, and witnesses the miracles
attending every second our lives, how can he not be overwhelmed with
gratitude, and at every moment repeat the tradition, "O Lord, increase
my astonishment at Thee!"

Getting to this point does require some effort. Bahá'u'lláh says, "Labor
is needed, if we are to seek Him; ardor is needed, if we are to drink of
the honey of reunion with Him..." Yet once the fire has been lit, it
does not need to be lit twice. It will burn as fiercely as the fuel you
feed it. If every created thing, if every /atom/ became a door leading
to the Ancient of Days and a cause for wonder and amazement, how
brightly such a fire would blaze!

So in serving people, I do not want to "try" to serve them anymore. I
want it to become impossible not to serve them. If a person you loved
entered the room, would you be able to sit still and not look after
their interests? Love generates virtue as a fire produces heat. This, to
me, is the secret of transformation: find God -- I mean, not an idea but
the true, spiritual reality -- devote your heart utterly to Him, and the
rest of life will fall joyfully into place.
