:PROPERTIES:
:ID:       51DBF190-93F5-4679-B2AB-E02D70D67288
:SLUG:     reflective-judgment
:END:
#+filetags: :journal:
#+title: Reflective judgment

This random thought came into my head a while back, and I wanted to jot
it down:

The Bible says we should not judge others, "lest ye be judged". It then
goes on to say, "For with what judgment ye judge, ye shall be judged:
and with what measure ye mete, it shall be measured to you again."

I was thinking on this idea of reflective judgment, and how God will
turn the tables on us, so to speak, during the Day of Judgment (when our
souls are called to the next life and summoned to give account for our
deeds). What I came up with was this:

What if, when we die, our memories are completely blanked for a time
save for our abstract understandings and judgments. God then plays our
entire life out before us, as if a movie, and asks us: What do you think
of this person? How would you reward or punish them for their actions?
We make our decision, and n poof, he gives us all of our memories back
-- and we find we've just passed judgment on ourselves.

How would you judge your own life, if you saw it being lived by another?
It may sound like a harsh question, but consider the corollary in light
of the above verse: If one can learn to view everything in a favorable
light, there will be nothing to fear if summoned to judge one's own
life.
