:PROPERTIES:
:ID:       9CA4B438-55B8-40CF-8AC8-14E15AF3D75C
:SLUG:     being-free-to-submit
:END:
#+filetags: :journal:
#+title: Being free to submit

Freedom is an interesting concept. We basically want to be free in order
to take advantage of whatever opportunities come to us, so we can use
them to find what we're seeking in life. Not being free is our fear of
missing out on what life's all about: should I have had more sex,
thought more radical thoughts, lived on the wild side, set my soul
running free through the fields of possibility?

However, this desire for freedom is so we can be open to receive
something. /From that something we don't wish to be free at all/. Who
wants to be free of their happiness?

For example, ask a lover if he really wants to be free from the one he
loves. When I fall in love, I would rather be a bandage on the sore feet
of my desire! than remain free to walk all the lands of the Earth...

And so the soul finds true joy only in submission to God; not because
this is submission goes against our nature, but because true submission
fulfills our nature in the same way thirst submits to water and hunger
submits to food: we are longing and He is our Succor. Until this is
felt, I question what a person has so far discovered.
