:PROPERTIES:
:ID:       C97F09B1-157D-44C3-9508-987A4564B75E
:SLUG:     two-kinds-of-will
:END:
#+filetags: :journal:
#+title: Two kinds of will

A theme in mystical philosophy is the recognition of one's inability to
know reality, and how this recognition is perhaps the only real
knowledge man can attain to. However, we seem to know many things; we
seem to be free to explore our universe and accumulate vast stores of
knowledge about how it works. How does this connect to the esoteric
pursuit of recognizing our poverty of understanding and powerlessness
before God? If outwardly we have both freedom and knowledge, what does
it mean inwardly to have neither?

#+begin_html
  <!--more-->
#+end_html

I think we have two forms of freedom of will: lesser and greater. The
lesser relates to our freedom to act and the greater to our freedom to
know. More specifically, the lesser degree of freedom is our ability to
affect the physical world. I call it lesser because the effects exist
only within the perception of time: whatever changes we make to our
environment, after sufficient time those changes will disappear. If the
universe ever collapses back to its original state, nothing that was
accomplished will have any consequence beyond that point. Thus "actions"
are an artifact of our consciousness of them and have no lasting meaning
to the physical world they were acted in.

The greater freedom is our ability to choose between multiple
perceptions of an event -- to manipulate the perception of time. Not
only do we have consciousness of something that transpires, but two
people may give plural accounts of the same occurrence: we can choose to
ignore the obvious, invent causes for what is not fully understood, or
delude ourselves about what happened. In essence, we have freedom to
affect our perceptions, although no freedom to alter the energistic
universe that is the medium of those perceptions. Physics calls this the
"law of conservation of energy", saying that we cannot materially affect
the substrate of reality, only its temporary forms and thereby the
effect of those forms on consciousness. Our lesser freedom is not any
freedom at all but the perception of a freedom. We call it "free will"
according to the greater freedom because the latter allows us to
perceive it as real rather than as a figment of consciousness; yet the
lesser freedom is subsumed in the greater, and does not exist apart.

However, I am not saying that the effects of the lesser freedom are not
real with respect to humanity, simply that they are not real with
respect to the universe since the results exist only within the
perception of time. A murder is a terrible thing for a community, but no
trace of the event will remain at the end of the universe. Its meaning
is relative to our experience of the act, making the "act" /per se/ an
aspect of our consciousness of the event.

The greater freedom is where humanity really shows itself, because this
freedom decides how we interpret the events of the world, both those
occurring naturally and the actions of the lesser will. If the lesser
will makes a transient impact on the medium of reality -- like a hand
splashing in a pool -- the greater will decides how to interpret the
ripples. After enough time the ripples will cease, and the pool return
to its original state, but the effect of the interpretation may
potentially endure forever (if one believes in the soul and in memory as
a spiritual faculty).

Even the greater freedom is contingent, however. The freedom to choose
between interpretations depends on a belief in the existence of
alternatives. We have no freedom to decide the outcome of two plus two,
since mathematics defines the outcome in advance of the question. If our
knowledge of reality were similar we could have no choice but to accept
what knowledge indicates. Our greater freedom of will is thus only the
active form of our ignorance. If we were not ignorant there would be
only one explanation for events and only one best response to those
events. Our life would be determined by our environment just as appears
to be the case in the animal kingdom, where instinct takes the form of
an absolute knowledge of how to react to events.

Although animals have a lesser will -- the ability to momentarily affect
nature -- we do not call it a "free will" because of the determined
nature of their choices. They do not appear to believe in the existence
of alternatives because their instinct denies them such a belief. A
human being, however, can take time to reflect on what he sees and
change his interpretation of the scene resulting in a different
reaction. This is the greater freedom at work, although it too is really
no freedom at all; it is a contingent freedom that exists because man
has the ability to go from one state of ignorance to another.

If the foregoing has any truth to it, then what I know of as myself --
in the sense of a free individual who chooses how he reacts -- is in
fact a shifting pattern of unknowingness, moving from instant to instant
between various interpretations of a single, underlying truth. If I knew
true reality my vision would not be in flux and I would not experience
any such freedom. I would be a determined entity unable to lastingly
alter physical reality and unable to decide my perception of its
fluctuations, whether initiated by me or by an outside agent.

Yet there is another form of identity which is determined by the act of
its function and not by our interpretation of it: the identity of
awareness. Our ignorant identity is how we perceive this awareness in
selecting the interpretation of what it means -- that a scene implies a
viewer, for example. The function of awareness, on the other hand, is
the pure experience of life which cannot simultaneously be an awareness
of experience and an awareness of the awareness of it. That is, we only
perceive "self" in believing that such an interpretation is meaningful;
during the actual function of awareness there is only experience, which
does not need a perception of its use to function.

By all this my point is that our lesser freedom is an illusion with
respect to physical reality, and our greater freedom is an illusion with
respect to the truth. If the veil is ever lifted from our eyes we will
lose both forms of freedom, since we would no longer have the option to
choose how we interpret events (such as the illusion that we can
substantially affect reality). We are ultimately both powerless and poor
because the substance of our identity is crafted from the stuff of
shadow, our ignorance. We are a people who has received the results of
physical reality without the principles, and so we continually put forth
various schemes to explain the results. In those schemes we move and
act, even creating works of art to describe our understanding; but once
the truth shines and the actual principles are revealed the sand-castles
of our thought will be washed away and we will realize how everything we
"knew" was ultimately founded on fantasy.

Perhaps our true value, then, is not founded on knowledge or power or
the existence of self but something else entirely: because the fact
remains that our awareness continues to function despite our lack of
understanding it. If our knowledge serves no one in the end but itself,
it begs the question of the real purpose of awareness. Is mystical
philosophy trying to tell us that recognizing our inability to know is a
way of clearing the path so awareness can be put to a finer use? Is the
belief in self and freedom, knowledge and power, a distraction from the
true intent of consciousness? For if I don't really know what I see,
what is the intention of sight? Perhaps there is something else to be
seen, which cannot be so long as we continue to believe we already know
what it is.
