:PROPERTIES:
:ID:       BEE250F9-C83C-451D-AA42-BFBE8C5FC005
:SLUG:     the-mountains-are-also-clouds
:END:
#+filetags: :journal:
#+title: The mountains are also clouds

On the idea of forms existing only through our perception of time, I
came across the following in the Qur'án (27:90):

#+BEGIN_QUOTE
Thou seest the mountains and thinkest them firmly fixed: but they shall
pass away as the clouds pass away...

#+END_QUOTE

In picturing this, I realized that if time were accelerated quickly
enough, the formation, change, and disappearance of mountains would seem
very similar to the way clouds behave. They too drift, grow and shrink,
appear from nowhere and fade away again. Mountains are only durable and
permanent because we see things on a relatively slow time-scale -- one
in which mountains are mountains. Yet if our perception of time were
much slower, clouds would be like mountains in the sky, equally as
constant. The world as we know it exists in our perception of it, even
if the raw materials do not.
