:PROPERTIES:
:ID:       0EEFD2C9-7D41-48BC-AE92-E543078A3236
:SLUG:     dream-of-another-life
:END:
#+filetags: :journal:
#+title: Dream of another life

In a dream I was climbing a long tower. I asked, "Where are we going?"
and people said: "To see the Christ." It was a broad tower with a spiral
staircase in the wall -- something like a lighthouse.

As I neared the top, a feeling began to come over me. It was a kind of
joy that reached fingers through my body. At the end of the stairs I saw
what looked like a picture frame, or a small mirror. This, I understood,
was Christ's reality. People were approaching the mirror and
disappearing as they touched it. They were being transported to another
world.

As I walked toward the mirror, my feeling of joy became overwhelming. It
was more intense than anything I had ever felt before.

Meanwhile, in the distance, I heard someone sobbing. I drew closer and
became intoxicated; closer and I began to fade and glow. At the same
time, the sobbing grew louder and more insistent. Touching the mirror, I
knew, would transport me into another life. I longed to reach it, but
someone near me was in pain. What was happening?

At that moment I awoke and found that it was I, myself, who was
crying... I wonder if my body could not endure the revelation. It was
begging me not to touch the mirror. Ever since, this image comes to mind
when I think about the "next life" -- which in a sense is found when we
die, and in another by our recognition of Him.
