:PROPERTIES:
:ID:       D5DAB8D9-6B8E-49BA-B68A-91E65797362E
:SLUG:     a-kind-of-knowledge
:LOCATION: Barnes & Noble, Shea Blvd, Scottsdale, AZ
:EDITED:   [2005-05-03 Tue]
:END:
#+filetags: :poetry:
#+title: A kind of knowledge

#+BEGIN_VERSE
There is a kind of knowledge that is known only
if contrasted with ignorance.
If not for ignorance, what would it be?

Easily recognized, touted, much sought;
such knowledge reigns supreme through
the hallowed halls of Academe!

However, because its existence is contrastive,
it doesn't really exist at all.
It shows up only if placed in a certain light.

This is the manifest form of knowing,
from which "knowledge" takes its name.

Then there is another kind of knowledge:
one that has no contrast.
As such, it cannot be seen. Where is it?

It is all action, and no words.
It enters through the door
like a humble beggar
but in fact, it is king.

This is the hidden essence of knowing,
from which "knowledge" has its meaning.

Its effectiveness cannot be trapped
or entombed on gilded pages.
Like a warrior poet, it keeps peace
until the moment of inspiration.

The other is a fumbling scholar
who thinks one more book
will make him wise.

Learn everything about everything!
You are still only reading the index.
Know the name of every plant?
Now watch them grow!

How do you recognize a master of essence
when he has no ties to form?

Search for his knowing look
paired with a feeling of ignorance.
Someone who, if others talk about the weather,
prefers to walk outside.

One who chooses people over sociology,
health to medicine, joy to truth --
and truly loving to every kind word.

He will be conspicuous
by what's missing:
Such faith -- so very few beliefs.
#+END_VERSE
