:PROPERTIES:
:ID:       5EB1FCDE-72C7-449E-91C5-6B2F62E0B7D4
:SLUG:     faith-reason-and-authority
:LOCATION: Nasim's house, 239 Misty Creek Dr, Monument, CO
:END:
#+filetags: :journal:
#+title: Faith, reason and authority

Several times now in the past few year, I've encountered a particular
argument: Whether it is nobler to forgo faith in any higher agency, so
the mind may remain free and clear; or to surrender judgment if one
believes they've discovered a higher Power. To maintain freedom and
aloofness seems to strengthen the individual; while giving up everything
-- even the mind -- in the name of love seems positively transcendent.

In one case, recently, a person asked whether Baha'is should accept the
authority of their Prophet, Bahá'u'lláh, utterly and without question.
To do so implies accepting even those things we have not yet understood
-- things that have not seen the light of reason. This is especially
true since so many of Bahá'u'lláh's texts remain untranslated into
English so far, and who knows what they might contain?

But if I understood him correctly, his argument was not against
Bahá'u'lláh and religion, but rather utter resignation to any authority.
This impairs human development because it closes the mind, truncates
judgment, and relativizes the meaning of "truth" to that authority.

The example was given of resigning in the present to dictates whose
future character cannot be known. Using Bahá'u'lláh as an example of
this was a good one, since His believers presuppose perfection on the
part of that authority, thus condoning any and every prescribed future
action no matter its appearance or consequences -- because that guidance
is "perfect". This removes judgment and understanding from the human
realm and places them wholly on the altar of a chosen God.

The danger I believe he picked up on is that our relationship to "God"
is always framed within the confines of human understanding. For
example, Bahá'u'lláh's pronouncements were rendered in human language,
and must be applied by human minds. No matter the perfection of His
original intent, its expression and realization must occur within the
fallible realm of a human translation of that intent into behavior.

Because the Bah' community believes their Source to be perfect, they may
implicitly ascribe a transmission of that quality of perfection down to
the ultimate acts themselves. This phenomenon has been used throughout
history to condone the worst violence against humanity, since the
perfection of the Source was believed to reflect itself in the
perfection of the believer's interpretations, and then to the perfection
of the believer's actions. Thus we have the idea of a believer "doing
God's will", even if that will gets translated into putting thousands of
innocent people to death.

I think that to believe, once one has "found" Bahá'u'lláh, that they may
submit their will entirely and be forever guided on the straight path,
is just not possible given our human condition. What I mean is, even if
one has found Bahá'u'lláh, they have not found Bahá'u'lláh; even if one
has discovered a perfect testament to God's nature, they have not read
it; and even if Bahá'u'lláh's laws are perfect for the ordering of
society, we have not begun to follow them, and never will.

By this I do not mean that Bahá'u'lláh is fallible or His laws are
incomplete, but rather that our understanding is fallible and our
application of those laws is incomplete. The perfection of a
Manifestation's authority simply cannot survive crossing the boundary
between the divine realm and a human one. We will corrupt whatever we
are given the moment we hear it. Even using the word "God" is a
corruption, since an infinite being cannot be bound by our terminology
or understanding. We just don't know what we're talking about; we don't
know Who Bahá'u'lláh is; and we don't know what a single one of His
words really means.

What this requires of the believer is that he never cease in his pursuit
after the truth. Every day, it's possible to "find" a Bahá'u'lláh whose
reality one was unaware of the day before. In a sense, a believer cannot
"belong" to a faith and remain honest to his nature. The Faith he
belongs to on any given day is subject to his own immaturity on that
day, and will not be the same as tomorrow's Faith -- if he continue
ardently in his search.

And yet, there is hope in this. What religion requires of us is that we
grow and develop our understanding, not that we close our minds and
relax in the perfection of our leader. His perfection is not accessible
to us; this is the meaning of having imperfections. "The imperfect eye
sees imperfections", said `Abdu'l-Bah. So too, when we read the Writings
of Bahá'u'lláh, or listen to the decisions of the House of Justice, we
are seeing a divine light filtered by the flaws of our own eye. What we
really see is a product of our own selves, and we may never wholly trust
in such mirages.

What this requires of the believer is faithfulness. Faith is not
properly a noun, as in a place where the heart may dwell. It is an
adjective, describing the terms of our relationship to God. Compare this
to the old saying, "keeping faith", meaning that one remains true to the
spirit of an agreement. Our faith in God means that we trust in the
perfection of His Messenger, and continue to seek the meaning of that
perfection throughout the rest of our lives. It's in believing that
we've "found" what we're looking that we become doomed.

So, if one no longer calls themselves a "Baha'i", I would say bravo. I
have never been a "Baha'i". That word identifies a concept whose meaning
is not only highly personal from day to day, but whose stasis is foreign
to my nature. What I am is a seeker after truth, and I inhale from the
fragrance of Bahá'u'lláh's words the fragrance of truth. This is why I
pursue them, and continue to pursue, hoping to become transformed by an
ever developing understanding and application of His teachings.

And if He commands things beyond my understanding, what then? Do I judge
them according to what I understand so far, or do I surrender my
judgment and follow anyway? And yet, what would I be judging them with,
and what would I be surrendering to? Both options exist within my own
understanding. Both will be wrong. So what is a believer to do?

I guess what I'm saying is that we are always "wrong", but this does not
mean we cannot be faithful. Religion is about love, not absolute truth.
Be true to your heart, be honest, be good as far as you know how -- and
keep at it. I have never aimed at forming the world into a certain
image. I think this is ridiculous. What I do aim at is increasing the
joy in my heart, and being conducive to happiness and the well-being of
society as I understand it. Of course, Bahá'u'lláh's Writings and
Institutions are my guide in this search and I follow them as closely as
I'm able. Yet I will always be wrong in the sense of knowing truth; I
will never be a true follower of my love. Yet I will always have that
love, and the truth of my Beloved One.

So yes, I believe in something I can neither know nor understanding. All
I have to go on is the joy of my pursuit, in much the same way we locate
a fire by following its heat. And yet, whoever said I was looking for
something that could fit within the confines of my mind? Even my own
heart does not fit in such a confined space! What I am seeking is a
mystery whose nature engulfs me; and whenever I'm immersed in its
waters, I feel my purpose -- to know Him, and to worship Him.
