:PROPERTIES:
:ID:       5761F246-C2B5-4E99-94E9-06BE044FE4CA
:SLUG:     a-single-point
:END:
#+filetags: :journal:
#+title: A single point

I have come to believe that all knowledge and understanding derives from
a single Point, and that this Point is so complete, and yet so rarefied,
that although it smacks us in the face at every moment, it remains
unperceived. Bahá'u'lláh wrote:

#+BEGIN_QUOTE
Say: My creatures are even as the leaves of a tree. They proceed from
the tree, and depend upon it for their existence, yet remain oblivious
of their root and origin. We draw such similitudes for the sake of Our
discerning servants that perchance they may transcend a mere plant-like
level of existence and attain unto true maturity in this resistless and
immovable Cause. Say: My creatures are even as the fish of the deep.
Their life dependeth upon the water, and yet they remain unaware of that
which, by the grace of an omniscient and omnipotent Lord, sustaineth
their very existence. Indeed, their heedlessness is such that were they
asked concerning the water and its properties, they would prove entirely
ignorant. Thus do We set forth comparisons and similitudes, that
perchance the people may turn unto Him Who is the Object of the
adoration of the entire creation.[fn:1]

#+END_QUOTE

I think the human mind cannot contain this Point, since there exist no
human concepts concerning its nature. I also believe, however, that the
soul can know it -- and know it intimately -- to the extent that you
would recognize it without hesitation, no matter how strange its form or
appearance. Such as He describes here:

#+BEGIN_QUOTE
Each and every thing, however small, would be to him a revelation,
leading him to his Beloved, the Object of his quest. So great shall be
the discernment of this seeker that he will discriminate between truth
and falsehood even as he doth distinguish the sun from shadow. If in the
uttermost corners of the East the sweet savours of God be wafted, he
will assuredly recognize and inhale their fragrance, even though he be
dwelling in the uttermost ends of the West. He will likewise clearly
distinguish all the signs of God -- His wondrous utterances, His great
works, and mighty deeds -- from the doings, words and ways of men, even
as the jeweller who knoweth the gem from the stone, or the man who
distinguisheth the spring from autumn and heat from cold. When the
channel of the human soul is cleansed of all worldly and impeding
attachments, it will unfailingly perceive the breath of the Beloved
across immeasurable distances, and will, led by its perfume, attain and
enter the City of Certitude.[fn:2]

#+END_QUOTE

If this life is a place of color and form, then the Point of all
knowledge is that Light which, through reflection off of various
objects, bestows on the world those very colors. If all human knowledge
and wisdom is like a wonderful, intricate tapestry, yet it only has
beauty because of that Light shining upon it. If the tapestry were
placed in a cave devoid of the Light, it would appear no different from
the surrounding walls of stone.

Whenever a person has discovered this Light, the meaning and reality of
the various colors is revealed; the entire spectrum makes sense, and is
seen to relate back to its Origin. Nor can the color's brilliance be
confused with the objects which reflects it. It's like in the Seven
Valleys where He wrote:

#+BEGIN_QUOTE
It is clear to thine Eminence that all the variations which the wayfarer
in the stages of his journey beholdeth in the realms of being, proceed
from his own vision. We shall give an example of this, that its meaning
may become fully clear: Consider the visible sun; although it shineth
with one radiance upon all things, and at the behest of the King of
Manifestation bestoweth light on all creation, yet in each place it
becometh manifest and sheddeth its bounty according to the
potentialities of that place.[fn:3]

#+END_QUOTE

If the Sun is the origin of all colors and form, and if the world of
creation is known only through Its Rays, then to adore the Sun is to
find all knowledge wrapped up within it, like the many colors that exist
in the spectrum of the Sun's light. But as I said, the mind cannot do
this, since it knows things only through color and form. The soul, on
the other hand, is a thing of the Light itself -- an emanation from that
very Sun -- so it can learn the language of Light, which then illumines
all the possibilities of color.

This Light, this spiritual essence which dawns on reality through the
Being of the Manifestations of God, reflects throughout time resulting
in the creation of society and the generation of human understanding. To
know Them is to know the origin of all things, and to disregard Them is
to render the various wonders of the universe an impenetrable mystery.

[fn:1] Summons of the Lord of Hosts, para.76

[fn:2] Kitáb-i-Íqán, p.197

[fn:3] Valley of Unity
