:PROPERTIES:
:ID:       1392AD6B-7DFC-4A51-8CCE-4B27E3B20FA8
:SLUG:     self-and-soul
:END:
#+filetags: :journal:
#+title: Self and soul

The following are just some thoughts on the different natures of self
and soul.

By "self" I mean ideas like will, conceptions, immediate desires, etc.,
and by "soul", our spiritual nature, love, virtue, true happiness --
realities that are a bit more difficult to pin down and agree on.

I think that only self has the power to act, and only soul possesses
power in its own being. That is, if self is like a lantern of iron, the
soul appears as the light within. The lantern can be open or closed, but
illumination is dependent on the light -- and happens as a consequence
of the light's nature, not by any intended action.

In order to develop spiritually, the relationship between these two
elements must be worked out; and I've found that in the development of
the self, people seem to go through distinct phases. Some linger in
these phases more than others, and some stop altogether. There are
essentially four of them at the beginning.

In the first phase, the individual is fairly unconscious of their soul,
and ascribes whatever they feel of it as relating to the self. In
consequence, they look only to their selves for their goals and desires,
even if they rarely feel fulfilled in accomplishing them.

In the second phase, the individual becomes aware that they have a soul,
and that its ways and needs are of a different nature than the self.
Self is very direct; it wants a thing, so it reaches for it. The soul is
quite indirect; it seems to prefer situations and qualities that cannot
be directly manipulated. The things that make the soul happy are not
always easy to figure out, and can be damnably hard to predict or
repeat. For example, there are circumstances which can lead to an
ineffable feeling of happiness, as though a gentle light were lifting
you up from underneath, pushing the substance of your being out beyond
the confines of ordinary life. What leads to this feeling is often
beyond calculation, and one may spend years persuing it in vain.

At this stage, when one has become disillusioned by the promises of self
and wishes to capture their "ineffable flame", self is often seen as the
enemy: an obstruction and barrier to the truth of one's soul. The
natural reaction is to wage war against this hateful self; to beat it
into submission with the cudgel of moral authority (as virtue is often
given as the path to clarifying the soul) and fear of consequence if the
individual should fail. After all, what if the barely-glimpsed soul is
lost to the mire of selfishness and vanity forever!

The paradox of this stage is simply, who is waging that war? It is the
very same self. Thus the self, arming itself with a sense of moral
authority, pounds on its own head. Yet this can be quite fruitful, as it
will eventually become educated, and learn through experimentation which
paths attract the soul and which repel it. An uncouth self can learn
about refinement, enforce this message by dint of will, and end up in a
much purer state than when it began.

In the third phase, the self has become fairly well educated. At this
point it is no longer abhorred, and may feel an overweening pride at its
accomplishments. By this time it may have acquired knowledge,
refinement, honesty, forbearance, nobility, and even a bit of modesty.
But none of these qualities can compare to their truer manifestations in
the soul. That is, the soul's nobility is more of an undeniable light,
which has the power to transform hearts; while the self's nobility,
albeit a beautiful thing, may actually result in envy or causing others
to feel ashamed. In brief, soul inspires, but does not measure.

These self-related forms of virtue, while excellent in themselves and a
great step on the way to their true realities, can themselves become a
barrier and a stopping point. Take humility, for example. One cannot
truly strive to become humble, because striving seek for improvement,
whereas humility -- by its nature -- sees itself as ever poorer. That
is, the more humble a person is, the less humble they believe themslves
to be, because that is just what humility is. So how can one strive for
humility if the act of striving to better humility is the same as
gaining distance?

The solution is that real humility can only be gained in the presence of
something greater. And that greater that something, the deeper our
instinctive humility, if we judge it fairly. One can think themselves
extremely knowledgable if surrounded by children; but when they meet a
true master, their own knowledge must convict them of certain ignorance
in comparison.

This leads to the fourth phase of the self's journey: it must stop
focusing on its self. In the first three stages we found it indulging
itself, belittling itself, and improving itself. In this stage it must
set its sights higher, and in consequence recognize the truth of its own
low estate. That is, that its beauty can never compare with the soul's
radiance; that its very substance is like ash next city of pure gold.
That the noblest action of the self is to step aside, and stop blocking
the light.

The best achievements of self are like shadows being cast on a wall,
while even the efficacy of those shadows is a product of the light
behind.

But one will find that this light does not grow brighter just by holding
one's breath and waiting. Turning toward the soul, because it is such an
elusive thing, does not yield to just picking a direction. Soul must be
kindled, the infant light sheltered, the growing blaze fed, and the
resulting light permitted to escape freely. How are these things to be
brought into the field of choice and action, where the self can
accomplish them?

It happens in the same way that one lights a candle, or quenches one's
thirst: the self must carry the individual to where the soul may be
kindled, and then remove itself from intefering with the process. To
seek knowledge, the self must labor, enroll at the university, attend
the classes, and then cease its own clamoring and listen and pay
attention. It must pay heed to the teacher, and not argue every point
based on what it thinks it knows.

In short, the role of the self is like that of a horse: it conveys the
soul to its destination, on and on, as far as the two may go. It must
reach the point that the journey and the destination are the only
realities worth mentioning, and not the skill and endurance, or beauty
and elegance of the horse.

And of all the places that the self can lead the soul to, God -- through
the Manifestations of God, and They through Their Revelation -- is the
greatest of all.
