:PROPERTIES:
:ID:       A72FB548-A920-40B7-813F-F02285E99D1D
:SLUG:     religious-truth
:END:
#+filetags: :journal:
#+title: Religious truth and the Covenant

Religious truth can at times seem obscure and difficult to fathom:

- Can detachment co-exist with caring about someone?
- Does the Unity of God mean transcending the world's variety, or
  relishing in it?
- Would a perfected man savor life, or remain unmoved by its changes and
  chances?
- If I'm human, and told to consider the needs of humanity, why am I
  also told to completely disregard my self? Aren't I human too?
- If the Covenant is just an agreement, why is it spoken of so much?

Despite these conundrums, I think that religious truth is something
universal, which everyone not only /can/ understand, but /already/
understands. By the time a person has reached adulthood, no matter their
culture or background, they have lived through certain, common
experiences relating to each of the divine mysteries. The reason why
these mysteries remain obscure is that we live those truths by a
material context and have yet to translate them into a divine context.
Doing so calls to mind Bahá'u'lláh's words: "One must, then, read the
book of his own self, rather than some treatise on rhetoric."

By a material context, I mean that we understand these principles first
in worldly terms, even if the same truth holds for eternal things as
well. For example, anyone who has fallen in love knows what the love of
God means, even if at first they only know it through loving another
person or thing. The essential truth of love is the transcendant
experience; but moving it beyond the physical is the job of the seeker.

#+begin_html
  <!--more-->
#+end_html

* The mystery of the Covenant
:PROPERTIES:
:CUSTOM_ID: the-mystery-of-the-covenant
:END:
In this sense, I would like to examine the idea of the Covenant. It is
both a specific agreement each believer makes with God, and a real,
living thing. For example:

#+BEGIN_QUOTE
There is, for example, the Greater Covenant which every Manifestation of
God makes with His followers, promising that in the fullness of time a
new Manifestation will be sent, and taking from them the undertaking to
accept Him when this occurs. There is also the Lesser Covenant that a
Manifestation of God makes with His followers that they will accept His
appointed successor after Him. If they do so, the Faith can remain
united and pure. If not, the Faith becomes divided and its force
spent.... It is a Covenant of this kind that Bahá'u'lláh made with His
followers regarding 'Abdu'l-Bahá, and that 'Abdu'l-Bahá perpetuated
through the Administrative Order that Bahá'u'lláh had already
created.[fn:1]

#+END_QUOTE

In this quote, the meaning of "Covenant" is closely tied to the notion
of a pact made between the believers and the Messenger of God. But the
Covenant is not just about these agreements, for we also find:

#+BEGIN_QUOTE
Recite ye the verses of God every morn and eventide. Whoso faileth to
recite them hath not been faithful to the Covenant of God and His
Testament.[fn:2]

#+END_QUOTE

Even though reading the Writings is nowhere specified as a law of God,
or an agreement the believer explicitly makes, yet it has been included
in the notion of obedience to the Covenant of God. This implies that the
Covenant covers a range of topics, and not just those mentioned above.
There are even quotes like this one:

#+BEGIN_QUOTE
Know this for a certainty that today, the penetrative power in the
arteries of the world of humanity is the power of the Covenant. The body
of the world will not be moved through any power except through the
power of the Covenant. There is no other power like unto this. This
Spirit of the Covenant is the real Center of love and is reflecting its
rays to all parts of the globe, which are resuscitating and regenerating
man and illuminating the path to the Divine Kingdom.[fn:3]

#+END_QUOTE

Here the Covenant is very much an active force, animating all of human
life. How can a description like this be expressed in the mere sense of
a "pact or agreement", as the dictionary would have us define a
covenant?

* Bonds of friendship
:PROPERTIES:
:CUSTOM_ID: bonds-of-friendship
:END:
As I mentioned at the beginning, I think each of us already understands
what the Covenant is in a deep, intuitive way. It's just a matter of
identifying which of our material experiences reflects this spiritual
reality.

Consider what happens when you meet someone for the first time and form
a friendship: Something takes place at that moment which forever-after
changes the way you react to that person. A kind of invisible link forms
between you and them, which although tenuous at first, is still very
real to the both of you.

This link, from the moment it's created, comes with some unwritten
rules. For example, if you lie or cheat the other person, it can
diminish the link, or turn it into something unfriendly. Likewise, if
you do selfless things on their behalf, it can greatly strengthen and
improve the bond. There is a whole set of unseen guidelines -- which
don't even need to be said -- concerning the care, feeding and
maintenance of that relationship.

This link is a mini-Covenant. It's always there, feeding the
participants through the medium of their friendship. It's like a third
reality which can grow into something rather astonishing, so long as the
terms of friendship are not violated.

It can even turn into marriage in certain cases. Then the bond becomes
formalized into a written or spoken agreement with legal consequences.
However, despite the increased formality of the arrangement, the
essential nature of the bond is still the same: a tie between
individuals with its own rules, life and benefits. It is up to the
individuals whether they work to strengthen and increase the bond, or
allow it to wither.

* The Covenant of God
:PROPERTIES:
:CUSTOM_ID: the-covenant-of-god
:END:
Looked at this way, the Covenant of God with His followers makes a bit
more sense. In the Qur'án it says that when man is created, he is
brought before God and asked, "Am I not your Lord?", to which each soul
responds "Yea, verily!"[fn:4] However, upon entering the material world,
the soul becomes forgetful of this "first day" and must work its way
back to God. The Bahá'í Writings speak along similar lines:

#+BEGIN_QUOTE
It [the soul] is the first among all created things to declare the
excellence of its Creator, the first to recognize His glory, to cleave
to His truth, and to bow down in adoration before Him. If it be faithful
to God, it will reflect His light, and will, eventually, return unto
Him. If it fail, however, in its allegiance to its Creator, it will
become a victim to self and passion, and will, in the end, sink in their
depths.

#+END_QUOTE

Here we see that the soul's faithfulness determines its progress, in the
same way that faithfulness between friends determines their nearness. So
the word "faith" is not just about believing in something or someone,
but "keeping faith" with them as well. This directly implies that the
Covenant is the channel of one's approach to God. The Guardian wrote:

#+BEGIN_QUOTE
For the core of religious faith is that mystic feeling which unites Man
with God. This state of spiritual communion can be brought about and
maintained by means of meditation and prayer.

#+END_QUOTE

Again we see the image of a link or a bond, and ways to hone that
connection. In Bahá'u'lláh's Writings one sometimes comes across the
term "Urvatu'l-Vuthqá" -- meaning the "Sure Handle", or Cord of God.
Bahá'u'lláh Himself has stated that Urvatu'l-Vuthqá refers to the
Covenant[fn:5], and has even used it to refer to the Verses of God in
general:

#+BEGIN_QUOTE
They [the verses of God] constitute the indissoluble Bond, the firm
Cord, the Urvatu'l-Vuthqá, the inextinguishable Light.[fn:6]

#+END_QUOTE

Thus the Covenant is the "Sure Handle", and the Writings of God, the
"indissoluble Bond". These are the believer's means of returning to God
and fostering that fundamental relationship, that "core of religious
faith".

Consider in this sense the following quote:

#+BEGIN_QUOTE
Say: My creatures are even as the leaves of a tree. They proceed from
the tree, and depend upon it for their existence, yet remain oblivious
of their root and origin.[fn:7]

#+END_QUOTE

This the plight of man: that we are born of God, and are bound to Him by
a mighty Covenant, but most remain unaware, even though all of humanity
is moved by its means.

* The Lesser Covenant
:PROPERTIES:
:CUSTOM_ID: the-lesser-covenant
:END:
In addition to these general and powerful notions of the Covenant of
God, there is also the much more specific Lesser Covenant of God, which
is unique to the Bahá'í Revelation. In this context, the Lesser Covenant
is the believer's agreement with Bahá'u'lláh to follow His successor,
'Abdu'l-Bahá, and any successors He should name, etc. This Covenant is
unique in religious history in that it was written down in the form of a
Will which was read following the passing of Bahá'u'lláh. It provides
for the unity of the Bahá'í community, and prevents the schism of the
Bahá'í Faith into sects claiming equal authority. Much more on this can
be found in the book, "The Covenant of Bahá'u'lláh", by Adib Taherzadeh.

[fn:1] Letter from the Universal House of Justice, dated March 3, 1975,
       to an individual believer

[fn:2] Bahá'u'lláh, The Kitáb-i-Aqdas, K 149, p. 73

[fn:3] 'Abdu'l-Bahá, in The Covenant of Bahá'u'lláh, p. 71

[fn:4] Qur'án, 7:172

[fn:5] http://bahai-library.com/file.php?file=wilmette_lawh_dunya_handle

[fn:6] Bahá'u'lláh, Kitáb-i-Íqán, p. 205

[fn:7] Bahá'u'lláh, The Summons of the Lord of Hosts, para. 76
