:PROPERTIES:
:ID:       4466EE3B-8553-42B0-9FF6-4E31F6D313D9
:SLUG:     its-own-reason
:END:
#+filetags: :journal:
#+title: Its own reason

When you go to a mountain-top to watch the sunset, what is the
objective? And the person who doesn't bother and stays at the bottom of
the hill, what has he lost? Some things are simply beautiful, wonderful,
and deserve attention for no other reason. Truth, beauty, virtue, God:
they deserve to be loved, because they are the essence of what is
lovable. To ask "why" is to miss the point; they are the why! Children
play to play, not to accomplish!

Consider the love relationship, a key analogy: I pursue the woman, I
marry the woman, but why? Is it for the child, the family, for what
comes after? Or is not the whole process its own reason for being? It
happens because it wants to happen; because we desire for it to happen.
There may be, in fact, an "outcome", but this comes later. The
experience itself is the reward.

To pursue religion for a glorious afterlife is like doing something for
the sake of your soul, without knowing why. That is, it's better to walk
up the mountain in ignorance and then enjoy the beauty of the sunset
from the top; but really, God is His own reason for being sought, His
own proof. Spirituality would just be another form of commercial
enterprise otherwise.

Two grammarians, sore athirst, were debating the ways and means of
drinking and of what comes after; until an ignorant man passed them by
and said, "Your thirst should be all the proof you need that drinking is
worthwhile! Cease your ramblings and find the river!"

Or I said to a friend once: "In marriage, you grow and grow together
every day, right?" He said, "Yes." I said, "So, do you stay married for
the sake of some perfect day in the future?" A marriage, if
well-founded, is its own reason for being. Even though it improves all
the time, it is in the /very process of its improving/ that one sees the
purpose.
