:PROPERTIES:
:ID:       00279B96-31C4-4BB7-9555-D1CF9A2F32F1
:SLUG:     translation-of-rashh-i-ama
:END:
#+filetags: :journal:
#+title: Translation of the Rashh-i-`Amá

I've found myself unable to comment on the meaning of Rashh-i-`Amá,
although it seems to be a tremendous song of joy at the event of
Bahá'u'lláh revelation. Instead of commenting directly, I chose to
retranslate the tablet, which in a way feels like writing a commentary.

In some cases the Persian language is like a sweet, sweet wine; putting
it into English is like pouring that wine into clear water. It may
become more easy to drink, but the original flavor is just hinted at in
the result.

#+BEGIN_VERSE
The pre-eternal Reality poureth forth from Our ecstasy!
The secret of fidelity issueth forth from Our song!

From the east, a zephyr wafts the musk of Cathay;
Nay, this gentle breeze doth flow from Our locks!

The adorning Sun dawneth from the countenance of the True One;
Behold the essence of Truth, streaming from the face of Thá!

The sea of purity crieth out as a wave from His Presence;
This token of His favor descendeth from the rapture of Há!

This treasure of Love remaineth hid in the land of Fá;
From this hidden trove of love, the pearl of fidelity gleams!

A joy, as of wine, appeareth at a glance of the Universal Being;
What a beauteous allusion resoundeth from the song of Rá!

A blow from the trumpet! lo, the ecstasy of the Realm on High!
Both manifested by a single breath from the expanse of Heaven!

The age of, "I am He", is made clear through Our Countenance;
The cycle of, "He is He", brimmeth forth as Bá overflows!

The Heavenly Fountain hath appeared in the chalice of the heart,
this honeyed cup poureth forth from the ruby lips of Bahá!

The Day of God entereth into union with its Lord;
This eloquent utterance streameth from the call of Tá!

Behold the overflowing glory! Behold the bestowals of the Divine Cloud!
All these words proceed from but one song, the Melody of God!

Behold the dweller in Eternity! The pure and radiant morn!
Behold the Immaculate Heart, descending from the Most Exalted Throne!

Behold the blessed Palm! Hearken to the nightingale's song!
Hear the intonation of the Most Glorious, alight with such purity!

Take note of the Arabian song, and of the Persian drum!
Behold the Divine Hand, resounding with the peal of Negation!

Behold the Immortal Face! Behold the Supernal Maid of Heaven!
Behold the mortal adornment, which issueth from the Primal Will!

Behold the Everlasting Countenance! Behold the face of the Cup-Bearer!
Behold the crystal-clear daught, flowing from Our chalice!

Behold the Fire of Moses! Behold the white, resplendant light!
Behold the bosom of Sinai, shining forth from the Glowing Hand!

Hear the sighs of the drunkards! Witness the state of the bondslaves!
Behold the ecstasy of those truly alive, born of that First Meeting!

Witness the allure of Há! Know the enticements of Bá!
Hear the music of Fá, which floweth from the pen of Bahá!

This is the overflowing Revelation, the cleansing of the Supernal Cloud;
The melodies of birds are these, sprung from the fount of Renunciation.
#+END_VERSE
