:PROPERTIES:
:ID:       21746661-1E05-4256-BBA9-9D3F18512444
:SLUG:     turn-thereunto
:END:
#+filetags: :journal:
#+title: Turn thereunto

Today's entry is about a word that appears in the Bahá'í Writings:
/tawajjuh/, or "attention".

This word is still in common use, and means "attention", "focus" or
"turning toward". The root it stems from is /wajh/: "face" or
"countenance". The form /tawajjuh/ is a verbal noun with the literal
meaning of "facing". Thus, the meaning of "attention" comes from the
idea of having one's face directed at something.

#+begin_html
  <!--more-->
#+end_html

Both this word and its root are found often in Islam. /Wajh/ is seen in
the phrases "the Face of God", and "the Countenance of the Lord"; and
also in the phrase "turn thy face unto thy Lord", which sometimes is
expressed using /tawajjuh/ and sometimes by a verb in combination with
/wajh/.

In fact, any word that is significant in Sufism can be traced back to
one or more verses from the Qur'án. /Wajh/ occurs many times, and
/tawajjuh/ can be seen here:

#+begin_html
  <p>
#+end_html

#+begin_html
  <table width="90%" border="0" cellspacing="3" cellpadding="2">
#+end_html

#+begin_html
  <tr>
#+end_html

#+begin_html
  <td>
#+end_html

And then, as he turned himself (tawajjuh) toward the land of Midian, he
said: "Perchance my Lord will lead me to the Straight Path" (Qur'án
28:22)

#+begin_html
  </td>
#+end_html

#+begin_html
  <td align="right" class="persian">
#+end_html

وَلَمَّا تَوَجَّهَ تِلْقَاء مَدْيَنَ قَالَ عَسَى رَبِّي أَن يَهْدِيَنِي سَوَاء السَّبِيلِ

#+begin_html
  </td>
#+end_html

#+begin_html
  </tr>
#+end_html

#+begin_html
  </table>
#+end_html

#+begin_html
  </p>
#+end_html

This concept of turning towards God lies at the very core of mystical
practice. In fact, it might be called a pivot of sorts. In the Writings
of the Báb (/Risalah fi's-Sulúk/) he distinguishes Paradise and
Hell-fire as the difference between being /tawajjuh/ toward God, or
regarding one's own self:

#+begin_html
  <p>
#+end_html

#+begin_html
  <table width="90%" border="0" cellspacing="3" cellpadding="2">
#+end_html

#+begin_html
  <tr>
#+end_html

#+begin_html
  <td>
#+end_html

Indeed, the world and the hereafter are but two stations. If you turn to
God (tawajjuh), exalted be He, then you are in paradise; but if you
remain intent upon (na.zar) your own self, then you are in the fire and
in the world.

#+begin_html
  </td>
#+end_html

#+begin_html
  <td align="right" class="persian">
#+end_html

فانّ الدّنیا والآخرة حالتان ان کان توجّهك باللّه تعالى فانت في الجنّة و ان
کان نظرك الی نفسك فانت في النّار و في الدّنیا

#+begin_html
  </td>
#+end_html

#+begin_html
  </tr>
#+end_html

#+begin_html
  </table>
#+end_html

#+begin_html
  </p>
#+end_html

Bahá'u'lláh, in His /Seven Valleys/, describes a spiritual station where
once the traveler's self has been "blacked out" (حالک شدن), the only
thing remaining will be the "Face of thy Lord" (/wajh/):

#+begin_html
  <p>
#+end_html

#+begin_html
  <table width="90%" border="0" cellspacing="3" cellpadding="2">
#+end_html

#+begin_html
  <tr>
#+end_html

#+begin_html
  <td>
#+end_html

This is the plane whereon the vestiges of all things are destroyed in
the traveler, and on the horizon of eternity the Divine Face riseth out
of the darkness, and the meaning of "All on the earth shall pass away,
but the face of thy Lord..." is made manifest.

#+begin_html
  </td>
#+end_html

#+begin_html
  <td align="right" class="persian">
#+end_html

و اين مقام است که کثرات کلّ شيء در سالک هالک شود و طلعت وجه از مشرق بقا
سر از غطا بيرون آورد و معنی « کُلِّ شَيْئٍ هَالَکْ اِلَّا وَجْهِهُ » مشهود گردد

#+begin_html
  </td>
#+end_html

#+begin_html
  </tr>
#+end_html

#+begin_html
  </table>
#+end_html

#+begin_html
  </p>
#+end_html

In this case it might be interesting to look at a more literal
translation of Bahá'u'lláh's words. I'll point out certain of them which
may become the focus of future entries:

#+BEGIN_QUOTE
This is a station (*maqám*) in which the plenitude of all things (*kullu
shay'*) are blacked out in the wayfarer (*sálik*); and the appearance of
the Face (*wajh*), rising from the dawn of eternity (*baqá*), comes out
from behind the veil; and the meaning of "All things (*kullu shay'*) are
pitch-black except for His Face (*wajh*)" (cf. Qur'án 55:26-7) is made
manifest.

#+END_QUOTE

This builds on a theme which recurs often in the Writings: That man is a
mystery, and the fulfillment of that mystery is found by turning towards
God (/tawajjuh/) so utterly that one becomes forgetful of his own self.
It is not that the self is destroyed, but rather it fades into darkness
before the bright light of His Countenance (/wajh/).

An analogy may help here: A car driver who is intent on winning a race
cannot be focused on his vehicle, rather the whole of his mind must be
outside it: on the track and the goal. This does not imply a neglect of
the car or its maintenance. Such a car is much better maintained than
most. The point is that striving for success must consume every aspect
of the driver's attention, or else he will miss the whole point of being
there.

Likewise, the mystic traveler (/saalik/) strives for a condition of
self-nothingness (/faná/) the flip-side of which might be called
"God-everythingness" (/baqá/). It is like the fading away of a tiny
light in the presence of a much brighter one -- a candle before the
everlasting Sun.

This act of turning from the self to the Divine is expressed by
/tawajjuh/, though in other contexts it has been described as a series
of "steps", the steps one takes in the journey from self to God. This
particular interpretation is mentioned by Bahá'u'lláh a text not yet
translated (errors are my own), found in /Má'idiyyih Ásmání/, Vol.8,
pp.21-22:

#+BEGIN_QUOTE
He saith, exalted be He: O Muhammad-Taqí! Upon thee be My glory and My
mercy! Today the king of all knowledge is the recognition of God. Every
soul who acknowledgeth and confesseth His oneness is numbered with the
people of Bahá, the companions of the Crimson Ark, who have been
inscribed in the Book of Names by the Most Exalted Pen.

In one of Our divinely-revealed Tablets, these verses have been sent
down: "In the first step, he who hath turned his face toward God must
labor to observe the following weighty verse: 'Say: It is God; then
leave them to entertain themselves with their cavilings.' (Qur'án 6:91)
In the second step, he must hold fast to and meditate upon this blessed
verse: 'I have abandoned the ways of those who disbelieve in God and who
deny the life to come' (Qur'án 12:37). The meaning intended by"step” in
both these stages is "turn thereunto". Blessings be unto the wise.

#+END_QUOTE

#+begin_html
  <blockquote>
#+end_html

#+begin_html
  <p class="persian">
#+end_html

قوله تعالی: یا محمد تقی علیك بهائی و عنایتی امروز سیّد عرفان عرفان الله
بوده هر نفسی بواحدیتش مقر و معترف شد اواز اهل بهاء و اصحاب سفينه حمراء
در کتاب اسماء از قلم اعلی مرقوم و مسطور در یکی از صحيفه های منزله اين
آیات نازل در اول قدم مقبل الی الله باید باین ایه کبری ناظر و عامل باشد
قُلِ اللّٰهُ ثُمَّ ذَرْهُمْ فِي خَوْضِهِمْ یَلْعَبُونَ و در قدم ثابی باين آیه مبارکه تمسك نماید
و تلاوت کند تَرَكْتُ مِلَّةَ قَوْمٍ لاَّ يُؤْمِنُونَ بِاللّهِ وَهُم بِالآخِرَةِ هُمْ كَافِرُونَ و مقصود
از قدم در اين مقامات توجه است طوبن للعارفين

#+begin_html
  </p>
#+end_html

#+begin_html
  </blockquote>
#+end_html

This concept of "steps" is expressed in the /Seven Valleys/ as well:

#+begin_html
  <p>
#+end_html

#+begin_html
  <table width="90%" border="0" cellspacing="3" cellpadding="2">
#+end_html

#+begin_html
  <tr>
#+end_html

#+begin_html
  <td>
#+end_html

...but the severed wayfarer -- if invisible confirmation descend upon
him and the Guardian of the Cause assist him -- may cross these seven
stages in seven steps, nay rather in seven breaths, nay rather in a
single breath, if God will and desire it.

#+begin_html
  </td>
#+end_html

#+begin_html
  <td align="right" class="persian">
#+end_html

سالک منقطع را اگر اعانت غيبی برسد و ولی امر مدد فرمايد اين هفت رتبه را
در هفت قدم طی نمايد بلکه در هفت نفس بلکه در يک نفس اذا شاءْ الله

#+begin_html
  </td>
#+end_html

#+begin_html
  </tr>
#+end_html

#+begin_html
  </table>
#+end_html

#+begin_html
  </p>
#+end_html

If these Seven Valleys can be described as seven steps, and if by step
is meant /tavajjuh/, the following quotation becomes somewhat clearer:

#+BEGIN_QUOTE
It is clear to thine Eminence that all the variations which the wayfarer
in the stages of his journey beholdeth in the realms of being, proceed
from his own vision (*na.zar*).

#+END_QUOTE

Here the word for vision is "na.zar", which also means "eyesight",
"look", "glance", "outlook", "view", etc. -- meanings similar to
/tavajjuh/. In fact, in the quote of the Báb's above, both words are
used to describe the traveler's inner orientation. This "crux of vision"
is also found in quotations such as the following, from Gleanings
(p.276):

#+BEGIN_QUOTE
Know ye that by "the world" is meant your unawareness of Him Who is your
Maker, and your absorption in aught else but Him. The "life to come," on
the other hand, signifieth the things that give you a safe approach to
God, the All-Glorious, the Incomparable. Whatsoever deterreth you, in
this Day, from loving God is nothing but the world.

#+END_QUOTE

It would seem, then, that reality from the perspective of the wayfarer
is divided into two parts: "the world" and "the hereafter", where the
former is whatever draws us away from God, and the latter is whatever
brings us nearer. The principle spiritual act, then, is turning away
from one in order to turn toward the other, or /tavajjuh/. It is
critical to note that in this act there is both a negative and a
positive component: In order to turn toward something, we must turn away
from something else -- but also, the only reason for denying the world
is /in order to turn towards God/.

The dual nature of this act, that it implies turning away at the same
time as turning toward, has in the past caused mystics to confound the
two. For example, they became so involved in the act of denying the
world, that they sometimes lost sight of the purpose of that denial.
Others became so inebriated by the joys of turning toward God, that they
neglected the necessities of law and restraint.

In Bahá'u'lláh's /Hidden Words/, He gives a few guidelines with respect
to this dual vision of ours, regarding the essential act of "turning
towards":

#+BEGIN_QUOTE
O Man of Two Visions! Close one eye and open the other. Close one to the
world and all that is therein, and open the other to the hallowed beauty
of the Beloved.

O Son of Dust! Blind thine eyes, that thou mayest behold My beauty; stop
thine ears, that thou mayest hearken unto the sweet melody of My voice;
empty thyself of all learning, that thou mayest partake of My knowledge;
and sanctify thyself from riches, that thou mayest obtain a lasting
share from the ocean of My eternal wealth. Blind thine eyes, that is, to
all save My beauty; stop thine ears to all save My word; empty thyself
of all learning save the knowledge of Me; that with a clear vision, a
pure heart and an attentive ear thou mayest enter the court of My
holiness.

#+END_QUOTE

Thus the act of "closing" and "blinding" must be paired with another act
of "opening" and beholding. Although blindness usually means the
complete lack of sight, in this sense material blindness produces
spiritual sight; losing one thing results in the discovery of something
far greater.

In the original text, "O Man of Two Visions" is literally stated as "O
Possessor of Two Eyes", and these two eyes are named by Bahá'u'lláh in
other places as the "outward, manifest eye" (/chasm-i-.zaahir/), and the
"inward, hidden eye" (/chasm-i-baa.tin/). By these two eyes we have the
capacity to behold the fullness of God's Creation, since He is both "The
Most Manifest of the Manifest" and "The Most Hidden of the Hidden". In
this connection, the mystic Ibnu'l-`Arabí wrote:

#+BEGIN_QUOTE
Then know that Allah has described Himself as the Outwardly Manifest and
the Inwardly Hidden. He brought the universe into existence as a Visible
world and an Unseen world so that we might know the Hidden by the Unseen
and the Manifest by the Visible.

#+END_QUOTE

Since the visible world is so immediately compelling, it is quite
possible for people to deny completely even the /existence/ of the
unseen world. This is why we must close, or blind, the outer eye in
order that the inner eye may be opened.

This point is made in the Seven Valleys using the story of Jacob and
Joseph. This story is found in the book of Genesis, chapters 37-50, and
the Qur'án, chapter 12. In the Qur'ánic version of the story, Joseph
gives his brothers a garment to take back to his father. By smelling
this garment, Jacob recognizes that his beloved son is still alive, and
it restores his sight: "Then when the bearer of the good news came, He
cast (the shirt) over his [Jacob's] face, and he forthwith regained
clear sight" (Qur'án 12:96). (In the Biblical version of the story,
Jacob is only told that Joseph is still alive, and believes it by seeing
the goods his sons brought back from Egypt). Now contrast the above with
this statement from Bahá'u'lláh:

#+begin_html
  <p>
#+end_html

#+begin_html
  <table width="90%" border="0" cellspacing="3" cellpadding="2">
#+end_html

#+begin_html
  <tr>
#+end_html

#+begin_html
  <td>
#+end_html

... and until, like Jacob, thou forsake thine outward eyes
(/chasm-i-.zaahir/), thou shalt never open the eye of thine inward being
(/chasm-i-baa.tin/);

#+begin_html
  </td>
#+end_html

#+begin_html
  <td align="right" class="persian">
#+end_html

و تا چون يعقوب از چشم ظاهری نگذری چشم باطن نگشائی

#+begin_html
  </td>
#+end_html

#+begin_html
  </tr>
#+end_html

#+begin_html
  </table>
#+end_html

#+begin_html
  </p>
#+end_html

Then if we have two eyes -- an outer and an inner -- and if we are to
turn from one to the other, and this turning is accomplished by a series
of steps, then consider anew this verse at the beginning of the Valley
of Love:

#+begin_html
  <p>
#+end_html

#+begin_html
  <table width="90%" border="0" cellspacing="3" cellpadding="2">
#+end_html

#+begin_html
  <tr>
#+end_html

#+begin_html
  <td>
#+end_html

And if, by the help of God, he findeth on this journey a trace of the
traceless Friend, and inhaleth the fragrance of the long-lost Joseph
from the heavenly messenger, he shall straightway step into the Valley
of Love and be dissolved in the fire of love.

#+begin_html
  </td>
#+end_html

#+begin_html
  <td align="right" class="persian">
#+end_html

و اگر در اين سفر باعانت باری از يار بينشان نشان يافت و بوی يوسف گمگشته
از بشير احديّه شنيد فوراً بوادی عشق قدم گذارد و از نار عشق بگدازد

#+begin_html
  </td>
#+end_html

#+begin_html
  </tr>
#+end_html

#+begin_html
  </table>
#+end_html

#+begin_html
  </p>
#+end_html

Here we see the notion of "step" used in conjunction with the story of
Jacob, this time referring the seeker himself, where the "step" is
enacted by inhaling the fragrance of Joseph -- an act which, in the
Qur'án, restores Jacob's sight and convinces him that his son is still
alive. This sight which is restored in the seeker is the
/chasm-i-baa.tin/, or inward vision. But how can the opening of our
inward vision lead to "turning toward" God?

#+begin_html
  <p>
#+end_html

#+begin_html
  <table width="90%" border="0" cellspacing="3" cellpadding="2">
#+end_html

#+begin_html
  <tr>
#+end_html

#+begin_html
  <td>
#+end_html

Turn thy sight unto thyself, that thou mayest find Me standing within
thee, mighty, powerful and self-subsisting.

#+begin_html
  </td>
#+end_html

#+begin_html
  <td align="right" class="persian">
#+end_html

فَأَرْجِعِ الْبَصَرَ إِلَيْكَ لِتَجِدَني فِيكَ قائِماً قادِراً مُقْتَدِراً قَيُّوماً

#+begin_html
  </td>
#+end_html

#+begin_html
  </tr>
#+end_html

#+begin_html
  </table>
#+end_html

#+begin_html
  </p>
#+end_html

The word for sight in this text is /ba.sar/, which can also mean
"vision", "look", "perception", etc. So the purpose of /tavajjuh/ -- of
all these "steps" and stages and stations -- is to discover God.

But there is more to the analysis of this act of turning. On the one
hand we have the negative aspect: the turning away from the world, the
closing of the outward eye, the blinding ourselves to all but God. The
fulfillment of this action describes a spiritual state called /faná/, or
"utter nothingness". Bahá'u'lláh used a verb above in connection which
literally means "being blacked out". The poet Rumi has describes it as
the circumstance of a candle brought before the daytime sun: it simply
vanishes. Yet since /faná/ is only the "closing" of the outer eye, it
has a definite beginning and an end, and represents a finite reality of
limited duration.

On the other hand, we have the Object of the turning and the positive
aspect of the journey. This is the turning towards God, the opening of
the inward eye, the beholding of the richness of the Ancient Beauty.
This condition is called /baqá/ (roughly meaning "eternity" and
"paradise"), but it is not finite. It has a beginning but no end, since
it is but the seeker's first entrance to the Divine Realm.

Because this turning happens upon a pivot, the accomplishment of /faná/
is linked to the achievement of /baqá/. This creates two journeys for
the seeker: The first, of finite duration, is the closing of the outward
eye. This is the "journey to God", in which the seeker is mostly blind
to His reality, but dimly senses it and is inflamed by its promise. The
second journey, starting from /baqá/, is called the "journey in God",
and is without limit as God is without limit.

It more basic terms, /faná/ is mortal poverty, and /baqá/ is immortal
wealth. And the theme of becoming impoverished to discover true wealth
is found again and again. I'll end this entry with the following from
Bahá'u'lláh's /Seven Valleys/ again, since it ties together some of
themes of this entry:

#+BEGIN_QUOTE
O thou dear one! Impoverish thyself, that thou mayest enter the high
court of riches; and humble thy body, that thou mayest drink from the
river of glory, and attain to the full meaning of the poems whereof thou
hadst asked.

Thus it hath been made clear that these stages depend on the vision of
the wayfarer....

#+END_QUOTE

It should be noted that this final sentence could perhaps be more
accurately be translated as: "Thus it is now known that these stages are
dependent on the seeker's own travels [to go see things]." That is, none
of these stations will be found or seen if the seeker does not undertake
himself to find them.
