:PROPERTIES:
:ID:       32AA8DD9-8F82-4182-BE10-3A6DEDFA284C
:SLUG:     human-reality
:END:
#+filetags: :journal:
#+title: Human reality

If human reality is a mirror, then it only shines because of the sun
appearing within it. A painting's beauty is only revealed because of
light within the room. The /quality/ of anything derives from a Source
other than that thing itself.

If we look to ourselves, what we find worthy of attention is Him;
otherwise, alone, we would be like corpses without life. Life is from
Him, and of Him, and a manifest sign of His handiwork.

In a sense, it means that the very act of contemplating God is to
witness the agency of God, in the same way that being able to see and
ponder a physical thing is to bear witness to the light which makes such
vision possible.

Put another way, my human reality is a like lamp, which God has filled
with oil. Now, in a dark room, devoid of light, my nature is
indistinguishable from everything else. That is, by myself I have no
visible existence. But then God kindles a flame within me. This is made
possible because He has endowed human nature with certain
potentialities.

Once I am lit, I manifest qualities which are not akin to my
lamp-nature, but resemble Another nature: light, heat, illumination.
These qualities, which originate from the Sun, are, to a reduced degree,
apparent in me. In this sense God's qualities appear with me, and I am
"made in His image".

If I look within myself, and see this light, then I am seeing Him, not
myself; for of my own nature there is nothing to be seen. That is, I
cannot exist without His light. If that light should go out, my being
would vanish. We have no existence apart from Him, and so /the
appearance of our reality is a revelation of His/. If we see ourselves
in these terms, we should see God within us, for if He is Light, every
lantern is His dawning place.

Another metaphor to describe what I'm aiming at is to compare ourselves
with a painting. Alone, a painting is just paper and pigment. It has no
beauty, no form. Only when the Master Artist takes up both, and reshapes
them according to His Own design, does the painting achieve an exalted
station. If the painting could then regard itself, it would see the hand
of the Master evident upon it, and know the majesty of its Creator.

#+BEGIN_QUOTE
O Son of Spirit! I created thee rich, why dost thou bring thyself down
to poverty? Noble I made thee, wherewith dost thou abase thyself? Out of
the essence of knowledge I gave thee being, why seekest thou
enlightenment from anyone beside Me? Out of the clay of love I molded
thee, how dost thou busy thyself with another? Turn thy sight unto
thyself, that thou mayest find Me standing within thee, mighty, powerful
and self-subsisting.

#+END_QUOTE

To me, this Hidden Word is saying: Recognize the greatness of God's
having created man; perceive human reality with a clear eye, and witness
how God has made him the dawning place of His names and attributes, and
we are therefore the very means by which we know Him. Love, beauty,
justice, grandeur: all these require human hearts, and human minds, to
become known. He has created us to this end: that we be His mirrors in
the world of creation. Thus we are both proof, sign and evidence; seeker
and sought; end and beginning.

The material world is a scroll. We are ink, which God has traced upon
that scroll, to reveal His intent. If, therefore, we look upon
ourselves, we will see His Hand reflected there.
