:PROPERTIES:
:ID:       E3E9A0E1-5B3D-43CD-B1B0-C4A3449490FD
:SLUG:     the-iceberg-principle
:END:
#+filetags: :essays:
#+title: The Iceberg Principle

There is an interesting dynamic in our Faith between what we "do". and
what we "accomplish". Our doings occur in this world -- where they can
be seen, measured and reflected upon -- but our true accomplishments
occur in the spiritual world, invisibly and by mystical means.

If we define "mystical" as relying on an unfathomable system to produce
practical results, our Faith is deeply so. How often have seeming
failures translated into success, or apparent successes petered away.
This world, in which we interact, is only the tip of an enormous
iceberg, whose movement and structure remains invisible beneath the
waves.

While this can be a confounding truth, it is also a hopeful one, because
this System not only desires us to succeeds, it actively cooperates.
Each step we take is answered by a thousand in response. Every activity
undertaken out of love and obedience to the Institutions is met with
assistance by unseen hosts. A single prayer can affect an entire
cluster; a devotional meeting, no matter how well attended, is an embryo
of the Mashriqu'l-Adhkár.

What this means is that we cannot judge success or failure by what we
see alone. In fact, these are the least part of our service to the
Faith. Since they define the pattern of our interaction, they are a
necessary part of reflection, consultation and learning; but they are
only the tip of the iceberg. Our hopes should rest on that deeper
element -- which is to say, our hopes should rest on God alone,
independent of the world of seeming.

#+BEGIN_QUOTE
O Man of Two Visions! Close one eye and open the other; close one to the
world and all that is therein, and open the other to the hallowed beauty
of the Beloved.

#+END_QUOTE

The plans of men are hopeful, but the plans of the Universal House of
Justice are ordained to transform all civilization. This is due to the
mystical Force enlivening their activities, and attending our efforts to
fulfill them. This is the well-spring of encouragement, where an atom is
in fact a sun, and a gnat an eagle. When a lone believer undertakes to
start a study circle, that action begets this Spirit, and begins a
fundamental change in the cluster As we labor to bring it to fruition,
it becomes a beacon attracting the breaths of the Holy Spirit. In fact,
the form of effort is somewhat secondary; it is the spirit it generates
that carries the power to renew the world.

The mystic thus challenges himself to awaken his vision to this dynamic,
and to transform his outlook, behavior, and emotional "baseline". The
Kingdom of God is taking shape on this earth beneath a veil of mystery,
and its construction is steady and certain. Each brick we lay produces
an edifice there; every holy syllable we utter reverberates invisibly in
pealing tones. Thus, whenever activities seem low, or the friends
discouraged, think of the iceberg. It may appear tiny and ineffectual
above; but in reality it is a leviathan of the fathomless deeps.
