:PROPERTIES:
:ID:       03B3F8AA-C088-4B30-8EA2-8DC2DB10E3EF
:SLUG:     souls-that-have-always-been
:END:
#+filetags: :essays:
#+title: Souls that have always been

I have always wondered about the meaning of this selection from "The
Hidden Words":

#+BEGIN_EXAMPLE
O My Friends! Have ye forgotten that true and radiant morn, when in those
hallowed and blessed surroundings ye were all gathered in My presence
beneath the shade of the tree of life, which is planted in the
all-glorious paradise? Awe-struck ye listened as I gave utterance to these
three most holy words: O friends! Prefer not your will to Mine, never
desire that which I have not desired for you, and approach Me not with
lifeless hearts, defiled with worldly desires and cravings. Would ye but
sanctify your souls, ye would at this present hour recall that place and
those surroundings, and the truth of My utterance should be made evident
unto all of you.
#+END_EXAMPLE

Recently I was reading the book "Gate of the Heart", by Nader Saidi,
where he quotes the following from the Báb, regarding His first
believers, the Letters of the Living:

#+BEGIN_EXAMPLE
Further, there can he no doubt that they [the Letters of the Living] were
the first Lights who bowed down before God, accepted the verses He hath
revealed unto His Báb, and proclaimed them to the world.... They are the
lights which in the past have eternally prostrated themselves and will
prostrate themselves eternally in the future, before the celestial
throne.... In each Dispensation, they are called by different names
amongst the people, and in each Revelation, their individual names are
also changed. Yet, the names of their inmost realities, which refer unto
God, are manifest in their hearts.[1]
#+END_EXAMPLE

This led me to wonder whether humans are possessed of two stations: our
outward, individual station; and an inward, potential, pre-existent
station, that we are born to through faith. That is, outwardly we are
unique and transitory: but inwardly we may attain to a station that has
always existed and will always exist, by acquiring the characteristics
and qualities of that station.

This led me to a verse from the Kitáb-i-Íqán, by Bahá'u'lláh:

#+BEGIN_EXAMPLE
Therefore, those who in every subsequent Dispensation preceded the rest of
mankind in embracing the Faith of God, who quaffed the clear waters of
knowledge at the hand of the divine Beauty, and attained the loftiest
summits of faith and certitude, these can be regarded, in name, in
reality, in deeds, in words, and in rank, as the 'return' of those who in
a former Dispensation had achieved similar distinctions. For whatsoever
the people of a former Dispensation have manifested, the same hath been
shown by the people of this latter generation. Consider the rose: whether
it blossometh in the East or in the West, it is none the less a rose. For
what mattereth in this respect is not the outward shape and form of the
rose, but rather the smell and fragrance which it doth impart.[2]
#+END_EXAMPLE

And similarly, 'Abdu'l-Bahá writes:

#+BEGIN_EXAMPLE
For example, there was a flower last year, and this year there is also a
flower; I say the flower of last year has returned. Now, I do not mean
that same flower in its exact individuality has come back; but as this
flower has the same qualities as that of last year -- as it has the same
perfume, delicacy, color and form -- I say the flower of last year has
returned, and this flower is the former flower. When spring comes, we say
last year's spring has come back because all that was found in last year's
spring exists in this spring. That is why Christ said, "You will see all
that happened in the days of the former Prophets."[3]
#+END_EXAMPLE

Is this, perhaps, the "sovereignty" that is "ancient, imperishable and
everlasting", mentioned in the first Hidden Word? Or when the Seven
Valleys says, "the bird of thy soul shall recall the holy sanctuaries of
preexistence"?

Can we, by purifying our hearts and attaining to true faith, "remember"
and attain a pre-existent reality which, throughout time, has been a
servant of the Prophets? Not in the sense of reincarnation, but of
fulfilling a role that has always existed, even if the individual souls
playing its part continually change.

#+BEGIN_EXAMPLE
Bring then into being, by Our leave, resplendent mirrors and exalted
letters that shall testify to Thy sovereignty and dominion, bear witness
to Thy might and glory, and be the manifestations of Thy Names amidst
mankind. We have caused Thee again to be the Origin and the Creator of all
mirrors, even as We brought them forth from Thee aforetime.[4]
#+END_EXAMPLE

The rose in my garden may whither and die; but the qualities of the rose
have adorned poetry and artwork for as long as history, and likely
always will. What life is more eternal than this, transcending both time
and place?

Footnotes: [1] Nader Saidi, The Gate of the Heart, pp.271-272

[2] Bahá'u'lláh, Kitáb-i-Íqán, pp.158-159

[3] `Abdu'l-Bahá, Some Answered Questions, p.133

[4] Bahá'u'lláh, Summons of the Lord of Hosts, para.82
