:PROPERTIES:
:ID:       1EFDADC0-75B2-4A5E-9BB3-406F2ADE21E2
:SLUG:     in-him-we-are-the-sea
:END:
#+filetags: :journal:
#+title: In Him, we are the sea

I think the most profound communication of one's love for God lies in
complete and radiant acceptance of others, until they feel the warmth of
our affection. It doesn't need to be a communication of ideas or
concepts; the unity of God is best preached by seeing the goodness in
others, independent of all earthly differences, and acting with this
awareness. The more complete such a vision becomes, the more it evolves
toward an inclusive experience of God, until "turning one's heart toward
God" no longer implies turning away from the world, but only what would
narrow the heart again.

#+BEGIN_QUOTE
For on this plane the traveler witnesseth the beauty of the Friend in
everything. Even in fire, he seeth the face of the Beloved. He beholdeth
in illusion the secret of reality, and readeth from the attributes the
riddle of the Essence. For he hath burnt away the veils with his
sighing, and unwrapped the shroudings with a single glance...

#+END_QUOTE

For example, we might interpret "everything" as the world around us;
"fire" as those characteristics that jar and annoy; "illusion", the
specious and transitory distinctions between people; "attributes" their
worldly qualities; the "veils", a cloak of manyness obscuring the One;
and "shroudings", the common perception that my neighbor is not my own,
truest self. Without God, we live alone, islands of our own making; in
Him, we are the sea.
