:PROPERTIES:
:ID:       620EE6B1-24AA-4940-AC81-FA14E11A928D
:SLUG:     four-valleys-as-an-independent-tablet
:END:
#+filetags: :journal:
#+title: Four Valleys as an independent tablet

As I read the Four Valleys, it gives me the impression that, like the
Seven Valleys seems to do, it depicts a series of relationships that
believers develop with the Manifestation of God. In particular it
reminds me of this Hidden Word:

#+BEGIN_QUOTE
O Son of Man! Write all that We have revealed unto thee with the ink of
light upon the tablet of thy spirit. Should this not be in thy power,
then make thine ink of the essence of thy heart. If this thou canst not
do, then write with that crimson ink that hath been shed in My path.
Sweeter indeed is this to Me than all else, that its light may endure
for ever.

#+END_QUOTE

Each Valley seems to describe a different degree of sacrifice. In the
first Valley, the believer sacrifies himself: his substance, energy,
effort, even his life. In the second Valley, the believer sacrifies his
mind: thoughts, opinions, notions of Truth. In the third Valley, he
sacrifices his heart: all that he cares for, every hope and goal now
culminates in the Beauty of God. And in the fourth Valley he sacrifices
his very self, until nothing else remains but consciousness of the
Friend.
