:PROPERTIES:
:ID:       FEF7256D-994C-4B44-B809-738E8C135099
:SLUG:     perceiving-with-divine-insight
:END:
#+filetags: :journal:
#+title: Perceiving with divine insight

[WARNING] Note with key '3' defined at line 105 column 1 but not used.
In the Seven Valleys, each Valley depicts a different world-view.
Bahá'u'lláh states:

#+BEGIN_QUOTE
Thus it hath been made clear that these stages depend on the vision of
the wayfarer. In every city he will behold a world, in every Valley
reach a spring, in every meadow hear a song.[fn:1]

#+END_QUOTE

To have knowledge of each Valley is not enough. One cannot comprehend it
from the outside. To be a "wayfarer" is a question of residence, not
familiarity.

In Persian there are two words commonly used for knowledge, 'Ilm and
'Irfán. They are as different as studying about the ocean, and swimming
in it.

#+begin_html
  <!--more-->
#+end_html

The translation "valley of knowledge" is not really accurate, given our
common meaning of the word. The Persian text says "Ma‘rifat"; which my
dictionary translates as meaning "insight into divine matters" (the word
is derived from 'Irfán, which can mean wisdom or insight).

It means that those in the valley of knowledge have come to fully
appreciate and trust God's planning. This is no simple matter. Even
Moses failed this test, as Muhammad relates in the story of Khidr:

#+BEGIN_QUOTE
So [Moses] found one of Our servants (Khidr), on whom We had bestowed
Mercy from Ourselves and whom We had taught /knowledge/ from Our own
Presence.

Moses said to him: "May I follow thee, on the footing that thou teach me
something of the (Higher) Truth which thou hast been taught?"

(The other) said: "Verily thou wilt not be able to have patience with
me!"

"And how canst thou have patience about things about which thy
understanding is not complete?"

Moses said: "Thou wilt find me, if God so will, (truly) patient: nor
shall I disobey thee in aught."

The other said: "If then thou wouldst follow me, ask me no questions
about anything until I myself speak to thee concerning it."

So they both proceeded: until, when they were in the boat, he scuttled
it. Said Moses: "Hats thou scuttled it in order to drown those in it?
Truly a strange thing hast thou done!"

He answered: "Did I not tell thee that thou canst have no patience with
me?"

Moses said: "Rebuke me not for forgetting, nor grieve me by raising
difficulties in my case."

Then they proceeded: until, when they met a young man, he slew him.
Moses said: "Hats thou slain an innocent person who had slain none?
Truly a foul (unheard of) thing hast thou done!"

He answered: "Did I not tell thee that thou canst have no patience with
me?"

(Moses) said: "If ever I ask thee about anything after this, keep me not
in thy company: then wouldst thou have received (full) excuse from my
side."

Then they proceeded: until, when they came to the inhabitants of a town,
they asked them for food, but they refused them hospitality. They found
there a wall on the point of falling down, but he set it up straight.
(Moses) said: "If thou hadst wished, surely thou couldst have exacted
some recompense for it!"

He answered: “This is the parting between me and thee: now will I tell
thee the interpretation of (those things) over which thou wast unable to
hold patience.

“As for the boat, it belonged to certain men in dire want: they plied on
the water: I but wished to render it unserviceable, for there was after
them a certain king who seized on every boat by force.

“As for the youth, his parents were people of Faith, and we feared that
he would grieve them by obstinate rebellion and ingratitude (to God and
man).

“So we desired that their Lord would give them in exchange (a son)
better in purity (of conduct) and closer in affection.

"As for the wall, it belonged to two youths, orphans, in the Town; there
was, beneath it, a buried treasure, to which they were entitled: their
father had been a righteous man: So thy Lord desired that they should
attain their age of full strength and get out their treasure -- a mercy
(and favour) from thy Lord. I did it not of my own accord. Such is the
interpretation of (those things) over which thou wast unable to hold
patience."[fn:2]

#+END_QUOTE

Bahá'u'lláh refers to this story in the Seven Valleys, by quoting Rúmí's
verse:

#+BEGIN_EXAMPLE
  If Khidr did wreck the vessel on the sea,
  Yet in this wrong there are a thousand rights.[^3]
#+END_EXAMPLE

[fn:1] Seven Valleys, p. 29

[fn:2] Qur'án, verses 18:65-18:82
