:PROPERTIES:
:ID:       08EB8EDF-26ED-4EBC-915C-E39AB2A4C9FD
:SLUG:     all-things-are-provided-by-god
:END:
#+filetags: :essays:
#+title: All things are provided by God

[WARNING] Note with key '1' defined at line 95 column 1 but not used.
[WARNING] Note with key '10' defined at line 113 column 1 but not used.
[WARNING] Note with key '2' defined at line 97 column 1 but not used.
[WARNING] Note with key '3' defined at line 99 column 1 but not used.
[WARNING] Note with key '4' defined at line 101 column 1 but not used.
[WARNING] Note with key '5' defined at line 103 column 1 but not used.
[WARNING] Note with key '6' defined at line 105 column 1 but not used.
[WARNING] Note with key '7' defined at line 107 column 1 but not used.
[WARNING] Note with key '8' defined at line 109 column 1 but not used.
[WARNING] Note with key '9' defined at line 111 column 1 but not used.
I wonder if God didn't create our imperfect natures on purpose. That is,
here I am feeling great one day, depressed and irritable the next. The
question is, will I forsake my expectation of a "particular condition"
and praise God throughout? Will my love for Him transcend every worry
caused by the baser sides of my nature?

I think if we abandon all procedure, all expectation, all method, and
simply focus on purifying our heart from everything but God, He will
grant us the assistance we seek. There are many quotations which appear
to me related to this Theme:

#+BEGIN_QUOTE
The true seeker hunteth naught but the object of his quest, and the
lover hath no desire save union with his beloved. Nor shall the seeker
reach his goal unless he sacrifice all things. That is, whatever he hath
seen, and heard, and understood, all must he set at naught, that he may
enter the realm of the spirit, which is the City of God.[^25]

#+END_QUOTE

In this quote, I throw away all my past learning and experience. It is
not necessary for seeking God.

#+BEGIN_QUOTE
The understanding of His words and the comprehension of the utterances
of the Birds of Heaven are in no wise dependent upon human learning.
They depend solely upon purity of heart, chastity of soul, and freedom
of spirit. This is evidenced by those who, today, though without a
single letter of the accepted standards of learning, are occupying the
loftiest seats of knowledge; and the garden of their hearts is adorned,
through the showers of divine grace, with the roses of wisdom and the
tulips of understanding.[^26]

#+END_QUOTE

In this quote, he frees me from the need for knowledge or skill, and
makes my progress wholly dependent on my purity, chastity and freedom.
These are attributes which oppose acquisition! Purity is being free from
obstruction, chastity is being free from lust or inordinate desire, and
freedom is of course being free from restriction.

#+BEGIN_QUOTE
Fear God, and God will give you knowledge.[^27]

#+END_QUOTE

Here I need only fear God. In Arabic the term is "Khashíyyatu'lláh",
which implies a reverential awe, such as a Knight of the Round Table
would have had for King Arthur. The devotion of such a knight which
cause him to prefer death before dishonoring or disobeying his Lord. In
fact, the mere suggestion of deceit would feel like a physical sickness.
This is different from "tarsídan", which means fear as one might fear
spiders or some threat.

#+BEGIN_QUOTE
Now is the traveler unaware of himself, and of aught besides himself. He
seeth neither ignorance nor knowledge, neither doubt nor certitude; he
knoweth not the morn of guidance from the night of error. He fleeth both
from unbelief and faith, and deadly poison is a balm to him.[^28]

#+END_QUOTE

In this quote, questions of station, knowledge and attainment are simply
not the seeker's focus. In fact, /whatever/ draws one's attention away
from God is not worthy of consideration. As He wrote:

#+BEGIN_QUOTE
They say: =Where is Paradise, and where is Hell?'  Say:=The one is
reunion with Me; the other thine own self, O thou who dost associate a
partner with God and doubtest.'[^29]

#+END_QUOTE

I interpret this to mean that our self, since it can become a focal
point of attention, causes us to turn our eyes away from God, which is
the essence of Hell. This is an interesting emphasis, since it means
that self-perfection and self-development are /not/ the goal of
religion. They are /means/ to an end. That end is reunion with God,
which is being so completely absorbed in and by the Divine that there is
nothing else. In order for this to happen, as was quoted above, there
must be purity, fear of God, etc. -- in other words, virtue. But this
virtue is functional, not qualitative. We gain nothing if the result of
such virtue is that we focus even more intently on our own progress.

So, we progress until we reach a point where we abandon all notion of
progress, all hope (for ourselves) of attainment. When there is only the
Beloved:

#+BEGIN_QUOTE
In this realm, to search after knowledge is irrelevant, for He hath said
concerning the guidance of travelers on this plane, "Fear God, and God
will instruct thee." And again: "Knowledge is a light which God casteth
into the heart of whomsoever He willeth."[^31]

#+END_QUOTE

The secret of life is to become like a moth, circling around the
Best-Beloved of all worlds, the Ancient Beauty. In that state, "they
swim in the sea of the spirit, and soar in the holy air of light. Then
what life have words, on such a plane, that 'first' and 'last' or other
than these be seen or mentioned!"[^33] From this state all knowledge and
all things proceed, as He wrote:

#+BEGIN_QUOTE
... for everyone who sets foot therein knows all branches of learning
even before he becomes aware of their inner secrets. He comprehends all
knowledge and wisdom by means of the mysteries of divinity deposited in
the creation -- for he reads in the leaf the secrets of the tree.[^34]

#+END_QUOTE

Why should we worry ourselves over the details of attainment, when
attainment itself grants all things? Therefore, the only question, the
only worry, the only point of focus worthy of attention, is God Himself
as manifested in the Primal Point: the Manifestations of God. There is
nothing else to consider beyond this.
