:PROPERTIES:
:ID:       EAAE856E-0773-4164-988D-4E3E0A560079
:SLUG:     immortal-sovereignty
:END:
#+filetags: :journal:
#+title: Immortal sovereignty

What follows are some musings on the following Hidden Word:

#+BEGIN_QUOTE
O Son of My Handmaid! Didst thou behold immortal sovereignty, thou
wouldst strive to pass from this fleeting world. But to conceal the one
from thee and to reveal the other is a mystery which none but the pure
in heart can comprehend.

#+END_QUOTE

When the Writings speak of this world and the next, it can also refer to
the world of self, and the world of nearness to God:

#+BEGIN_QUOTE
Know ye that by "the world" is meant your unawareness of Him Who is your
Maker, and your absorption in aught else but Him. The "life to come," on
the other hand, signifieth the things that give you a safe approach to
God, the All-Glorious, the Incomparable.

#+END_QUOTE

Viewed in this sense, the first sentence of the Hidden World could be
saying that if we only knew the station of a pure heart, devoted to God,
we would impatiently cast away our selves.

In another Hidden Word He writes:

#+BEGIN_QUOTE
Possess a pure, kindly, and radiant heart, that thine may be a
sovereignty, ancient, imperishable and everlasting.

#+END_QUOTE

Here again we see the image of an immortal sovereignty, but it refers to
a condition of heart, and not the worlds after physical death. And the
phrase "strive to pass from this fleeting world" reminds me of another
verse along these lines:

#+BEGIN_QUOTE
O My Brother! A pure heart is as a mirror; cleanse it with the burnish
of love and severance from all save God, that the true sun may shine
within it and the eternal morning dawn. Then wilt thou clearly see the
meaning of "Neither doth My earth nor My heaven contain Me, but the
heart of My faithful servant containeth Me." And thou wilt take up thy
life in thine hand, and with infinite longing cast it before the new
Beloved One.

#+END_QUOTE

But why is the glory of this station concealed, and the unreality of
self allowed to hold sway over both our understanding and our
perceptions, such that we must battle life-long to overcome it?

Maybe, in order to know God, we must first perceive what is "not God";
that is, acutely know the pain of His absence, until we are able to
perceive even the least hint of His presence; until, "Each and every
thing, however small, would be to him a revelation, leading him to his
Beloved, the Object of his quest", and where, "none shall contemplate
anything whatsoever but that he shall see God therein".

For example, a thirsty man perishing in the desert knows far more about
water than the fish who swims in it always. That man can perceive its
life-giving potential in a single drop -- savoring its sweetness,
longing for it with all his heart -- while the fish remains ignorant in
the very heart of the sea!

God's revelation is like that sea, and to truly recognize it for its own
sake -- not only for benefits it may confer -- we must endure the dark,
to sensitize our eyes; we must endure pain, to know the sweetness of
mercy; we must feel the anguish of separation, poignant and deep, to
savor the joy of reunion.

Within the contrast between what is and what could be, between "this
fleeting world" and the joys of "immortal sovereignty", lies a mystery
both awesome and dreadful: "For the head raised up in the love of God
will certainly fall by the sword, and the life that is kindled with
longing will surely be sacrificed, and the heart which remembereth the
Loved One will surely brim with blood."

Again, if "head" and "life" are taken as references to selfhood, and
"falling by the sword" and "sacrifice" refer to what must happen in
order for us to die from self and live in God, then the brimming of our
hearts with blood is a beautiful mystery -- and one I believe is also
addressed quite eloquently in the Fire Tablet.
