:PROPERTIES:
:ID:       A2D90B5D-EF63-4C84-912F-6CB206B0FB8E
:SLUG:     to-know-God
:END:
#+filetags: :journal:
#+title: To know God

I believe that God created us out of love, since love is an attribute of
His perfection. He created each thing, and a paradise for that thing, so
the creature might enjoy the bounties of its Creator. This is not done
out of any need, but as a token of His grace, so we might know the
abundant joy of drawing near to Him.

Paradise for human beings is the knowledge of God, but knowledge is not
identical with awareness and appreciation. A wealthy man can know money
in every detail, but fail to appreciate the meaning of his wealth,
unless and until he has hungered and suffered deprivation.

Even with us Bahá'ís: we know prayer; but it's another thing to fully
appreciate the reality of prayer. Consider what the Báb wrote about
prayer:

#+BEGIN_QUOTE
[T]he river of milk "whose taste changeth not" ... floweth through the
depths of prayers and supplications. It is the fresh milk and the
manifest mystery, whose inner essence revealeth the crystal,
incorruptible water, the outward form of which is pure milk. It is the
water of the spirit of prayer, through which man reacheth the summit of
sanctity and reposeth within the heaven of eternal reunion....

#+END_QUOTE

#+BEGIN_QUOTE
By thy life! Were the people to taste the delight of that milk, they
would assuredly be willing to rend, with their own hands, their own
bodies, that they might be permitted to recite a single prayer. For
verily, within each prayer vibrateth the spirit of divine Sovereignty,
radiateth the mystery of Eternity, and shineth forth the uttermost word
of Servitude before the Divine Justice.

#+END_QUOTE

All this ignorance, darkness and evil, are in fact aspects of knowledge,
since without it, we would not be driven to realize the full extent of
our powerlessness before God, and our reliance upon Him. In
contemplating the beauty of this ugliness, or the peace in this war,
consider this prayer from Bahá'u'lláh:

#+BEGIN_QUOTE
Glorified, immeasurably glorified art Thou, my Best-Beloved! Inasmuch as
Thou hast ordained that the utmost limit to which they who lift their
hearts to Thee can rise is the confession of their powerlessness to
enter the realms of Thy holy and transcendent unity, and that the
highest station which they who aspire to know Thee can reach is the
acknowledgment of their impotence to attain the retreats of Thy sublime
knowledge I, therefore, beseech Thee, by this very powerlessness which
is beloved of Thee, and which Thou hast decreed as the goal of them that
have reached and attained Thy court, and by the splendors of Thy
countenance that have encompassed all things, and by the energies of Thy
Will whereby the entire creation hath been generated, not to deprive
them that have set their hopes in Thee of the wonders of Thy mercy, nor
to withhold from such as have sought Thee the treasures of Thy grace.

#+END_QUOTE

And again, the message of the Fire Tablet. Finally, there are these
words on coming to know God from 'Abdu'l-Bahá:

#+BEGIN_QUOTE
Is the king free as the bird is free to fly upward? The king's head is
often heavy with anxiety and the things of this world which hold him
down. The true pleasure and happiness depend upon the spiritual
perception and enjoyment. The powers of mind are the bounties of God
given to man to lead him toward spiritual happiness. The highest grace
in man is to love God. Love of God, knowledge of God is the greatest,
the only real happiness, because it is nearness to God. This is the
kingdom of God. To love God is to know Him. To know him is to enter his
kingdom, and to be near him.

#+END_QUOTE

If the meaning of life is predicated on knowing God, we must ask what it
means to know, and what role this dark existence plays in gaining that
knowledge.
