:PROPERTIES:
:ID:       F8D91AFA-C01C-4580-94BF-435D6C59F826
:SLUG:     the-choice-wine
:END:
#+filetags: :journal:
#+title: The choice wine, sealed with musk

Some thoughts on the "wine sealed by musk", mentioned in the
Kitáb-i-Íqán:

The source of this reference comes from Qur'án 83:25-26:

#+BEGIN_QUOTE
And they are given to drink of a sealed wine, whose seal is musk. For
the like of this let the travailers travail!

#+END_QUOTE

Which is also quoted by Bahá'u'lláh in the second of The Four Valleys:

#+BEGIN_QUOTE
Wherefore, a man should make ready his heart that it be worthy of the
descent of heavenly grace, and that the bounteous Cup-Bearer may give
him to drink of the wine of bestowal from the merciful vessel. "For the
like of this let the travailers travail!"

#+END_QUOTE

There are many references to this wine, all of them likening it to His
Revelation:

#+BEGIN_QUOTE
I have, moreover, with the hand of divine power, unsealed the choice
wine of My Revelation, and have wafted its holy, its hidden, and
musk-laden fragrance upon all created things.

#+END_QUOTE

#+BEGIN_QUOTE
Think not that We have revealed unto you a mere code of laws. Nay,
rather, We have unsealed the choice Wine with the fingers of might and
power.

#+END_QUOTE

#+BEGIN_QUOTE
Renounce all created things, and quaff the sealed wine of My
remembrance.

#+END_QUOTE

#+BEGIN_QUOTE
Well is it with him... who hath quaffed, with unswerving resolve, and in
the name of the Self-Subsisting, the sealed wine of His Revelation.

#+END_QUOTE

#+BEGIN_QUOTE
The seal of the choice Wine of His Revelation hath, in this Day and in
His Name, the Self-Sufficing, been broken.

#+END_QUOTE

#+BEGIN_QUOTE
Take heed lest anything deter thee from extolling the greatness of this
Day -- the Day whereon the Finger of majesty and power hath opened the
seal of the Wine of Reunion...

#+END_QUOTE

#+BEGIN_QUOTE
The Best-Beloved is come. In His right hand is the sealed Wine of His
name.

#+END_QUOTE

One thing to note about the "choice wine" is that the Arabic phrase is
"rahíqun makhtúmun". Rahíq can mean both "exquisite wine", and nectar,
the source of honey. And two of the rivers in paradise are wine and
honey...

Now, why is this Wine sealed with musk?

There is a powerful connection in the Writings between discerning scent
and a spiritual capacity to recognize the true nature of the
Manifestations of God. This connection of fragrance to recognition is
also a powerful motif is the story of Joseph, which Bahá'u'lláh
references on multiple occasions:

#+BEGIN_QUOTE
And if, by the help of God, he findeth on this journey a trace of the
traceless Friend, and inhaleth the fragrance of the long-lost Joseph
from the heavenly messenger, he shall straightway step into the Valley
of Love and be dissolved in the fire of love.

#+END_QUOTE

Or in the Íqán where Bahá'u'lláh writes:

#+BEGIN_QUOTE
We seal Our theme with that which was formerly revealed unto Muhammad
that the seal thereof may shed the fragrance of that holy musk which
leadeth men unto the Ridván of unfading splendour.

#+END_QUOTE

`Abdu'l-Bahá also uses the image of the choice wine and the musk:

#+BEGIN_QUOTE
As to you, O ye loved ones of God! Loose your tongues and offer Him
thanks; praise ye and glorify the Beauty of the Adored One, for ye have
drunk from this purest of chalices, and ye are cheered and set aglow
with this wine. Ye have detected the sweet scents of holiness, ye have
smelled the musk of faithfulness from Joseph's raiment.

#+END_QUOTE

And in another place, He associates musk with spiritual revival:

#+BEGIN_QUOTE
One's conduct must be like the conduct of Paul, and one's faith similar
to that of Peter. This musk-scented breeze shall perfume the nostrils of
the people of the world, and this spirit shall resuscitate the dead.

#+END_QUOTE

So, the Wine symbolizes God's Revelation, and the musk -- its beauty,
fragrance, and life-giving breath -- attracts us to it. This only leaves
the question: why is it sealed with this musk? This actually connects to
the question of why Noah was given prophecies that God did not
fulfill...
