:PROPERTIES:
:ID:       A616B2E4-B1AC-4E29-8E6C-4310D37225A9
:SLUG:     descriptive-interpretation
:END:
#+filetags: :journal:
#+title: Descriptive interpretation

There are certain mystical passages in the Bahá'í Writings that can be
read quite differently if one shifts from a prescriptive, self-oriented
interpretation, to a descriptive, Revelation-oriented one.

One example of this is detachment, about which I wrote
[[/2005/02/detachment-and-desire/][in another post]]; another, I think,
is the following Hidden Word:

#+BEGIN_QUOTE
O Son of Earth! Know, verily, the heart wherein the least remnant of
envy yet lingers, shall never attain My everlasting dominion, nor inhale
the sweet savors of holiness breathing from My kingdom of sanctity.

#+END_QUOTE

For many years I'd read this Hidden Word in what seems like the obvious
way: until my heart is purified from all envy, I cannot attain God's
everlasting dominion. Since this is quite difficult to achieve, it makes
that kingdom feel very far away, and nearly impossible to reach.

But what if it's not /prescribing/ a condition /I/ must achieve, but is
/describing/ the nature of that kingdom, by depicting the character of
one who has recognized it?

If the Revelation of God's Manifestation is the most valuable thing in
existence, how can one who has the most valuable thing envy anything at
all? Therefore, even "the least remnant of envy" becomes proof that one
has not truly recognized it -- a recognition necessary to perceive the
gift it contains -- rather than indicting the unworthiness of one who
still seeks it.

Or in the example on detachment, Bahá'u'lláh writes:

#+BEGIN_QUOTE
Say: He is not to be numbered with the people of Bahá who followeth his
mundane desires, or fixeth his heart on things of the earth. He is My
true follower who, if he come to a valley of pure gold, will pass
straight through it aloof as a cloud, and will neither turn back, nor
pause. Such a man is, assuredly, of Me.

#+END_QUOTE

Prescriptively interpreted as making a statement about the individual,
it seems to be saying we must achieve a nearly impossible standard to
become one of the people of Bahá; but descriptively intepreted as a
statement clarifying the nature of Bahá'u'lláh's Revelation, it could be
read as saying: So great is His Cause that any man who truly recognizes
it will have no room in his heart for anything the world might contain;
if even the least shred of desire should remain, then he has not
recognized it.
