:PROPERTIES:
:ID:       AD86BE8D-1844-4AE6-A539-259BCC3425BF
:SLUG:     proving-validity-of-the-quran
:END:
#+filetags: :journal:
#+title: Proving the validity of the Qur’án?

It's hard to give a "proof" of the Qur'án, in the sense of convincing
others instantly and utterly, but there are a few facts to consider:

- Muhammad was illiterate, and is reported to have uttered the chapters
  of the Qur'án on the spot, noted down by those around him. If you look
  at the language and complexity of the Qur'án, and how hard it is even
  for learned individuals to mimic its richness and style, that's pretty
  amazing by itself.

- Although the Qur'án is relatively short, it became the basis for a
  civilization that was more successful than the Roman Empire, covered a
  greater territory, and was reknowned over the centuries for its art,
  science and philosophy. How can such a small book, spoken aloud by an
  unlettered man of Arabia during the 7th century, be so rich and
  complex that it still serves as a guide for millions today?

- The Qur'án makes an explicit challenge that if it is not from God,
  simply imitate it: Write something of equal beauty and power, if you
  think it's just the ravings of a poet from the Arabian desert.
  Although this challenge was given over 1300 years ago, it has
  nonetheless withstood the test of time.

- If you survey the state of the Arabian Peninsula when Muhammad was
  born, it is shocking to think it could have ever been united by
  anyone, so afflicted was it by internecine conflicts, prejudices, and
  barbaric traditions. Compare the result of the Qur'án's influence on
  that region, with the conditions it appeared in, and it becomes very
  hard to reckon it a mere book of poetry. Many men, over millenia, have
  tried to fashion ideal societies under far more favorable conditions
  --- we still don't have a living example of Plato's Republic. Yet the
  Islamic nations, at their peak, were a light to the world.
