:PROPERTIES:
:ID:       2EAB9C9C-8FD3-4D6C-936F-5BE9C047B054
:SLUG:     does-absolute-truth-exist
:END:
#+filetags: :journal:
#+title: Does absolute truth exist?

I think absolute truth does exist, but often when you cast it into terms
of human language and conception, it becomes relative to those
assumptions.

For example: Does the sun radiate heat? Absolutely, this is a physical
and verifiable fact. Is the sun hot? Yes, and no. It's certainly hot to
those of us living on Earth; but it's downright frigid compared to the
temperatures of the Big Bang.

As the absolute truth you're seeking gets more and more abstract, it
becomes harder to find an expression of it that is not made relative by
the expression itself. For example, for centuries Sufi mystics have
argued whether God is found in all things, or all things are God. There
are compelling religious foundations for both viewpoints; but since the
subject (God) is so abstracted from human experience, the terminology
used to explore the problem means that even when such statements are
relatively true, no one of them is absolutely so. The absolute truth
must be approached in the union of these perspectives.

So if you seek an absolute truth, be very careful of how you phrase it,
and the terms used to describe it. It may remind you of Rumi's story
about the elephant in the dark:

#+BEGIN_EXAMPLE
Some Hindus have an elephant to show.
No one here has ever seen an elephant.
They bring it at night to a dark room.

One by one, we go in the dark and come out
saying how we experience the animal.
One of us happens to touch the trunk.
A water-pipe kind of creature.

Another, the ear. A strong, always moving
back and forth, fan-animal. Another, the leg.
I find it still, like a column on a temple.

Another touches the curve back.
A leathery throne. Another, the cleverest,
feels the tusk. A rounded sword made of porcelain.
He is proud of his description.

Each of us touches one place
and understands the whole in that way.
The palm and the fingers feeling in the dark
are how the senses explore the reality of the elephant.

If each of us held a candle there,
and if we went in together, we could see it.
#+END_EXAMPLE
