:PROPERTIES:
:ID:       1EA06C90-732B-4F2E-934D-A5897DFC6378
:SLUG:     divine-kabih
:END:
#+filetags: :journal:
#+title: The divine Ka`bih

"God's eternity", in the Arabic, is often stated as "baqá". It is
discovered upon completing self-annihilation, faná. These two relate to
the opposite poles of the mystic's journey: God (Alláh) and self (nafs).
Once the nafs is consumed in the fire of love and becomes nothing
(faná), then the lover enters the heaven of eternity in God (baqá).

These mystic states have many outward symbols. The meaning of baqá is
represented as the Object of Adoration, the Divine Ka`bih. It does not
refer to the building, but its essential meaning as the cynosure of all
hopes and desires.

Viewed this way, the Ka`bih comes to signify many things. For example,
the letters of the Qur'án may be compared to the believers, and the
true, inner meaning, as the Ka`bih of recognition. Only when the role of
the letters is subsumed in the purpose of the message is the meaning
faithfully conveyed.
