:PROPERTIES:
:ID:       24FA52E6-15C5-4D1C-A6DA-81CCF9791C06
:SLUG:     beauty-of-the-quran
:END:
#+filetags: :essays:
#+title: Discovering the beauty of the Qur'án

How do we, as lovers of the Ancient Beauty, come to recognize the
gem-like beauty of the Qur'án, as an emanation from His Exalted Pen?

#+BEGIN_QUOTE
Number me not with them who read Thy words and fail to find Thy hidden
gift which, as decreed by Thee, is contained therein, and which
quickeneth the souls of Thy creatures and the hearts of Thy servants. --
Bahá'u'lláh

#+END_QUOTE

The point has often been made that the Qur'án is outdated -- and in its
moral and legal teachings, it certainly is. If that weren't the case,
God would not have sent another Revelation. However, in its spiritual
teachings, the Truths enshrined within it remain unchanged. This is
evidenced by how frequently Bahá'u'lláh quotes from it to explain
fundamental spiritual principles.

Defending Islám and the Qur'án does not mean justifying its practices in
the context of today's society. It means upholding its value and role in
human history, while preserving those eternal aspects that will never be
eclipsed.

The Qur'án speaks often of fear, the fire, and God's wrathful vengeance;
but this is no ordinary fear, or fire, as it has been preached to the
masses. That fear is something you would cherish in your heart as a dear
possession, and a guarantor of victory -- as you might honor wisdom as a
safeguard for knowledge; and that fire is nothing other than unbelief
itself, into which the infidels are cast by their willful disobedience;
and God's wrath is likewise the harsh light of truth, as much as the
Earth's, if you were to ignore the laws of gravity and throw yourself
from a great height.

Words like these have spiritual meanings that are greatly obscured by
literal, humanistic interpretations, that imagine God as some powerful,
earthly-minded king Who imposes whatever laws He wishes, while punishing
the disobedient. However, the beauty of Qur'án is not to be found in
this view. Hold foremost in your mind the goodness, love, and mercy of
God, and then read His verses as if there could be no other
interpretation.

For example, in verse 2:59, we find a pretty scary statement:

#+BEGIN_QUOTE
... So We sent down a torment from Heaven upon those who did wrong for
the iniquity they committed.

#+END_QUOTE

The word used here for torment is rijz, which is also translated as
"defilement" (or sometimes, evil whisperings) in verse 8:11:

#+BEGIN_QUOTE
Behold, He covered you with sleepiness, security from Him, and sent down
upon you water from the sky to purify you thereby, to remove the
defilement of Satan from you, to fortify your hearts, and to make firm
your steps thereby.

#+END_QUOTE

These "evil-whisperings of Satan" portray the promptings of the
insistent self, that inclines people toward evil. Thus, the "torment"
sent down on those who do wrong is to leave them to themselves! Compare
this to a similar statement from the Báb:

#+BEGIN_QUOTE
Indeed shouldst Thou desire to confer blessing upon a servant Thou
wouldst blot out from the realm of his heart every mention or
disposition except Thine Own mention; and shouldst Thou ordain evil for
a servant by reason of that which his hands have unjustly wrought before
Thy face, Thou wouldst test him with the benefits of this world and of
the next that he might become preoccupied therewith and forget Thy
remembrance.

#+END_QUOTE

Rather than fire and brimstone, divine torment here is described as
material benefit and the promises of the next world! How opposite to any
literal reading of the Qur'ánic verse!

Similarly, many of the dreadful passage from the Qur'án can be
understood in another light: not as vengeful acts of an angry God, but
conditions of spirit whose ultimate effect is so horrible, that for
some, only the literal message conveys the intended meaning.
