:PROPERTIES:
:ID:       697CF619-2BC4-4CE9-BD90-F4CEDDF5F4E3
:SLUG:     does-foreknowledge-eliminate-freedom
:END:
#+filetags: :journal:
#+title: Does God's fore-knowledge eliminate free will?

Problem with this question is that it assumes time is linear for
everyone, including God.

Imagine you knew everything. Not just everything that is, but everything
that can be: every possible universe that could result from every
possible choice. And you don't just know one or some of them, but all of
them. You know my whole future if I choose to drink coffee today, and
you know my whole future if I choose not to. After all, if your
knowledge is infinite, there's no capacity problem. You would know every
future, resulting from every choice, for every person in existence.

This means that God doesn't need to fore-know what I'll choose, because
it wouldn't make a difference; He already knows every divergent outcome:
billions upon billions of possible futures, resulting from every
conceivable choice I might make.

Does it limit my freedom that the future exists? Does it limit my
freedom that God knows all of them?

I think what your original question assumes is that, if God knows which
final future I will choose, it eliminates all the other possibilities
from the beginning. But maybe this isn't how God's knowledge of the
future works... if He's not linear.

I also think this is where fate and free will co-exist. Free will
creates the set of futures we can choose from, while fate limits that
set to what God makes allowable. It's like a diner at a buffet, who can
choice any one of a hundred foods, but his choice is still limited to
those hundred.

So if God decrees that a certain thing must happen in my life, it
becomes fated, and all my futures now contain that thing. But how
exactly I get there would still be up to me, without either affecting
His foreknowledge of what must happen, or my free will in how I get
there.
