:PROPERTIES:
:ID:       FDBB394F-D9DD-4E00-92E4-9EDB4BFB04B7
:SLUG:     suffering
:END:
#+filetags: :journal:
#+title: Suffering

Viewed on its own, physical death and suffering in this world are among
the worst of its evils. How can God, Who is so good, permit these evils
to constantly triumph?

Viewed in the context of a life beyond, where this world is only the
beginning of a vast and varied journey, the picture changes. Then
physical suffering is not the worst outcome; in fact, a lack of
suffering, causing one to neglect all spiritual matters, is much worse.

Some things only make sense in their proper context; divorced from that
context, they remain nonsensical. It's a bit like asking why our body
should feel pain, without considering how our health is generally
preserved by that pain. Does it mean all pain is useful? No. Errant
pains are part of the nature of our body. But there is no pain that will
endure forever. God made our soul to inhabit this body. The body
experiences what it will, but the soul is where the meaning lies.
