:PROPERTIES:
:ID:       731EBC68-048C-4362-B73A-ED3732CC225F
:SLUG:     virtue-renewed
:END:
#+filetags: :journal:
#+title: Virtue renewed

Like many things, I think the attitudes of past religions toward certain
subjects, such as prayer, fasting and chastity, have given us a
framework for understanding these things that is limited by the
perspectives of the past. Just as the past religious doctors failed to
understand the spiritual meaning of the prophecies of the Holy Books,
they also abbreviated many other concepts such as heaven, hell, and
soul, by relating these concepts primarily to physical realities or
states of being. To them, the event of physical death is somehow the
most significant spiritual event in one's life; but why would
transformation of the material be so significant to our spiritual life?

Instead, I think the books have been unsealed, and we are ready to
develop an entirely new relationship with these concepts and laws. Take
chastity for example... I have a strong sense that our wrestling over
chastity has a lot to do with the times we live in, where identity,
sexuality and personal competence and success are so highly valued that
it distorts all measure of value and self-worth.

Chastity (not just sexual expression, but a purity of heart necessary to
the mystical path) can lead to greater consciousness, awareness,
sensitivity and development. Meanwhile, sexual impulses can lead one
back to the earth and too easily confuse and distract the heart, mind
and body.

Thus, essentially, one is more useful to spiritual development than the
other, and once one's life objectives become aligned with the Writings,
it's only natural to seek one over the other. Not in the sense of
exclusion, but of choosing what makes the most sense.

Put another way, we have two aspects: our self (nafs) and our spirit
(rúh), which are related like a horse is to its rider. In order to make
our way safely and with speed, the self requires training and education.
Chastity, fasting, prayer, study, moral virtue: all of these serve the
deepest interests of the self, which is to serve the spirit from which
life and happiness are derived.

When we neglect the spirit and give ourselves over to physical impulses,
I wouldn't say this is bad per se, but it's like feeding sugar cubes and
soda to the trusty steed self. Of course he'll turn into a spaz that
only wants to run in its own direction, leaving the spirit confused and
bewildered and hanging on for dear life.

The internal dialog of right and wrong that we've inherited from Western
religious traditions --- a perspective often applied to readings of the
Bahá'í Writings --- pits the self and spirit at war with each other.
Islam even calls it the greater Jihad (even though the word just means
"the great effort"). But I tend to think the self is more like a young
puppy defecating all over your house. With training, his adult self will
/want/ to show you obedience and loyalty. That's his nature. But he
can't achieve the beauty of that relationship if left solely to his
inclinations.
