:PROPERTIES:
:ID:       838901A6-E43A-44AB-9DCE-7EB5FE77ECC4
:SLUG:     second-translation-of-the-rashh-i-ama
:END:
#+filetags: :journal:
#+title: Second translation of the Rashh-i-`Amá

There is a particular music and rhythm, an entrancing feel of being
carried along, swept up in a verbal embrace. It's a written form of the
sun breaking through clouds, a song of power, a revelation of mysteries
long hidden yet never kept from view -- osbcured by their own
transcendent glory. I've tried my best to translate it so that, as an
English speaker, it conveys how I feel when reciting the original:

#+BEGIN_VERSE
Rashh-i-`Amá (Sprinkling from the Eternal Cloud)

The Eternal Cloud rains down with Our joy;
the secret of fidelity resounds in Our song.

The wind of Sheba carries the musk of Cathay:
a gentle fragrance that flows from Our locks.

A gleaming Sun doth beam from Our countenance;
what secrets of truth shine from Our face!

The sea of purity surges in waves of reunion,
casting forth precious gifts through our joy.

A treasury of love lies nestled in the breast of Fá,
wherein is found the treasured pearl of devotion.

The Choice Wine is a mere glance at this bloom:
heart-stirring secrets that echo from the song of Rá.

The silver-white Trumpet, the rapture of the Divine:
both ringing out by a single breath from Heaven.

From Our dawning, the Day of "I am He" shines forth;
by Our gentle breeze, the Age of "He is He" begins.

The heavenly Kawthar flows from Our heart's chalice;
Bahá's lips shed sweet draughts of honey.

The Day of God, fulfilled by Our Lord's unveiling:
What wondrous tidings go out from the bounty of Tá!

What overflowing glory!
what showers from this Cloud!
and all flows out
from but one of God's songs...

Behold the ancient Leviathan
and the blameless Countenance;
behold the great Judge
descending from His lofty throne.

Behold the Palm of Paradise;
hear the melody of the Dove;
witness the grandeur of Abhá
descending in purest splendor.

Give ear to the Persian melody
and the beat of the Arab drum;
hear the God-song that vibrates
throughout the ecstasy of Lá.

Behold the Divine Appearance
and the Maid of His Threshold;
whose mortal splendor rains down
from the secrets of Pre-existence.

Behold the Immortal Face
and the cup-bearer's glance!
behold Our gleaming chalice
and its crystal waters raining down.

Behold the flame of Moses;
behold its gleaming light;
behold the hand of splendor
stretched out from the heart of Sinai.

Hear the lament of the drunkards;
observe the state of the gardens;
behold the rapture of existence
raining down from Our Court.

Behold Há's budding blooms of
and the curling locks of Bá;
hear the songs of Ná
crying out from the pen of Bahá.

This is the overflowing ablution;
this is the cleansing water;
this is the trill of birds
that only sanctified eyes doth see.
#+END_VERSE
