:PROPERTIES:
:ID:       B59EAC83-6D90-4123-85C9-1B1B99D10A55
:SLUG:     a-meditation
:END:
#+filetags: :journal:
#+title: A meditation

Breath deeply. Take a moment to let your eyes close; clear your mind of
thoughts best you can; let a feeling of stillness settle upon you. In
this space imagine your whole being is like a compass needle, seeking
true North. Allow it move freely this way and that. Your guide is the
magnetic force of the Divine: the attraction of your soul to its
Beloved. Just tell your body, your mind to chill for a minute. They are
fantastic tools, but you don't need them for this. The soul knows, the
soul has always known; it was made to know.

Meditate for a moment on some of the attributes of God: His goodness,
His love, His friendship toward you. Sometimes when we pray we have
great faith that it will help; do you also have faith when praying for
your own aid and assistance? Do you know, in your bones, not only will
God help you, but He wants to? That He yearns to? That He has only been
waiting for you to ask because He loves your freedom as much as your
happiness?

If you have children, or family members, or friends, think how you would
answer their request for help. Is God less good than this? Or is He so
good we can't imagine it? If we know what friendship is, wasn't that
knowledge created by Him? Isn't the very essence of goodness born from
Him?

When the night is over, His friendship takes the form of the sun rising,
inviting us to wake. When we are hungry, His friendship is in the food
that satisfies us. When we're thirsty, it's found in the cool water that
makes us content. Everywhere the world is speaking this bond. Even in
pain, even in suffering, there is also His friendship, just on a larger
scale than we recognize right now.

Finally, consider that God, through His Ancient Beauty, has asked us to
become the living manifestations of His friendship toward all the people
of the Earth. Commit to letting that spirit shine through you, bright
and clear, by speaking truth, serving justice, drawing your motive to
act from seeing one another as /His friends/. Do not stop until feel it
also. Make it real.

You are His mirror, which is to say, His light has been shining on you
since the beginning.
