:PROPERTIES:
:ID:       90DEB61F-2BA7-43FF-9484-B0935ACEF931
:SLUG:     the-living-universe
:END:
#+filetags: :journal:
#+title: The living universe

Culturally I was brought up to see myself as an active agent within a
largely passive universe: A mechanist view wherein I make decisions and
the universe receives those decisions. In this view, when I read that I
am "created rich", I naturally think of that richness as belonging to
me, or being an attribute of my own that I have somehow failed to
realize.

Instead, I think that we exist within a spiritual dynamic -- a universe
that is as alive with Spirit as my own spirit enlivens my body. In this
view, what seems to be my "flea" nature becomes an "eagle" when I stand
in right relation to my Lord. Just as a garden might be filled with
color, yet until the sun gives its light there is no variety visible.
Such a notion of richness implies that I exist within the reality of
this relationship with God, in which is infinite bounty and
potentiality. It's only when I rest on self alone that I can see myself
as poor and of little account.
