:PROPERTIES:
:ID:       B90B4D40-4B38-49B1-8101-DC6ECDAE540A
:SLUG:     knowledge-of-god
:END:
#+filetags: :journal:
#+title: Knowledge of God

On Reddit someone said recently:

#+BEGIN_QUOTE
I was having this discussion with a few friends recently. I think that
the term "Knowledge of God" in the Writings is code for "recognition of
the Manifestation of God", except in those Writings where the term
"knowledge of God" refers to God's knowledge -- i.e. the knowledge
possessed by God.

#+END_QUOTE

When I read your words, I agree with you 100%, though I realize it
depends very much on what the hearer means by "God", "knowledge" and
"Manifestation". Some people, even Bahá'ís, think of the physical person
of Bahá'u'lláh when they hear the word "Manifestation of God". Others
think of divine attributes when they hear "God". And the thing is, in a
sense everyone is right, they're just right on different levels.

To use some analogies: If I look at a mirror, shining with light
reflected from the sun, I could say that I am looking at the sun and be
both right and wrong. The sun is much more than the tiny bit of shining
that I see, filtered as it is by distance, clouds and atmosphere. Humans
have never seen the sun, we cannot process what it means to "see" gamma
rays and x-rays and the full spectrum of its light; nor can we perceive
its intensity. So we filter it down, dim it, and say we have observed
the sun.

Or if I think about a rose, I might employ the idea of a rose. This is
not the same thing as Plato's Ideal Rose, even though they bear a
relationship. No one has ever perceived the ideal, and everyone has
their own idea descended from it. These ideas are made concrete by way
of example, and every example has an actual, physical rose that acts as
the revealer of its properties. So even just by saying "rose", a person
might mean the essential, the mental, the phenomenological, or the
physical.

Again and again, these four "dimensions" of perception come up: the
immediate and tangible; the revelation of attributes; the emanation from
the source; and the imperceptible origin.

When we talk about knowledge of God, then which of these dimensions do
we recognize Him through? Some have thought that phenomena were equal to
God Himself, because nothing else but Him exists (the Sufi doctrine of
wahdatu'l-wujúd). Others use "God" to mean the divine attributes we
witness, emergent from the phenomena. Still others call "God" the
absolute qualities these attributes descend from, such as perfection,
glory, supreme sovereignty, etc. And then there are those who associate
no name or place with "God" at all.

Similarly, we recognize the Manifestation of God first through His
earthly person; then through a recognition of His station; then by a
recognition of His eternal Purpose and sameness with all the
Manifestations of God; and lastly as the Primal Point, the Ancient
Beauty, the cynosure of all hopes and the object of the adoration of all
existing things. The Kitáb-i-Íqán, the Seven Valleys, and the Gems of
Divine Mysteries: each of these books is practically a travel guide
through these stations of recognition.

But when it comes to discussion, I can't pin any one of these down as
being "right" and the others wrong, or even "more right", because it
depends on one's perspective and how the seeker orients himself to the
truth. Some look at a mirror and see primarily the mirror; some look at
it and see the effulgence of the light; some look and see how it
testifies to the nature of the Rays; and some look and see only the Sun
itself.

And while it may be my purpose to forever learn about and better
understand the Sun, but I will never soar in Its atmosphere, or make
contact with It directly. In this way I am always dependent on the Rays
to mediate the qualities of the Sun, so I can perceive them according to
the extent of my limitations.

Then to me, the answer to how we know God and how we know the
Manifestations is the same: What is means to know the Manifestation is
to discover true Reality --- which is what it means to know God.

For another metaphor: I can never enter the mind of an author, but I can
discern his thoughts through the writing he conveys, always finding more
meaning, deeper connections. This noetic reality is beyond paper, but it
never fully bridges the gap between minds. The medium is our bond: it is
the relationship.

#+BEGIN_VERSE
Love is a veil betwixt the lover and the loved one;
More than this I am not permitted to tell.
#+END_VERSE

If we see the Manifestation as a limit, thinking that because we can
imagine something Beyond we might reach there --- I think this is a
falsehood of the self. He is the "Tree beyond which there is no
passing", because "How can utter nothingness gallop its steed in the
field of preexistence?". So He says, "Leave thyself behind, and then
approach Me."
