:PROPERTIES:
:ID:       01FAE318-5382-42D0-A7A5-CFB58B53B698
:SLUG:     transforming-the-heart
:END:
#+filetags: :journal:
#+title: Transforming the heart

Something that occurred to me this week: In my relationship to God, I
know I have to eventually love the Blessed Beauty so dearly that any
hint of self would feel like choosing dust over diamonds.

And I've also always thought there is a direction reflection between my
relationship to God and my relationship to people.

This led to an insight: the only path forward from where we are as a
society, to the spiritual future ahead of us, is to so love Black people
that even the least vestige of whiteness tastes like ash in my mouth.
Not something to defend, or explain, or seek compassion for. Just ash.
And yes, I have to love all humankind this way; but until I know how to
adore Blackness, the muscle of my heart remains atrophied.

Now I see "Black Lives Matter" in a much deeper light. It reads like the
title to Sadie Oglesby's conversation with the Guardian.
