:PROPERTIES:
:ID:       E00A57D4-59F4-4C8F-BB37-0264D61C059D
:SLUG:     the-sun-and-its-rays
:END:
#+filetags: :journal:
#+title: The sun and its rays

When I compare the Primal Will to the sun, it's clear to me that the sun
too has an origin: the laws of physics which allow gravity to seize
matter and compress it until fusion begins. But where did the laws of
physics come from? What is the origin of gravity? No matter how much we
may understand the operations of nature that allow the sun to exist, we
cannot know the causal origins of existence itself. In logic, this is
like building a framework of reasoning atop an assumed set of axioms.
Although such a framework can explain nearly all of mathematics, at the
end of the day the axioms are pulled out of whole cloth and it is there
that our reasoning fully and completely stops. The mind has no entrance,
even if in the result there is great utility.

Now that the sun is shining, and bestowing life on the entire solar
system, it must convey that life-giving power through its rays. There is
no direct tie between the sun and any of the planets: this would be
utterly destructive. Instead, the rays act as medium and connection.
What we call "the sun" is in fact only knowledge of the sun's properties
through its rays.

But even this isn't a complete picture, because life requires periods of
rest and renewal. The earth is not awash in the full radiance of the sun
at all times. There is a night and day cycle. In consequence -- from the
earth's perspective -- the rays appear to come and go, to wax and wane
in both intensity and spectrum.

In this sense, a pre-dawn ray might claim to be a direct representative
of the sun, but it cannot be compared to the visible sun. A post-dawn
ray, however -- while also a ray -- is a more direct representative
because its light manifests the full orb of the sun. When speaking in
the voice of the sun, it could factually declare that it is the source
of that pre-dawn ray.

This is the key point: they are both equally rays, but because of their
differences owing to the orientation of the earth, they speak in the
voice of the sun from distinct stations. One is the dawning radiance of
the sun; the other bears the light of the full image of the sun. And
since the dawning light derives its radiance from that full orb, it
would be correct for the ray representing the orb to say that it is the
source of the ray representing the morning's aurora.

To me, these three realities: that which makes the sun possible, the sun
itself, and the rays that manifest the attributes of the sun: are all
aspects of one reality. And because the rays differ in rank in their
relationship to the sun -- solely due to the orientation of the earth,
and not because of any inherent difference in the essence of the rays
themselves -- not only do they appear as multiple, but in their
relationship one to the other it could be said that one is the source of
another, or that an earlier ray exists only to make the earth ready for
one who will come after.
