:PROPERTIES:
:ID:       C01960F7-4888-41AB-A97F-3AF107AEE158
:SLUG:     the-dream-example
:END:
---
title: The example of the dream
tags: journal
---

** Question
:PROPERTIES:
:CUSTOM_ID: question
:END:
In the Seven Valleys it mentions that Luqmán, "in proving to his son
Nathan the planes of resurrection and death, advanced the dream as an
evidence and an example." I have just a few thoughts to share on this
statement.

There is another Tablet, provisionally translated, where Bahá'u'lláh
uses the dream metaphor relative to the idea of resurrection -- or more
specifically, when something appears in other form after death:
https://bahai-library.com/brown_lawh_haqqu_nas. I find that this
explanation also connects with the other dream example, immediately
preceding His statement about Luqman in the Seven Valleys.

A few thoughts: For all things there is an essence and an appearance,
which are intimately related but not identical. Resurrection is the
return of essence in a new appearance. This happens in the world of
nature, in the return of the Manifestations --- and it happens when we
dream. In dreams, we observe things that connect to the waking world in
very indirect ways. This is because the essence is the same, but the
appearance varies between the waking world and the dream world, just as
they do through all the worlds of God.

If one understands how a "river" in a dream can represent the course of
one's life in the real world, and vice versa, then one should understand
how religious texts speak of spiritual realities using metaphors and
images: where "earth" may mean the heart and "heaven" can mean the Holy
Scriptures. The dream world is an example of the flexibility with which
spiritual essences reveal themselves in the world of Being, and so also
how the Ancient Beauty appears in various figures and guises throughout
history. This is why it is such a powerful "evidence and example", and
how this insight can lead to divine confirmations. The dream is, in this
way, an intra-personal reflection of how the spiritual and material
worlds are connected.

#+BEGIN_QUOTE
Consider the difference between these two worlds and the mysteries which
they conceal, that thou mayest attain to divine confirmations and
heavenly discoveries and enter the regions of holiness.

#+END_QUOTE
